finos/SymphonyElectron

- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
https://perzoinc.atlassian.net/browse/sda-2625 CLIENT Translation
> fix: sda-2625 Update translation

- src/locale/ja-JP.json
Fixed japanese screensnippet translation
[SDA-2625](https://perzoinc.atlassian.net/browse/SDA-2625)
Notes: Peanutbutter
> fix: SDA-2625 Fixed japanese screensnippet translation

- spec/__snapshots__/annotateArea.spec.tsx.snap
- spec/__snapshots__/snippingTool.spec.tsx.snap
- spec/annotateArea.spec.tsx
- spec/snippingTool.spec.tsx
- src/app/window-handler.ts
- src/renderer/components/annotate-area.tsx
- src/renderer/components/snipping-tool.tsx
- src/renderer/styles/snipping-tool.less
This PR adds the possibility for panning in the screen snippet annotate tool
[SDA-2705](https://perzoinc.atlassian.net/browse/SDA-2705)
Notes: Add possibility for panning
> feat: SDA-2705 Add possibility for panning

- spec/annotateArea.spec.tsx
- spec/snippingTool.spec.tsx
- src/app/analytics-handler.ts
- src/app/window-handler.ts
- src/renderer/components/annotate-area.tsx
- src/renderer/components/snipping-tool.tsx
This PR adds BI to the screen snippet annotate tool. It also fixes a bug where the snippet window is potentially too small on windows.
[SDA-2571](https://perzoinc.atlassian.net/browse/SDA-2571)
[SDA-2721](https://perzoinc.atlassian.net/browse/SDA-2721)
Notes: Adding BI to screen annotate
> feat: SDA-2571, SDA-2721 Add annotate BI and fix window size on windows

- package.json
- src/app/config-handler.ts
- src/app/main.ts
- src/app/version-handler.ts
- src/app/window-handler.ts
Same as #1125
Notes: fix blank screen on first install
> fix: SDA-2694: fix blank screen on first install

- package.json
- spec/__snapshots__/aboutApp.spec.ts.snap
- spec/aboutApp.spec.ts
- spectron/about-app.spec.ts
- src/app/version-handler.ts
- src/renderer/components/about-app.tsx
https://perzoinc.atlassian.net/browse/sda-2700 Showing SFE/SFE-lite version in About section
Notes: Showing SFE/SFE-lite version in About section
> fix: sda-2700 show 1.5/SFE 2.0/SFE-lite

- src/app/main.ts
Backport of #1128 
Notes: remove logic of deleting app cache on install
> fix: SDA-2731: remove logic of deleting app cache on install

- spec/annotateArea.spec.tsx
- spec/snippingTool.spec.tsx
- src/app/analytics-handler.ts
- src/renderer/components/annotate-area.tsx
- src/renderer/components/snipping-tool.tsx
Updated existing BI events and added more events, plus testing, to be consistent with new BI requirements.
[SDA-2571](https://perzoinc.atlassian.net/browse/SDA-2571)
Notes: Added BI events for screen annotate.
> feat: SDA-2571 Added correct BI events to screen annotate

- src/app/screen-snippet-handler.ts
- src/app/window-handler.ts
Refactoring opening of snippet tool, made it workAreaSize dependent. 
[SDA-2747](https://perzoinc.atlassian.net/browse/SDA-2747)
Notes: Refactoring snippet tool opening
> fix: SDA-2747 Refactoring opening of snippet tool

- src/app/main.ts
- src/app/window-handler.ts
Fixes the blank screen issue by using a work-around
[SDA-2731](https://perzoinc.atlassian.net/browse/SDA-2731)
- Restart SDA on a timeout if the the page is not loaded.
#1138 
Notes: fix blank screen issue
> fix: SDA-2731: fix blank screen issue

- src/app/window-handler.ts
Forward port of #1137 
Notes: reload app if stuck on white screen
> fix: SDA-2731: reload app if stuck on white screen

- src/app/window-handler.ts
Removed junk from merged PR
notes: Removed openDevTools
> fix: Removed openDevTools

- src/app/window-handler.ts
- src/renderer/components/screen-picker.tsx
https://perzoinc.atlassian.net/browse/sda-2754 CORE Preview what we are going to screen share
> fix: Preview screen share

- src/app/window-handler.ts
This reverts commit 5557c115c393ce5cd4e98b78602ac7742ec412b2.
Above commit broke devTools on main window.
notes: Revert
> fix: Revert "Changed API for getWindowOpts"

- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-2754 CORE Preview what we are going to screen share
notes: always quit red frame, and give the new red frame 300ms
> fix: sda-2754, always quit red frame, and give the new red frame 300ms

- scripts/build-mac.sh
- scripts/build-win64.bat
Backport of #1149 
Notes: move all build steps to the build scripts
> chore: SDA-2793: move all build steps to the build scripts

- scripts/build-win64.bat
> Update path to root

- src/locale/fr-FR.json
- src/locale/fr.json
update french replay translation
[SDA-2750](https://perzoinc.atlassian.net/browse/SDA-2750)
`reply: Répondre`
Notes: Update french translation
> feat: SDA-2750 (update french replay translation)

- spec/annotateArea.spec.tsx
- spec/snippingTool.spec.tsx
- src/app/screen-snippet-handler.ts
- src/app/window-handler.ts
- src/renderer/components/snipping-tool.tsx
This PR fixes multiple BI calls being triggered
[SDA-2571](https://perzoinc.atlassian.net/browse/SDA-2571)
Notes: Skalman
> fix: SDA-2571 Fixed triggering multiple BI calls

- src/renderer/components/notification-comp.tsx
- src/renderer/notification.ts
- src/renderer/styles/notification-comp.less
- Fix translation issues
- Fix notification overlap issue when replying
- Make notification `pop-up-menu` so that it is always on top of normal notifications
https://perzoinc.atlassian.net/browse/SDA-2811
https://perzoinc.atlassian.net/browse/SDA-2750
https://perzoinc.atlassian.net/browse/SDA-2806
Notes: Fix issues with notification quick reply feature
> fix: SDA-2811 (Fix css issue and make notification show as pop-up-menu)

- spec/__snapshots__/notificationSettings.spec.ts.snap
- spec/notificationSettings.spec.ts
- src/app/window-handler.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
- src/renderer/components/notification-settings.tsx
- src/renderer/styles/notification-settings.less
- Create new user interface for notification position window
- Add unit tests
N/A
> feat: SDA-2775: Notification Position Window New UI

- src/app/screen-snippet-handler.ts
https://perzoinc.atlassian.net/browse/sda-2836 CLIENT Screen annotate cancel capture
> fix: SDA-2836: If no capture, don't show annotate window

- src/renderer/components/notification-comp.tsx
- src/renderer/notification-handler.ts
- src/renderer/notification.ts
- Reposition notifications when on input 
- Push notification down
- Fix emoji rendering issue
Notes: Reposition notifications when on input
> fix: SDA-2806, SDA-2822 & SDA-2831 (Reposition notifications when on input)

- src/app/child-window-handler.ts
- src/app/window-handler.ts
- Auto reloads the main window in case of a blank screen
- Listens for load on `did-start-loading` webContents event
- Reloads the current url instead of falling back to the default pod url
N/A
> fix: SDA-2852: auto reload main window in case of blank screen

- spec/__snapshots__/notificationSettings.spec.ts.snap
- spec/mainApiHandler.spec.ts
- spec/notificationSettings.spec.ts
- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/common/api-interface.ts
- src/renderer/app-bridge.ts
- src/renderer/components/notification-settings.tsx
- src/renderer/ssf-api.ts
- src/renderer/styles/notification-settings.less
This PR adds the possibility to view notification position modal in dark mode, when dark mode is set on SFE-Lite.
> feat: SDA-2824 Set notification position modal darkmode

- src/renderer/components/notification-comp.tsx
- src/renderer/notification-handler.ts
- src/renderer/notification.ts
- src/renderer/styles/notification-comp.less
WIP - waiting for customer feedback
- Increase the notification height to make more space for message content
> fix: SDA-2857 (Increase the notification height to make more space for message content)

- src/renderer/styles/notification-settings.less
https://perzoinc.atlassian.net/browse/sda-2922 Notification Position modal - The number of monitor is not left-aligned
> fix: Left align the text

- src/app/window-handler.ts
> Removed unused parameter ChildProcess

- spec/__snapshots__/notificationSettings.spec.ts.snap
- src/renderer/components/notification-settings.tsx
https://perzoinc.atlassian.net/browse/sda-2947 SDA 9.2.0 - The "position" tooltip is not localized in Notification settings
> fix: translation of tool tip

- src/renderer/components/notification-comp.tsx
- src/renderer/styles/notification-comp.less
- Switch to default HTML input element
> fix: SDA-2955 (Switch to default HTML input element)

- spec/appMenu.spec.ts
- spec/mainApiHandler.spec.ts
- src/app/app-menu.ts
- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- **Note: Work in progress for the UTs.**
Add Zoom restriction as per the following
- Set the maximum zoom-in % to 150% (goes from 100% < 110% < 125% < 150%)
- Set the maximum zoom-out % to 70% (goes from 100% > 90% > 80% > 70%)
[C2-9049](https://perzoinc.atlassian.net/browse/C2-9049)
> feat: C2-9049: Implement zoom restriction in SDA

- scripts/build-win64.bat
- src/app/window-handler.ts
Enable remote module explicitly
#1198
> fix: SDA-3030: enable remote module explicitly

- .vscode/launch.json
This PR adds launch config for st2 in VS Code
> Add VS Code launch config for st2

- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-2992 SDA 9.2 766 doesn't retain "SSO" setting on upgrade
> fix: sda-2992 safe guard if user config is missing

- auto_update/auto_update.sln
- auto_update/auto_update_helper.cpp
- auto_update/auto_update_helper.vcxproj
- auto_update/auto_update_service.cpp
- auto_update/auto_update_service.vcxproj
- auto_update/ipc.h
- auto_update/package.json
- package.json
Setting up new projects for auto update service and helper, and adding some (partially cleaned up and refactored) code from the POCs
> SDA-3024 Initial code setup for auto update

- src/app/app-state-handler.ts
- src/app/main-api-handler.ts
> fix: Prevent display to go to sleep if user is in a meeting

- spec/mainApiHandler.spec.ts
- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/renderer/app-bridge.ts
- src/renderer/notification.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
This PR adds an API for closing all electron windows from SFE-Lite. To be used for now when signing out, which should close all notifications.
> SDA-3033 Add ability to close all windows from SFE-Lite

- RELEASE_NOTES.md
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/install_instructions_win.md
Added support for LAUNCH_ON_INSTALL installation parameter
> SDA-3102 Added support for LAUNCH_ON_INSTALL installation parameter

- RELEASE_NOTES.md
- config/Symphony.config
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/install_instructions_win.md
- src/app/auto-launch-controller.ts
- src/app/config-handler.ts
- src/app/main-api-handler.ts
- src/app/main.ts
Added USER_DATA_PATH installation parameter to be able to control where user data is saved
> SDA-3137 Added USER_DATA_PATH installation parameter

- package.json
Fix the build problem on windows (also mac)
> fix: try to get swift-search

- src/renderer/preload-main.ts
https://perzoinc.atlassian.net/browse/sda-3133 Console error is shown when click on toast notification with SDA in Full screen mode
> fix: Check we are in full screen

- src/renderer/notification-handler.ts
https://perzoinc.atlassian.net/browse/sda-3143 JavaScript exception while closing out persisting notifications
> fix: To avoid the pop up and save the error in the log

- auto_update/auto_update.sln
- auto_update/package.json
- auto_update/testfw.h
- auto_update/tests.cpp
- auto_update/tests.vcxproj
Added a test framework, integrated it with npm build script, and set up a dummy test that always pass
> SDA-3147 Set up test framework to be run during build

- installer/win/install_instructions_win.md
Improve installation instructions
> SDA-3161 Improve installation instructions

- auto_update/auto_update_helper.cpp
- auto_update/auto_update_helper.vcxproj
- auto_update/auto_update_service.cpp
- auto_update/auto_update_service.vcxproj
- auto_update/ipc.h
- auto_update/run_loop.bat
- auto_update/testfw.h
- auto_update/tests.cpp
- auto_update/tests.vcxproj
SDA-3148 IPC client/server implementation
SDA-3149 Tests for IPC client/server 
Most of the changes are in the file ipc.h which is not expanded by default
> SDA-3148 Implementation and tests for IPC client/server module

- package.json
https://perzoinc.atlassian.net/browse/c2-10207 Swift-search npm package is missing files
> Use the handmade swift-search with all libs

- docs/development/DEV_SETUP.md
- installer/win/WixSharpInstaller/Symphony.cs
Same as https://github.com/symphonyoss/SymphonyElectron/pull/1230
> SDA-3210 Supporting boolean as msi arg 

- installer/win/WixSharpInstaller/Symphony.cs
Mirror of this [PR](https://github.com/symphonyoss/SymphonyElectron/pull/1233)
> SDA-3210 Extending boolean regex to newlines

- src/app/window-handler.ts
Replacing user-agent to support SSSO and RTC
Mirror of #1237
> SDA-3201 Replacing user-agent to support Calls and snipping tool

- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
Let the user setting his zoom value from the General Settings menu
[C2-11081](https://perzoinc.atlassian.net/browse/C2-11081)
https://github.com/SymphonyOSF/SFE-Lite/pull/7519
**- Old SDA**
**- Browser**
- New SDA
https://user-images.githubusercontent.com/52144470/123741242-e1a02500-d8d3-11eb-82e0-2b4df0c98bc3.mp4
> C2-11081 Let the user setting his zoom value from the General Settings menu

- src/renderer/components/notification-comp.tsx
- src/renderer/styles/notification-comp.less
Fix for external room name with external badge taking too much place in not-flashing mode.
> SDA-3268 Ext room name length fix

- src/renderer/components/notification-comp.tsx
- src/renderer/styles/notification-comp.less
Back-porting latest dev from main branch to 9.2.x:
- Backward compatibility with SDA 9.2.0 and Client 1.5
- Close button issue that brings to front desktop app
> SDA-3237 SDA-3267 Backward compatibility and close button fix

- src/app/version-handler.ts
- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-3192 Change command/option/3 to use the daily bff
> fix: sda-3192 option+command+3 use bff-daily

- spec/notificationComp.spec.ts
- src/renderer/components/notification-comp.tsx
> SDA-3281 Client 1.5 not sending user picture 9.2.x

- spec/notificationComp.spec.ts
- src/renderer/components/notification-comp.tsx
Back porting https://github.com/symphonyoss/SymphonyElectron/pull/1254
> SDA-3292 Close button hovering fix

- src/app/window-utils.ts
- src/renderer/notification.ts
https://perzoinc.atlassian.net/browse/sda-3312 I18N - Toast notification - 'Close' and 'Reply' button are not translated
> fix: Clean up after new locale is set

- auto_update/auto_update_service.c
Validation of digital signature in auto update service, so it will reject installers not signed by a Symphony certificate
> SDA-3260 Added validation of digital signature in auto update service

- spec/__snapshots__/colorPickerPill.spec.tsx.snap
- spec/__snapshots__/snippingTool.spec.tsx.snap
Fix snapshot test for screen capture
> SDA-3322 Fix snapshot test

- RELEASE_NOTES.md
- package.json
- Upgrade SDA version to 14.0.0
- Update release note template
> SDA-3362 (Upgrade SDA version to 14.0.0)

- auto_update/auto_update_helper.c
- auto_update/auto_update_service.c
- auto_update/manifest.xml
- auto_update/package.json
- src/app/auto-update-handler.ts
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/app-bridge.ts
- src/renderer/ssf-api.ts
Adding functionality to the demo app to invoke the native auto_update_helper.exe through a newly added auto-update-handlers.ts. Also includes changes to native auto update code, for additional logging and including a manifest to ensure they don't require elevated rights to run.
> Calling auto update from demo app

- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- spec/windowsTitleBar.spec.ts
- src/renderer/components/windows-title-bar.tsx
- Fix missing title bar on leave fullscreen
> SDA-3437 (Fix missing title bar on leave fullscreen)

- src/app/window-utils.ts
- Workaround to fix dev tools resize issue
> 🐛  SDA-3435 (Workaround to fix devtools resize issue)

- src/app/window-utils.ts
- Workaround for the main view container height resize issue
> 🐛  SDA-3422 (Workaround for the main view container height resize issue)

- src/app/main-api-handler.ts
- Fix hamburger menu focus issue
- Cut, copy & paste edit menu items work as expected
> 🐛  SDA-3434 (Fix hamburger menu focus issue)

- src/common/logger.ts
- Add safety check for logger window to prevent from accessing destroyed web contents
> 🐛  SDA-3430 (Add safety check for logger window)

- src/app/window-utils.ts
- Publish full-screen events for the snack bar to work as expected in Windows OS
> 🐛  SDA-3437 (Fix event not being emitter due to throttle)

- installer/win/WixSharpInstaller/WelcomeDialog.cs
Accessibility - Bringing welcome screen foreground to be able to use keyboard pressing Enter.
> SDA-3451 Windows - Accessibility - Bringing welcome screen foreground

- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/renderer/app-bridge.ts
- src/renderer/preload-main.ts
- Move Swift Search API from remote module to IPC
- Optimize spellchecker module by using async
> SDA-3366 (Update swift search API and optimize spellchecker sync calls)

- package-lock.json
- package.json
- src/app/activity-detection.ts
- src/app/analytics-handler.ts
- src/app/crash-handler.ts
- src/app/download-handler.ts
- src/app/main-api-handler.ts
- src/app/main-event-handler.ts
- src/app/protocol-handler.ts
- src/app/reports-handler.ts
- src/app/screen-snippet-handler.ts
- src/app/spell-check-handler.ts
- src/app/window-actions.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- src/common/logger.ts
- tsconfig.json
- Improving SDA logs for API calls.
- Also took the opportunity to simplify dev env script.
- Electron update.
> SDA API calls logging

- src/app/window-handler.ts
- src/renderer/preload-component.ts
> 🐛 SDA-3469 (Fix welcome screen title)

- src/app/window-handler.ts
- Add a command-line flag for starting SDA maximized
> ✅ SDA-3476 (Add a command line flag for starting SDA maximized)

- src/app/child-window-handler.ts
- Fix issues with popout window by not assigning parent window opts
> 🐛 SDA-3431 (Fix issues with popout window by not assigning parent window opts)

- src/app/child-window-handler.ts
- Fix issues with popout window by not assigning parent window opts
- Add default child window opts
> SDA-3475 (Fix issues with popout window by not assign parent window opts)

- src/app/window-handler.ts
- Fix issues with command line argument `--window-size`
> 🐛  SDA-3482 (Fix command line argument --window-size)

- src/app/window-actions.ts
- Fix sending bounds to main web contents
> 🐛 SDA-3475 (Fix sending bounds to main web contents)

- src/app/window-handler.ts
- Remove assigning the window size to config and set the value directly
> 🐛 SDA-3475 (Remove assigning window size to config)

- src/app/window-utils.ts
- Remove custom title bar on fullscreen as title bar was blocking the client UI from accessing
> 🐛  SDA-3450 (Remove title bar on fullscreen)

- src/app/chrome-flags.ts
[SDA-3484](https://perzoinc.atlassian.net/browse/SDA-3484)
- Disable smooth scrolling 
- `disable-threaded-scrolling`
- `disable-smooth-scrolling`
> 🐛 SDA-3484 (Append disable smooth scroll chromium flag)

- src/app/child-window-handler.ts
- Load preload js file for popout window in 1.5
> 🐛  SDA-3487 (Load preload js file for popout window in 1.5)

- src/app/window-utils.ts
- Delay resizing the window to make sure the client resize is done correctly
> 🐛  SDA-3422 (Delay resizing the window)

- src/app/window-actions.ts
- Focus the main web content when the window is restored
> SDA-3516 (Focus main web contents on restore)

- src/app/window-utils.ts
Kill screen share indicator frame before reloading
> SDA-3520 Kill screen share indicator frame before reloading

- spec/__snapshots__/aboutApp.spec.ts.snap
- src/app/window-handler.ts
- Clear snippet window reference after the close
> SDA-3530 (Clear snippet window reference after close)

- src/app/window-utils.ts
- Disable Zoom for notification windows
> SDA-3440 (Disable Zoom for notification windows)

- package.json
- Update electron spellchecker repo URL
> SDA-3489 (Update electron spellchecker repo url)

- src/app/main.ts
- Focus main webContents on "second-instance" event
> SDA-3516 (Focus main webContents on "second-instance" event)

- src/app/main-api-handler.ts
Hiding data received through API.
> SDA-3548 Hide data field for notifications

- package-lock.json
- package.json
- remove `copy image URL` context menu item
> SDA-3489 (bump electron spellchecker version to 2.3.4)

- spec/mainApiHandler.spec.ts
- src/app/main-api-handler.ts
- src/app/window-handler.ts
- Refocus to main webContents when the title bar action buttons are clicked
> SDA-3516 (Refocus to main webContents when title bar action buttons are clicked)

- src/renderer/notification.ts
- Reset the width and height of the inactive notification to the default size
> SDA-3544 (Reset the width and height of the inactive notification to the default size)

- package-lock.json
- package.json
request lib is introducing json-schema vulnerability. This lib has been removed from spellchecker as not being used.
> SDA-3568 Bump spellchecker version to 2.3.6

- src/app/app-menu.ts
- src/app/reports-handler.ts
- src/app/window-handler.ts
- Add accelerator to export logs
[#9969](https://github.com/SymphonyOSF/SFE-Lite/pull/9969)
> SDA-3554 (Add accelerator to export logs)

- src/app/app-state-handler.ts
- If the id value === 0 the `powerSaveBlocker` was never stopped
- Only Check if the id is undefined
> SDA-3574 (Fix the condition to validate undefined)

- installer/win/WixSharpInstaller/Symphony.cs
- package-lock.json
- package.json
- spec/citrixHandler.spec.ts
- src/app/citrix-handler.ts
In order to support Citrix Media Optimization, it is necessary for an extension to be able to query the current status. Only when the redirection support is active is it necessary to proceed with loading and initializing the full Citrix client-side SDK.
https://perzoinc.atlassian.net/browse/SDA-3565
> SDA-3565 Citrix media redirection presence update

- src/app/citrix-handler.ts
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
Citrix media redirection API endpoint + demo page update.
> SDA-3565 Citrix media redirection status API endpoint

- src/app/init.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- src/common/env.ts
- src/renderer/notification.ts
> SDA-3577 (Remove isNodeEnv usage)

- installer/win/WixSharpInstaller/Symphony.cs
- scripts/build-win64.bat
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/app-bridge.ts
- src/renderer/ssf-api.ts
Disabling auto-update service for SDA 14 release.
> Disabling auto-update service and helper

- src/app/main-api-handler.ts
Received logs shouldn't be logged in SDA logs.
> SDA-3580 Logging cleanup

- src/app/window-handler.ts
Logging more details while having renderer crash.
> Enriched renderer crash logs

- package.json
- Update SDA version to 14.1.0
> SDA-3583 (Upgrade SDA version to 14.1.0)

- src/renderer/styles/notification-comp.less
Decreasing max notification title length
> SDA-3585 Long notification title fix

- .github/workflows/ci.yml
- src/app/citrix-handler.ts
Updating Citrix media redirection registry key.
> SDA-3593 Citrix redirection registry key update

- src/renderer/components/notification-comp.tsx
Mirror of https://github.com/finos/SymphonyElectron/pull/1349
> SDA-3525 Removing reply tooltip for notifications (#1349)

- spec/config.spec.ts
- src/app/config-handler.ts
- src/app/main-api-handler.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/common/utils.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
- Create a new API for SDA to display a banner on the client
- Compare the cloud-config and update the client
- Coming soon
> SDA-1824 (client banner api & cloud config update identifier)

- spec/__snapshots__/welcome.spec.ts.snap
- spec/welcome.spec.ts
- src/renderer/components/welcome.tsx
- src/renderer/styles/welcome.less
Removing SSO checkbox on Welcome screen
JIRA Ticket: https://perzoinc.atlassian.net/browse/SDA-3606
Screenshot:
> SDA-3606 Removing SSO checkbox in Welcome screen

- src/app/window-handler.ts
- src/app/window-utils.ts
- src/renderer/notification.ts
https://perzoinc.atlassian.net/browse/SDA-3219
> SDA-3219 Disabling aux click

- src/app/window-handler.ts
Transparent background for screen share indicator window.
> Transparent background for screen share indicator window

- spec/dialogHandler.spec.ts
- src/app/dialog-handler.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
Allowing insecure URLs one by one and only once.
> SDA-3140 Insecure sites - Ability to allow insecure sites only once

- spec/basicAuth.spec.ts
- src/app/window-handler.ts
- src/renderer/components/basic-auth.tsx
Preventing Submit event to navigate.
> SDA-3592 Basic auth popup fix

- spec/__snapshots__/welcome.spec.ts.snap
- spec/welcome.spec.ts
- src/renderer/components/welcome.tsx
- src/renderer/styles/welcome.less
Backporting https://github.com/finos/SymphonyElectron/pull/1367
> SDA-3606 Removing SSO checkbox in Welcome screen (#1367)

- spec/basicAuth.spec.ts
- src/app/window-handler.ts
- src/renderer/components/basic-auth.tsx
Backport of https://github.com/finos/SymphonyElectron/pull/1365
> SDA-3592 Prevent redirection on form submission (#1365)

- package-lock.json
- package.json
> SDA-3642 Archiver upgrade due to vulnerability

- src/app/context-menu-builder.ts
- Disable Inspect element context menu for production
> SDA-3637 (disable InspectElement for prod)

- src/app/window-handler.ts
Maximized app positioning bugfix at start up.
> SDA-3652 App mispositioning bugfix

- package-lock.json
- package.json
- src/app/window-handler.ts
SDA-3646 Backport of https://github.com/finos/SymphonyElectron/pull/1389 https://github.com/finos/SymphonyElectron/pull/1393
> SDA-3646 App shared screen is shown behind SDA when user starts screen share

- src/app/window-utils.ts
- Fix window will navigate issue on main webContents
https://github.com/finos/SymphonyElectron/pull/1395
> SDA-3662 (Fix window will navigate issue on main webContents)

- src/app/window-actions.ts
- Publish main events only for events from main window
- Ignore window events from popout window
https://github.com/finos/SymphonyElectron/pull/1398
> SDA-3673 (Publish main events only for events from main window)

- src/app/child-window-handler.ts
- src/app/window-handler.ts
Child window is displayed behind main window when main window has "AlwaysOnTop" option enabled.
> SDA-3672 Child window displayed behind main window

- spec/dialogHandler.spec.ts
- src/app/dialog-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
> SDA-3140 Certificates validation bugfix

- package-lock.json
- package.json
Upgrading to Electron 17.4.2 to get CVE-2022-1364 fix
> SDA-3678 Electron upgrade

- src/app/child-window-handler.ts
- Set child window fullscreen to false 
17.x - https://github.com/finos/SymphonyElectron/pull/1408
> SDA-3669 (Set child window fullscreen to false)

- installer/win/WixSharpInstaller/Symphony.cs
- spec/hwndHandler.spec.ts
- spec/mainApiHandler.spec.ts
- src/app/hwnd-handler.ts
- src/app/main-api-handler.ts
- src/demo/index.html
- src/renderer/ssf-api.ts
This reverts the revert of the RTC window handler fixes, similar to #1402 but for the 17.0.x branch.
> SDA-3611 - Revert "Revert "Bugfix/rtc 17.0.x (#1372)" (#1375)"

- src/app/window-actions.ts
- src/renderer/components/windows-title-bar.tsx
Bugfix: Ability to maximize SDA by dragging after putting the window in fullscreen.
> SDA-3679 Ability to maximize SDA by dragging

- src/app/window-actions.ts
- src/app/window-utils.ts
- src/renderer/components/windows-title-bar.tsx
Adding move event registration to title bar
> SDA-3679 Adding move event registration to title bar

- src/app/window-utils.ts
Preventing navigation to http URLs.
> SDA-3221 Preventing navigation to http URLs

- src/app/window-handler.ts
> SDA-3677 Screen share bugfix for Citrix Windows

- src/app/window-handler.ts
- `skipTaskbar` for screen share indicator frame window
https://github.com/finos/SymphonyElectron/pull/1422
> SDA-3704 (skipTaskbar for screen share indicator frame window)

- src/app/window-handler.ts
- `skipTaskbar` for screen share indicator frame window
https://github.com/finos/SymphonyElectron/pull/1422
> SDA-3704 - skipTaskbar for screen share indicator frame window

- package-lock.json
- src/renderer/preload-main.ts
- Network error page will be injected to DOM only once
https://github.com/finos/SymphonyElectron/pull/1426
> SDA-3705 (Render network error once)

- src/app/window-handler.ts
- Close placeholder window only on Windows as SDA-3656/SDA-3715 only happens on Mac
> SDA-3656 (Close placeholder window only on Windows)

- src/app/child-window-handler.ts
- src/app/window-handler.ts
This reverts commit a92caf642c9a3773aa3baa87f696db26b1804740.
Reverting SDA-3672: while AlwaysOnTop option is enabled, SDA child windows should be minimized when focusing on main app.
> Revert "SDA-3672 Focusing on child window after creation (#1399)"

- src/app/window-actions.ts
- Use separate logic to update the window maximized state
- Revert #1410 
Backport #1433
> SDA-3726 (Use separate logic to update the window maximized state)

- package-lock.json
- package.json
- src/app/main.ts
> SDA-3731 shell-path upgrade

- package-lock.json
- package.json
> Bumping SDA revision

- installer/win/WixSharpInstaller/Symphony.cs
- package-lock.json
- package.json
- src/app/init.ts
- tsconfig.json
- Fix app id
- Include everything from **asar.unpacked** into packed app (for now this only adds **~2mb**) instead of selecting specific build files which causes `user errors`
> SDA-3733 (Include everything from node_modules)

- installer/win/WixSharpInstaller/Symphony.cs
> SDA-3770 Installer fix

- package.json
- Add extra files (screen snippet, cloud9 & screen share indicator frame)
- Remove nsis and dmg build targets
> SDA-3589 (Remove unwanted targets and add extra files)

- build/installer.nsh
- package-lock.json
- package.json
- scripts/build-win64.bat
- src/app/app-menu.ts
- src/app/auto-update-handler.ts
- src/app/main-api-handler.ts
- src/app/main.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
- Fix issues with All user installations
> SDA-3589 (Fix issues with All user installations)

- scripts/build-win64.bat
> SDA-3589 (Fix signing nsis file path)

- package-lock.json
- package.json
- scripts/build-win64.bat
- scripts/update_checksum.js
Yaml file update with right URL prefix and new checksum post code-signing
> Yaml file update with right URL prefix and new checksum post code-signing

- package.json
- src/app/main-api-handler.ts
- To save the package size Include cloud9 in main dir and remove it from resource dir
> SDA-3589 (Include cloud9 in main dir and remove it from resource dir)

- package-lock.json
- package.json
Scrolling issue fixed in Electron v19.0.10
> SDA-3790 Electron version bump 19.0.10

- package-lock.json
- package.json
- src/app/auto-update-handler.ts
- Use default channel for auto-update
> SDA-3589 (Use default channel for auto update)

- config/Symphony.config
- Update the default channel to `latest`
> SDA-3589 (Change the default channel to latest)

- scripts/build-win64.bat
- src/app/auto-update-handler.ts
Wrong server URL + wrong filename bugfix
> SDA-3589 Server url + Yml file update bugfix

- src/app/app-menu.ts
Display 'Check for updates' menu entry after login
> SDA-3794 Display 'Check for updates' menu entry after login

- installer/win/WixSharpInstaller/Symphony.cs
- package.json
- src/app/config-handler.ts
- src/app/init.ts
- src/app/main.ts
- src/app/window-handler.ts
- Rever the app id changes 
- Read user config before starting the application
> SDA-3780 (Read user config before starting the application)

- installer/mac/symphony-mac-packager.pkgproj
Ability to install SDA for local user only
> SDA-3589 Ability to install SDA for local user only 

- build/installer.nsh
- src/app/auto-update-handler.ts
- src/app/config-handler.ts
- src/app/main-api-handler.ts
- Backup and overwrite global config to persist data
> SDA-3800 (Backup and overwrite global config to persist data)

- src/app/config-handler.ts
- Ignore config copy issue for global installed SDA
- It is not possible to copy config into system installed SDA
> SDA-3800 (Ignore config copy issue for global installed SDA)

- package.json
- scripts/build-win64.bat
Removing unnecessary files to decrease file size:
.exe ~ -30%
MSI  ~ -25%
> Removing unnecessary files

- src/app/window-handler.ts
- Initialize variables `onCreateApplication`
https://perzoinc.atlassian.net/browse/SDA-3813
https://perzoinc.atlassian.net/browse/SDA-3814
> SDA-3813 (Initialize variables on create Application)

- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- src/app/window-handler.ts
- src/renderer/components/windows-title-bar.tsx
- src/renderer/styles/title-bar.less
- Disable only maximize button and not minimize button to match the SDA 9.2 version
> SDA-3815 (Disable maximize button and enable minimize button)

- src/app/window-utils.ts
> SDA-3784 SDA-3834 Resizing fix and optimization

- src/app/window-handler.ts
> SDA-3813 - update variables on create Application (#1472)

- src/app/child-window-handler.ts
> SDA-3819 (Fix initial pop-out loading issue)

- src/app/auto-update-handler.ts
> Auto-update server URL update

- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
> SDA-3839 Resize SDA if unmaximizing

- src/app/auto-update-handler.ts
Auto-update .yml file is now served by the backend
> Updating auto-update URL

- src/app/local-menu-shortcuts.ts
- src/app/window-handler.ts
> SDA-3844 (Use local shortcuts to fix issues on Windows)

- src/app/local-menu-shortcuts.ts
> SDA-3869 (include more local shortcuts to fix issue on Windows)

- installer/win/WixSharpInstaller/ProgressDialog.cs
- Remove UAC warning message for current user install
> SDA-3855 (Remove UAC warning message for current user install)

- src/app/auto-update-handler.ts
- src/app/config-handler.ts
> SDA-3875 (Skip welcome screen for auto update)

- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
> SDA-3871 Closing screensharing frame and screen picker window after the end of a meeting

- src/app/app-menu.ts
- src/app/window-handler.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
> SDA-3875 (Update corporate switch shortcuts keys)

- package-lock.json
- package.json
Pump Electron to 20.0.x
Put screenshots, videos or gif demos of what was the behaviour before your PR.
Put screenshots, videos or gif demos of what is the behaviour after your PR.
> SDA-3861_20: Upgrade SDA to latest Electron 20 release

- installer/win/WixSharpInstaller/Symphony.cs
- package.json
Bumping SDA version for its release
> Bumping SDA version

- build/installer.nsh
- src/app/config-handler.ts
- src/app/main-api-handler.ts
- Set up first time launch for auto updated version
> SDA-3913 (Set up first time launch for auto updated version)

- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
> SDA-3892_Crowdin: Remove few files for Crowdin Test

- src/app/window-handler.ts
- src/renderer/styles/about-app.less
About window css and size update for macOS
> SDA-3892 macOS styling

- src/app/window-actions.ts
Ability to pop-up the menu by pressing alt key
> SDA-3929 Ability to pop-up the menu by pressing alt key

- src/locale/fr-FR.json
- src/locale/fr.json
> New translations in main

- build/installer.nsh
- package.json
Auto update - moving temp config file in local appData folder
> SDA-3913 SDA-3913 Auto update - moving temp config file in local appData folder

- src/app/app-menu.ts
- src/app/auto-update-handler.ts
- src/app/main-api-handler.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/renderer/ssf-api.ts
Prevent displaying auto-update banner if triggered by recurring check and there is no update available
> SDA-3941 Prevent displaying auto-update banner if triggered by recurring check and there is no update available

- src/app/app-menu.ts
- src/locale/en-US.json
- src/locale/en.json
Adding IV channel for corp auto-update
> SDA-3964 Adding IV channel for corp auto-update

- README.md
> Removing old Symphony Software Foundation badge

- spec/__snapshots__/menu-button.spec.tsx.snap
- src/renderer/components/menu-button.tsx
- src/renderer/styles/snipping-tool.less
- src/renderer/styles/theme.less
> SDA-3959: Fixing some UI css bugs

- spec/mainApiHandler.spec.ts
- src/app/main-api-handler.ts
- src/app/screen-snippet-handler.ts
- src/app/window-handler.ts
- src/common/api-interface.ts
- src/renderer/app-bridge.ts
- src/renderer/ssf-api.ts
Add an additional API to give user ability to hide SDA while capturing using 2nd parameters 'hideOnCapture'
> SDA-3933: Add api to hide SDA

- src/app/app-menu.ts
- src/app/context-menu-builder.ts
- src/locale/en-US.json
- src/locale/en.json
> SDA-3966 Support Paste as plain text

- src/app/context-menu-builder.ts
> SDA-3970 Add copy capability on links

- scripts/macos_update_yml.js
- scripts/windows_update_checksum.js
Updating auto-update installers CDN URL
> Updating installers CDN URL

- package-lock.json
- package.json
> SDA-3988 CVE-2022-4135 + bump version

- package.json
> Bump SDA version to 22

- src/app/window-actions.ts
Bring to front on notification bugfix
> SDA-3996 Bring to front on notification bugfix

- package-lock.json
- package.json
Update the optional dependency symphony-c9-shell to 3.19.0-0.98.3.124.
> SDA-3997 Update symphony-c9-shell

- README.md
> Adding best practices badge

- src/app/version-handler.ts
- src/renderer/components/about-app.tsx
Version field should always display 2.0 version in "About" window.
> SDA-4036 Remove 1.5 related code for version discovery

- package-lock.json
- package.json
- src/app/screen-snippet-handler.ts
- src/app/stores/window-store.ts
Hide and restore fullscreen windows while taking a screenshot
> SDA-3993 (Restoring full-screened windows while taking a screenshot)

- src/app/main-api-handler.ts
- src/app/presence-status-handler.ts
- src/app/stores/presence-status-store.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/renderer/ssf-api.ts
IDLE presence status bugfix: we rely on received presence status group to set the presence.
> SDA-4070 IDLE presence status bugfix

- src/app/presence-status-handler.ts
- src/app/window-utils.ts
- src/locale/en-US.json
- src/locale/en.json
Meeting status displayed in sys tray
> SDA-4069 Meeting status displayed in sys tray

- src/app/window-handler.ts
Mirror: https://github.com/finos/SymphonyElectron/pull/1810
> SDA-4113: Add url from CMD

- src/app/window-handler.ts
There was an error check, added remained commit
> SDA-4113: Update the remained commit havent pushed

- src/app/window-handler.ts
Whenever user had GlobalConfig available, they will be directed to Login instantly
> SDA-4143: by pass welcome screen

- src/app/window-utils.ts
Mirror: https://github.com/finos/SymphonyElectron/pull/1823
> SDA-4144: The presence status is still shown when reloading SDA

- src/app/window-utils.ts
> SDA-4100 Reload SDA should reload pod URL and not current URL (#1828)

- src/renderer/styles/snipping-tool.less
> SDA-4134 Screenshot tool - JP copy dropped in 2 lines (#1827)

- src/app/protocol-handler.ts
> SDA-4140 Focus SDA after browser login (#1825)

- src/app/main-api-handler.ts
- src/renderer/components/basic-auth.tsx
- src/renderer/styles/basic-auth.less
> SDA-4120 Proxy authentication on Browser login flow (#1826)

- src/app/window-handler.ts
Mirror: https://github.com/finos/SymphonyElectron/pull/1833
> SDA-4143: Adding bug fix

- src/app/notifications/call-notification.ts
- src/renderer/styles/call-notification.less
- Fix the EXT alignment issue
- Fix Closing existing call notification window
Before
After
> SDA-4233 & SDA-4232 (Fix EXT alignment and closing exiting window issue)

- src/renderer/components/call-notification.tsx
- Move the click handler onto button rather than the text
> SDA-4241 (Move click handler on to button)

- src/renderer/notification-handler.ts
- Fix the issue with the lower-left calculation
https://github.com/finos/SymphonyElectron/pull/1909
> SDA-4243 (Fix issue with lower-left calculation)

- spec/aboutApp.spec.ts
- src/app/window-handler.ts
- src/locale/en-US.json
- src/locale/en.json
- src/renderer/components/about-app.tsx
- src/renderer/styles/about-app.less
- Add support to update user POD settings
> SDA-4186 (Add support to update user POD settings)

- spec/appCacheHandler.spec.ts
- src/app/app-cache-handler.ts
- src/app/app-state-handler.ts
- src/app/config-handler.ts
- src/app/dialog-handler.ts
- src/app/window-handler.ts
- Update user config once on before-quit
> SDA-4247 (Update user config once on before-quit)

- src/app/window-handler.ts
Add a fix to update userConfig variable to latest
> SDA-4244_23.8: Reload will cause config went unavailable and redirect to Symphony Contact

- src/app/child-window-handler.ts
- src/app/protocol-handler.ts
SDA will now support +tel on opening a new page with target=_blank
> SDA-4234: Support Tel Protocol on loading _blank

- src/app/window-handler.ts
Add a fix to update userConfig variable to latest
Mirror: https://github.com/finos/SymphonyElectron/pull/1927
> SDA-4244: Reload will cause config went unavailable and redirect to Symphony Contact

- src/renderer/components/about-app.tsx
- Handle key down on pod input - AboutApp
> SDA-4253 (Handle key down on pod input - AboutApp)

- src/app/window-handler.ts
- Workaround to fix always on top issue
electron issue https://github.com/electron/electron/issues/31505
> SDA-4251 (Workaround to fix always on top issue)

- src/app/config-handler.ts
- src/app/window-handler.ts
- src/locale/en-US.json
- src/locale/en.json
- Handle uncaught exceptions
- Add safety check for user config
> SDA-4265 (Handle uncaught exceptions)

- src/app/stats.ts
> SDA-4266 (Log SDA version info)

- src/app/config-handler.ts
- src/app/window-handler.ts
> SDA-4270 config file persistency bugfix

- src/app/auto-update-handler.ts
- Refactor auto update handler
> SDA-4235 (Refactor auto update handler)

- src/app/app-menu.ts
- src/app/config-handler.ts
- Remove the user config file if the content is empty
- New user config will automatically be created
> SDA-4267 (Remove config file if the file is empty)

- package-lock.json
- package.json
This updates the C9shell with [the recent build ](https://c9deploy.xhoot.com/c9trader/3.26.98.2/C9Installer.msi)
> Update C9shell to 3.26.0-0.98.2.165

- package-lock.json
- package.json
- spec/__mocks__/electron.ts
- src/app/analytics-handler.ts
- src/app/auto-update-handler.ts
- src/app/config-handler.ts
- src/app/main-api-handler.ts
- src/app/memory-monitor.ts
- src/app/stats.ts
- src/app/window-handler.ts
- Add SDA session analytics
- Add more parameters for auto-update analytics
New Third-party module `systeminformation`
Time taken for fetching all the system information 
```
MacOS ~3sec
Windows ~5sec
```
https://github.com/SymphonyOSF/SFE-Lite/pull/15369
> SDA-4290 (Add SDA session & auto update analytics)

- src/app/auto-update-handler.ts
- Update auto-update channel end point
`client-bff/sda-update -> apps/sda-update/default`
> SDA-4317 (Update auto-update channel end point)

- src/app/stats.ts
- Optimize logic to speed up close time
- Analytics will not hold SDA from closing
- Close will have the `~15min` data rather than the latest
https://github.com/finos/SymphonyElectron/pull/1953
> SDA-4291 (Optimize logic to speed up close time)

- spec/childWindowHandle.spec.ts
- spec/config.spec.ts
- src/app/analytics-handler.ts
- src/app/auto-update-handler.ts
- src/app/config-handler.ts
- Create BI analytic events for SDA installation
https://github.com/SymphonyOSF/SFE-Lite/pull/15452
> SDA-4290 (Create Install BI analytic events)

- spec/callNotification.spec.ts
- src/renderer/components/call-notification.tsx
- src/renderer/notification-handler.ts
- src/renderer/styles/call-notification.less
- src/renderer/styles/theme.less
- src/renderer/styles/tool-tip.less
Backporting #1950 #1961 #1966 #1970
> Call notification bugs backport

- src/app/bi/analytics-handler.ts
- src/app/bi/auto-update-analytics.ts
- src/app/config-handler.ts
- src/app/main-api-handler.ts
- src/app/stats.ts
- src/app/window-handler.ts
- src/renderer/ssf-api.ts
- Queue & send analytics data once the client registers the analytics handler
- Write `End`, `Logout`, and `InstallStarted` to a local file
> SDA-4361 (Queue & send analytics data once client registers the func)

- src/app/auto-update-handler.ts
- Check for empty objects
- getFilteredCloudConfigFields filters out truthy values
> SDA-4290 (Update check to validate object length)

- src/common/utils.ts
- src/renderer/ssf-api.ts
- Add delay when invoking analytics event handler function
- This is required to add a difference in the timestamp
> SDA-4291 (Add delay for sending analytics events)

- src/app/auto-update-handler.ts
- Always retrieve the latest registry channel
- registry entry can be updated externally
> SDA-4372 (Always retrieve latest registry channel)

- src/app/local-menu-shortcuts.ts
- src/app/window-handler.ts
- Add a fix now user wont be able to open devtool with config 'enableDevTools' installed as false
> SDA-4374: Devtool will now depend on config

- src/app/config-handler.ts
- src/app/window-handler.ts
> Sda 4373: Reopen SDA automatically after save

- src/app/config-handler.ts
- src/app/local-menu-shortcuts.ts
- src/app/window-handler.ts
Backport of https://github.com/finos/SymphonyElectron/pull/1990
Backport of https://github.com/finos/SymphonyElectron/pull/1991
> SDA-4374-4373_23.11.x: Backports

- src/renderer/components/about-app.tsx
- Trigger close about-app event after updating the pod URL
> SDA-4378 (Rearrange close event)

- src/renderer/components/about-app.tsx
> SDA-4378 (Rearrange close event) 

- src/app/window-handler.ts
> SDA-4381 (Reverts SDA-4373 as killing c9 is enough)

- src/app/auto-launch-controller.ts
- If userDataPath fields is not present the config undefined will be registed
- Fix userDataPath validation
> SDA-4380 & SDA-4387  (Fix userDataPath validation)

- src/app/auto-launch-controller.ts
> SDA-4380 & SDA-4387 (Fix userDataPath validation)

- package-lock.json
- package.json
- src/renderer/components/call-notification.tsx
- Make the tooltip dynamic based on the text content overflow
> SDA-4365 (Make tooltip dynamic)

- src/renderer/styles/call-notification.less
Backport of https://github.com/finos/SymphonyElectron/pull/2010
> SDA-4350 (Fix spacing and style of tooltip)

- src/app/c9-shell-handler.ts
- src/app/window-handler.ts
Backport of https://github.com/finos/SymphonyElectron/pull/2012
> SDA-4386 (Properly terminate c9 shell on exiting the application)

- src/app/child-window-handler.ts
- Add a dedicated input listener for child windows
- This is required for `Windows` as there will be no menu attached for child windows
> SDA-4400 (Add a dedicated input listener for child window)

- src/app/window-handler.ts
Add fix to resolve conflict in between WebdriverIO and Electron
> SDA-4404: Resolve Framework Conflict Electron with WDIO

- src/renderer/styles/welcome.less
- Change welcome pod url input border-color
> SDA-4074 (Change input broder color)

- src/app/window-utils.ts
- `setFullScreen` was placed inside leave fullscreen
https://github.com/finos/SymphonyElectron/pull/2020
> SDA-4256 (Fix placement issue)

- src/app/window-handler.ts
- Apply hide fullscreen and minimize even if minimize on close setting is enabled
> SDA-4256 (Apply hide fullscreen if minimize on close enabled)

- src/app/main-api-handler.ts
- src/app/reports-handler.ts
- src/common/api-interface.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
- Add support for persisting client logs after reload
- Optimize writing client logs in chunks and in background
https://github.com/SymphonyOSF/SFE-Lite/pull/16090
> SDA-4077 (Add support for persisting client logs after reload)

- src/app/auto-update-handler.ts
https://github.com/SymphonyOSF/SFE-Lite/pull/16159
> SDA-4406 -(Auto-update silent download)

- src/locale/en-US.json
- src/renderer/components/about-app.tsx
- src/renderer/styles/about-app.less
Add a new UI to revamp the current behavior of About App. An additional Save button is added in order to save change before proceed to restart
> SDA-4369: PoC Revamp About App Edit

- src/app/window-handler.ts
- Move focus listener outside did-finish-load 
- Use window property instead of config for `AlwaysOnTop`
> SDA-4417 - Optimize focus event listener

- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- src/renderer/components/windows-title-bar.tsx
- Fix maximize and unmaximize button height
> SDA-4419 (Fix maximize and unmaximize button height)

- spec/childWindowHandle.spec.ts
- spec/log.spec.ts
- src/app/c9-pipe-handler.ts
- src/app/c9-shell-handler.ts
- src/common/c9-logger.ts
- src/common/loggerBase.ts
IV logs will now be saved as iv_<date>
SDA logs will now be saved as sda_<date>
> SDA-4408: Separate Logs of IV and SDA

- spec/__snapshots__/aboutApp.spec.ts.snap
- spec/aboutApp.spec.ts
- src/renderer/components/about-app.tsx
- src/renderer/styles/about-app.less
Re-vamp the about app again, new changes flow diagram will be sent on ticket
> SDA-4408: Rennovate about app

- spec/__snapshots__/aboutApp.spec.ts.snap
- src/renderer/components/about-app.tsx
Mirror: https://github.com/finos/SymphonyElectron/pull/2045
> SDA-4433: Clicking on the Close button in edit pod URL screen does not close the About

- src/app/window-utils.ts
This reverts commit 8422af2faa1ad13905685b72e2b14aa9276ff2af.
Mirror #2048
> Revert "SDA-4422 Bug - Workaroud for frameless transparent windows titlebar being displayed (#2041)"

- src/app/screen-snippet-handler.ts
- src/app/stores/window-store.ts
- Close will automatically shift focus back to main
- Upload will automatically shift focus back to main regardless to hidden or include SDA
> SDA-4427: Add fix to case of close and capture with sym hidden

- spec/__snapshots__/aboutApp.spec.ts.snap
- src/renderer/components/about-app.tsx
- src/renderer/styles/about-app.less
- FR: Text wont be broken and looks as large as before. ITs size will be shrunk and the symbol ontop of e wont be lost
- JP: Text of cancel wont be broken to a new line, they should be in the same line
- Add new fix new pod URL does not affect after it was changed
> SDA-4434_4436: Update Fr/Jp text and Update PodURL Change

- src/app/window-utils.ts
> SDA-4433 (Revert SDA-4418)

- package-lock.json
- package.json
> update c9-shell to 3.29.0-0.98.3.175

- src/app/screen-snippet-handler.ts
- src/app/stores/window-store.ts
Mirror: https://github.com/finos/SymphonyElectron/pull/2050
> SDA-4427_24.1: Add fix to case of close and capture with sym hidden

- spec/__snapshots__/aboutApp.spec.ts.snap
- src/renderer/components/about-app.tsx
- src/renderer/styles/about-app.less
Mirror: https://github.com/finos/SymphonyElectron/pull/2051
> SDA-4434_4436_24.1: Update Fr/Jp text and Update PodURL Change

- src/app/window-utils.ts
> SDA-4435 (Revert SDA-4418)

- spec/__snapshots__/aboutApp.spec.ts.snap
- spec/aboutApp.spec.ts
- src/renderer/components/about-app.tsx
Size of close button should not be smaller in French
> SDA-4440: Restore size for non line break words

- installer/win/install_instructions_win.md
> SDA-4412: Update Win Installer

- installer/win/install_instructions_win.md
Mirror: https://github.com/finos/SymphonyElectron/pull/2060
> SDA-4412_24.1: Update Win Installer

- spec/__snapshots__/aboutApp.spec.ts.snap
- spec/aboutApp.spec.ts
- src/renderer/components/about-app.tsx
backport of: https://github.com/finos/SymphonyElectron/pull/2063
> SDA-4443_4444: Adding A11Y to Close and Prevent enter while pod is disabled

- src/app/window-handler.ts
On closing sub windows, automatically shift focus back to RTE
> SDA-4441: Restore focus on main after closing sub Windows

- .run/Demo (Build & Run).run.xml
- package.json
- spec/config.spec.ts
- src/common/env.ts
- Update isDevEnv check using `app. isPackaged`
To update the value using command line flag `ELECTRON_FORCE_IS_PACKAGED=true`
or
`export export ELECTRON_FORCE_IS_PACKAGED=true`
`npm run dev`
> SDA-3833 (Update isDevEnv check)

- src/renderer/styles/notification-comp.less
- Set max width for header content
> SDA-3708 (Fix content overflowing in toast notification)

- spec/plistHandler.spec.ts
- src/app/config-handler.ts
- src/app/plist-handler.ts
- Backup and restore global config
> SDA-4479 (Backup and restore global config)

- installer/mac/postinstall.sh
- Remove escaping URL string
- Fetch isPodUrlEditable from `sym_settings.txt`
> SDA-4487 (Remove escaping url string)

- src/app/app-menu.ts
- Do not send the initial menu analytic event
> SDA-4414 (Remove sending initial analytic event)

- src/app/init.ts
- Fix the dev env issue by setting default values in .plist file
> [Dev] SDA-4496 (Fix dev env issue by setting default values in .plist file)

- src/app/context-menu-builder.ts
Clone of https://github.com/finos/SymphonyElectron/pull/2109
> SDA-4481_24.4: Add Fix to image cannot be copied

- src/app/window-handler.ts
- Force welcome screen in user config URL is not configured correctly
> SDA-4494 (Force welcome screen in user config url is not configured correctly) [bug]

- src/app/init.ts
- setUserDefault only for macOS
> SDA-4496 (setUserDefault only for macOS)

- spec/plistHandler.spec.ts
- src/app/config-handler.ts
- src/app/plist-handler.ts
- Add validation to support newly added global config fields 
- Set newly added global config field
> SDA-4507 (Add validation for copying old global config file)

- src/app/config-handler.ts
- Read from default after copying global config
> SDA-4507 (Read from default after copying global config)

- src/app/window-utils.ts
- Use the correct variable to clear interval
> SDA-4197 - Use correct variable to clear interval

- src/app/notifications/notification-helper.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/renderer/call-notification-helper.ts
- src/renderer/components/call-notification.tsx
- src/renderer/components/notification-comp.tsx
- src/renderer/notification.ts
- Apply Zoom for notification windows
https://github.com/finos/SymphonyElectron/assets/13243259/25e81fa5-181c-4a03-9919-2443b34a3fc4
https://github.com/finos/SymphonyElectron/assets/13243259/182f7c11-1dbc-484b-bbd2-9b81d79980d8
> SDA-4506 - Apply Zoom for notification window

- src/app/window-utils.ts
- Use the correct variable to clear interval
> SDA-4197 (Use correct variable to clear interval)

- package-lock.json
- src/app/auto-update-handler.ts
- src/app/main.ts
- Force auto update on SDA launch if the auto-update is already downloaded
> SDA-4489 (Force auto update)

- src/app/stores/window-store.ts
Mirror of https://github.com/finos/SymphonyElectron/pull/2125
> SDA-4528: Minimize Windows wont disappear on capture with SDA Hidden

- scripts/build-win64.bat
- Change the signing tool for .msi
> SDA-4552 (Change signing tool for .msi)

- scripts/build-win64.bat
> SDA-4552 (Changing sign tool)

- src/app/auto-update-handler.ts
- Invoke check for update & download before force install
Fixes - electron-uptdater we need to trigger `checkForUpdate` & `downloadUpdate` for the `quitAndInstall` to work
> SDA-4489 (Invoke check for update & download before force install)

- src/app/auto-update-handler.ts
- src/app/main.ts
Force update: Fix issue related to different env
> SDA-4489 (Fix issue related to different env)

- src/app/main-api-handler.ts
- src/app/window-utils.ts
- src/renderer/styles/call-notification.less
- src/renderer/styles/notification-comp.less
SDA-4553 - Apply client zoom for toast notifications
SDA-4555 - Hide scroll bar for toast notifications
> SDA-4553 (Apply client zoom for toast notifications)

- src/app/config-handler.ts
- Initialize new data if the user config is unable to parse
> SDA-4501 (Initialize new data if the user config is unable to parse)

- package-lock.json
- package.json
- Bump SDA and Electron version
> SDA-4561 (Bump SDA and Electron version)

- src/app/auto-update-handler.ts
- src/app/main.ts
- Implement force auto-update SDA on launch
- Detects any pending latest installer and applies the update
> SDA-4489 (Force auto update) [Feature]

- src/app/window-utils.ts
> SDA-4563 (Ignore changing zoom if focused window is notification window) [Bug]

- src/app/window-utils.ts
- Ignore changing zoom if the focused window is about Symphony
> SDA-4563 (Ignore changing zoom if focused window is about Symphony)

- src/app/window-utils.ts
> SDA-4563 (Ignore changing zoom if focused window is about Symphony) [Bug]

- src/app/main.ts
- Only load the developer tool extension in development environments.
> SDA-4544 (only load dev tool extension on dev env)

- installer/win/WixSharpInstaller/Symphony.cs
- Uninstall `nsis` installer registry entries
> SDA-4562 (Uninstall nsis installer registry entries)

- src/app/auto-update-handler.ts
- Use the correct URL to validate
- `windowHandler.url` will be undefined which is the root cause of the issue
> SDA-4489 (Use correct url to validate)

- build/installer.nsh
[SDA-4514](https://github.com/finos/SymphonyElectron/pull/2142)
Revert of this
> SDA-4514_revert: Revert NSIS migration

- src/app/auto-update-handler.ts
- Just use the version which already includes the build number
> SDA-4489 (Just use version) [bug]

- installer/win/WixSharpInstaller/Symphony.cs
- Managed conditions should always run
- Remove install dir filter
> SDA-4562 (Managed condition should always run)

- package-lock.json
- package.json
- src/app/window-handler.ts
> SDA-4587 - Bump electron version

- package-lock.json
- package.json
- src/app/window-handler.ts
> SDA-4587 - Upgrade electron version to 30.1.0

- installer/win/WixSharpInstaller/Symphony.cs
- Only execute custom action if allowed
> SDA-4562 - Only execute custom action if allowed

- installer/win/WixSharpInstaller/Symphony.cs
- Clean registry only for the admin user
> SDA-4562 (Clean registry only for admin user)

- src/app/protocol-handler.ts
- Use only the hostname from the redirect URL to navigate
> SDA-4593 - Use only host name from redirect url to navigate

- src/app/window-handler.ts
- src/renderer/styles/screen-sharing-indicator.less
- enable use of content size for screen sharing indicator window
> SDA-4530 - enable use content size for screen sharing indicator window

- package-lock.json
- package.json
- src/app/notifications/call-notification.ts
- src/renderer/notification-handler.ts
- src/renderer/notification.ts
- Add toast stacking and unstacking logic
- Optimize closing active notifications
https://github.com/user-attachments/assets/38ca3a5a-ae4a-4d13-8584-13c82d149428
> SDA-4614 - Add toast stacking and unstacking logic

- src/app/window-handler.ts
> SDA-4530 - Increase the indicator window height

- src/renderer/notification-handler.ts
- add logic to stack based on start corner
> SDA-4659 - add logic to stack based on start corner

- src/renderer/notification-handler.ts
- Stack notifications based on top and bottom
> SDA-4659 - stack based on corner top and bottom

- src/renderer/notification-theme.ts
> SDA-4664 - Add border for light theme

- src/app/notifications/call-notification.ts
- src/renderer/notification-handler.ts
- src/renderer/notification-theme.ts
- src/renderer/notification.ts
> SDA-4664, SDA-4660, SDA-4661 - Add border color light theme

- src/renderer/styles/notifications-animations.less
- src/renderer/styles/variables.less
- Add border color for mentions
> SDA-4664 - Add border color for mentions

- package-lock.json
- src/renderer/notification.ts
> SDA-4675 - Debounce hide notification

- src/common/utils.ts
- src/renderer/notification-handler.ts
- src/renderer/notification.ts
- src/renderer/ssf-api.ts
> SDA-4675 - Add sequential function queue for showing notification

- src/renderer/notification-handler.ts
- src/renderer/notification.ts
> SDA-4675 - Remove move top

- src/renderer/notification-handler.ts
Mirror #2211 
https://github.com/user-attachments/assets/6db49498-bb80-4d40-aefb-f9ea29b77fad
https://github.com/user-attachments/assets/cd2f09b8-d383-4fa0-b2bb-f82529302abf
> SDA-4689 - Fix condition for one notification

- src/renderer/notification.ts
> SDA-4705 - Move notification to the top to fix full screen issue

- package-lock.json
- package.json
- src/app/window-handler.ts
- src/renderer/notification.ts
- Bump electron version to 33.0.2
> SDA-4717 Bump electron version

- installer/mac/postinstall.sh
- spec/postinstall.spec.ts
- Add missing latestAutoUpdateChannelEnabled fields into the plist file
> SDA-4714 - Add missing latestAutoUpdateChannelEnabled into plist file

- src/app/config-handler.ts
> SDA-4714 - Add missing latestAutoUpdateChannelEnabled into user config

- src/app/child-window-handler.ts
- Increase the child window minimum size
> SDA-4682 - Increase child window minimum size

- src/app/child-window-handler.ts
- Set min width & height for popout window
- Force setting min width & height
> SDA-4763 - Force setting min width & height for popout window

- src/app/child-window-handler.ts
- Add additional px for minimum window size
> SDA-4763 - Add additional px for min window size

- package-lock.json
- package.json
> Bump version 25.2.0

- spec/config.spec.ts
- src/app/config-handler.ts
- src/app/init.ts
- src/app/plist-handler.ts
- src/common/config-interface.ts
- Fix config race condition conflicts between the app and config
> SDA-4757 - Fix config race condition

- src/app/c9-pipe-handler.ts
- src/app/c9-shell-handler.ts
- Prevent starting a new c9 shell if the application is terminated
> SDA-4751 - Prevent starting new c9 shell if application is terminated

- package.json
- src/app/stores/presence-status-store.ts
- src/app/window-utils.ts
- src/locale/en-US.json
- src/locale/en.json
- Fix the theme color and update the initial system tray icon
> SDA-4727 - Fix the theme color and update the initial system tray icon

- package-lock.json
- package.json
> Upgrade electron@34.0.0

- package-lock.json
- package.json
- scripts/build-linux.sh
- scripts/build-mac.sh
- scripts/build-win32.bat
- scripts/build-win64.bat
- spec/mainApiHandler.spec.ts
Backport of https://github.com/finos/SymphonyElectron/pull/2286
> SDA-4799 - Bump node-adapter & audit fix

- package-lock.json
- package.json
> SDA-4792 - Bump native tool versions

- package-lock.json
> SDA-4792 - Update package-lock.json

- src/app/screen-snippet-handler.ts
- src/app/window-handler.ts
> SDA-4771 - Fix screen snippet window visibility issue

- config/Symphony.config
- Change connectionTimeout to string
> SDA-4793 - Change connectionTimeout to string

- package-lock.json
- package.json
> SDA-4808 - Bump screen snippet version

- src/app/window-handler.ts
- src/app/window-utils.ts
- Change from `BrowserView` to `WebContentsView`
https://github.com/user-attachments/assets/e7beaab3-79cf-4e42-af93-2d46c731c741
> SDA-4655 - Change from browserView to WebContentsView

- package-lock.json
- package.json
> SDA-4807 - Downgrade winreg version to 1.2.4

- src/app/notifications/notification-helper.ts
- src/app/window-utils.ts
- src/common/api-interface.ts
- src/renderer/call-notification-helper.ts
- src/renderer/components/call-notification.tsx
- src/renderer/components/notification-comp.tsx
- src/renderer/notification.ts
> Revert "SDA-4506 - Apply Zoom for notification window (#2120)"

- package-lock.json
- package.json
- scripts/build-mac.sh
- scripts/build-win64.bat
> SDA-4832 - Electron version 35.0.0

- spec/appMenu.spec.ts
- src/app/app-menu.ts
- src/app/main-api-handler.ts
- src/app/window-actions.ts
- src/app/window-handler.ts
- src/common/utils.ts
- Fix the windows shortcut 
- Fix fullscreen & maximize state
> SDA-4844 - SDA-4843 - SDA-4842 - Fix windows shortcut & fix fullscreen & maximize state

- spec/appMenu.spec.ts
- spec/miniViewHandler.spec.ts
- src/app/app-menu.ts
- src/app/main-api-handler.ts
- src/app/mini-view-handler.ts
- src/app/window-actions.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
> SDA-4847 - SDA-4848 - Optimize mini view and fix mini state

- spec/callNotification.spec.ts
- src/renderer/components/call-notification.tsx
Adding fixes for these issues:
Show Unknown Avatar instead of TextAvatar
Avatar show the first letter, instead of first and last
Eliminate Dupplication for Unknown User
Missing symphony logo for Unknown User
> SDA-4732_25.3: Fixing 3 remaining issues

- src/renderer/components/call-notification.tsx
Mirror of: https://github.com/finos/SymphonyElectron/pull/2331
> SDA-4732_Main: Fixing 3 remaining issues

- spec/miniViewHandler.spec.ts
- src/app/mini-view-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
> SDA-4847 - add generic listener for enter-full-screen & async leave-full-screen

- src/app/screen-snippet-handler.ts
> SDA-4846 - Close any instance of screen snippet window on capture

- src/app/window-handler.ts
> SDA-4858 - Prevent keystroke Ctrl + Shift + M from propagating in Windows

- package.json
> SDA-4862 - Remove desktop field

- spec/helpers/files-helper.spec.ts
- src/app/helpers/file/files-base-helper.ts
- src/app/helpers/file/files-helper.ts
- src/app/helpers/file/files.ts
- src/app/interfaces/file-helper.interface.ts
- src/app/interfaces/reports-handlers.interface.ts
- src/app/reports-handler.ts
Adding logs to the bundle
If IV logs arent found within the last 30 minutes, the latest logs that has been modified will be included instead
> SDA-4415: Add IV Zeus log to logs bundle

- installer/mac/symphony-mac-packager-arm64.pkgproj
- package-lock.json
- package.json
- scripts/build-mac.sh
- scripts/macos_update_yml.js
- Generates separate x64 & arm64 builds
- Bump electron version to 35.1.4
> SDA-4867 - Bump electron version & support arm64 builds

- scripts/build-win64.bat
- Update the file name with arch info
> SDA-4867 - Update file name with arch

- src/app/display-media-request-handler.ts
- Apply a workaround for the new screen picker implementation
> SDA-4866 - Apply workaround for screen picker

- package-lock.json
- package.json
> SDA-4881 - electron version

- src/app/display-media-request-handler.ts
> SDA-4865 - Fix screen picker window focus issue

- package-lock.json
> SDA-4897 - Fix vulnerable path @babel

- src/app/auto-update-handler.ts
- src/app/config-handler.ts
- Use sdaInstallerMsiUrl for custom auto update URL
> SDA-4902 - Use sdaInstallerMsiUrl for custom auto update URL

- spec/helpers/files-helper.spec.ts
- src/app/helpers/file/files-base-helper.ts
- src/app/helpers/file/files-helper.ts
- src/app/reports-handler.ts
An error occurred if user has no IV Entitlement.
This PR targets to catch fs.readfilesync, first to check it existence. Then perform action
> SDA-4909: Adding log handling exception for IV

- package-lock.json
- package.json
- scripts/build-mac.sh
- scripts/build-win64.bat
- Bump electron version to 36.3.2
> SDA-4911 - Bump electron version to 36.3.2

- src/app/stores/presence-status-store.ts
- src/app/window-utils.ts
- Apply shouldUseDarkColorsForSystemIntegratedUI for the system tray
> SDA-4910 - Apply shouldUseDarkColorsForSystemIntegratedUI

- package-lock.json
- package.json
- spec/i18n.spec.ts
- src/app/window-utils.ts
- src/common/i18n-preload.ts
- src/common/i18n.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
- Implement plural formatting for i18n
> SDA-4915 - Implement plural formatting for i18n

- src/app/stores/presence-status-store.ts
- src/app/window-utils.ts
> SDA-4910 - Remove shouldUseDarkColors check

- src/app/stores/window-store.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- Use minimize instead of hide for Windows
> SDA-4924 - Use minimize instead of hide for Windows

- src/app/window-utils.ts
- Ignore resize when in fullscreen
> SDA-4923 - Ignore resize when in fullscreen

- src/app/window-utils.ts
> SDA-4924 - Handle resize on restore

- package-lock.json
> SDA-4925 - Bump vulnerable dependencies

- spec/appMenu.spec.ts
- src/app/app-menu.ts
Prevent malformed URL to be proceeded in Menu -> Support Link section
> SDA-4876: Prevent malformed URL to action further

- package-lock.json
- package.json
- Bump electron version to 35.2.2
> SDA-4896 - Bump electron version to 35.2.2

- src/app/auto-update-handler.ts
- src/app/registry-handler.ts
- src/app/window-handler.ts
> SDA-4880 & SDA-4926 - Fix registry failures 

- .github/workflows/ci.yml
- src/app/stores/window-store.ts
- src/app/window-actions.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- Minimize the window if any pop-out windows exist
> SDA-4710 & SDA-4940 Minimize the window if any pop-out windows exist

- src/app/main.ts
- src/app/presence-status-handler.ts
- src/app/protocol-handler.ts
- src/app/window-utils.ts
> SDA-4943 & SDA-4939 - Handle window hidden state on Windows

- src/app/presence-status-handler.ts
- src/app/window-utils.ts
- Set thumb bar buttons on click
> SDA-4939 - Set thumb bar buttons on click

- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- src/app/presence-status-handler.ts
- src/renderer/components/windows-title-bar.tsx
- Prevent double click on hamburger button
> SDA-4938 - Prevent double click on hamburger button

- src/app/notifications/call-notification.ts
- src/renderer/notification.ts
- src/renderer/react-window.html
Adjust edges to be in proper size regardless to system zoom settings
> SDA-4937: Fixing bleeding edges for windows 10

- src/renderer/components/notification-comp.tsx
- src/renderer/components/screen-sharing-indicator.tsx
- src/renderer/styles/call-notification.less
- src/renderer/styles/notification-comp.less
- src/renderer/styles/screen-sharing-indicator.less
Reverts finos/SymphonyElectron#2429
> Revert "SDA-4937 - Fix border issue for Windows"

- package-lock.json
- package.json
- src/app/window-handler.ts
- src/renderer/notification.ts
- src/renderer/react-window.html
Pump Electron and Revert temp fixes for bleeding edges
> SDA-4944: Pump Electron + Revert workaround for bleeding edges fix

- src/app/window-actions.ts
- src/app/window-handler.ts
- setSkipTaskbar to false on activate
- setSkipTaskbar to true only on hide
> SDA-4968 & SDA-4969 - setSkipTaskbar to false on activate

- package-lock.json
- package.json
- Bump electron version to 38.1.2
> SDA-4994 - Bump electron version to 38.2.0

- src/app/notifications/call-notification.ts
- src/common/api-interface.ts
- src/common/env.ts
- src/renderer/components/call-notification.tsx
- src/renderer/components/notification-comp.tsx
- src/renderer/notification.ts
- src/renderer/styles/call-notification.less
- src/renderer/styles/notification-comp.less
- Add specific notification style for macOS tahoe
> SDA-4997 - Add specific notification style for macOS tahoe
