- README.md
- demo/README.md
- package.json
simplify local development environment by including lib: cross-env that support setting env vars on windows and mac.  
now to run dev build just do: npm run dev (rather than before have specific cmd for windows and mac).
> simplify local dev env

- package.json
jest needs to apply babel transform on all required files, previously some required files in node_modules was not being transformed so jest would throw errors because the file couldn't be properly transformed.
> fix jest to transform all tested files

- js/preload/createProxy.js
- tests/apiTests/proxy-polyfill.js
- tests/apiTests/proxyAPI.test.js
tests failed on version of node > 6.4.0 because Proxy is supported natively and requires that setter return non-falsely value when successful.
> fix test failures for newer ver of node

- package.json
According to recently added documentation, `sandbox: true` creates a sandbox 'compatible' renderer process, but doesn't actually enable the sandbox. The command line argument I've added is also required.
See discussion here: https://github.com/electron/electron/pull/9054#discussion_r108695652
> Enable the Chromium sandbox

- demo/index.html
- js/mainApiMgr.js
- js/notify/notifyImpl.js
- js/preload/createProxy.js
- tests/apiTests/proxyAPI.test.js
ensures all event listeners are cleaned up in proxy when instance is destroyed.
> clean up event listeners in proxy

- js/notify/AnimationQueue.js
- js/notify/electron-notify.js
- js/notify/notifyImpl.js
- js/windowMgr.js
fix few things related to notifications:
- close existing notfs when main window is reloaded
- add emitter queueing mechanism so that events received prior to call addEventListener are still emitted.  due to multi-process arch of electron, it is possible to subscribe to events in JS but miss early notifications.
> fix event timing for events

- js/windowMgr.js
use 'closed' event rather than 'close' event to ensure knowing when child window gets fully closed.  parent calling close method will not emit 'close' event - only 'closed' event does get emitted.
> use correct event when browserWin finally closes

- js/main.js
only allow single instance of app to run at time.
note: this will be needed later when implementing protocol handler.
> only allow single instance of app

- package.json
upgrade to electron 1.6.8.
release notes: https://github.com/electron/electron/releases/tag/v1.6.8
https://github.com/electron/electron/pull/9314 fixes memory leak we reported: https://github.com/electron/electron/issues/9191
> upgrade to electron 1.6.8

- demo/index.html
- js/desktopCapturer/getSources.js
- js/preload/preloadMain.js
This code implements interface that allows getting list of media sources in sandbox renderer process. This code provides equivalent of desktopCapturer.getSources that works in a sandbox renderer. see: https://electron.atom.io/docs/api/desktop-capturer/.
> get media source interface

- tests/activityDetection.test.js
@KiranNiranjan this test is failing for me on mac, so skipping for now, please fix...
error i am seeing when running locally...
FAIL  tests/activityDetection.test.js
● Test suite failed to run
The module '/Users/lneir/IntelliJProjects/SymphonyElectron-OSS/node_modules/@paulcbetts/system-idle-time/build/Release/system_idle_time.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 53. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
at Object.Module._extensions..node (module.js:598:18)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require …
> skip failing test - must fix

- demo/index.html
- js/windowMgr.js
enforces min width of 300 and min height for 600 for main and pop-out windows as per bug noted in electron-52
> enforce min width and height for windows

- js/enums/api.js
- js/mainApiMgr.js
- js/preload/preloadMain.js
this removes checkProtocolAction from preload api  as it should not be needed anymore.  requires that corresponding PR in SFE-Cilent be merged as well: https://github.com/SymphonyOSF/SFE-Client-App/pull/5622
> simplify protocol handler api

- js/preload/preloadMain.js
- js/windowMgr.js
opening A tag link from browser (in different hostname) should be blocked as this causes electron page to navigate to new location.  But there is a bug in electron https://github.com/electron/electron/issues/8841 that is preventing main process from using 'will-navigate' event.  So in the mean-time using 'beforeunload' event in browser process to block.
Note:  A tag with href='_blank' is allowed and already handled by 'window-open' event; will cause link to be opened in default browser.
> fix opening A tag

- package.json
bump to version of electron that fixes crash issue we reported: https://github.com/electron/electron/issues/9387
https://github.com/electron/electron/releases
> bump electron to ver 1.6.11

- js/main.js
- js/menus/menuTemplate.js
Updated AutoLauncher path to make it work properly in mac osx
> Electron-26 (Auto Launch for Mac)

- js/main.js
for development environment mode - ignore singleton app mode.  for example, this allows dev env testing and running production at the same time.
> ignore single app instance for dev mode

- js/preload/preloadMain.js
- js/screenSnippet/ScreenSnippet.js
- package.json
- tests/ScreenSnippet.test.js
hides the resultResult method, otherwise this will get exposed to web client via preload api and would allow client to read any file.
> hide readResult method

- js/notify/electron-notify-preload.js
custom notifications were not working.  the addition of logs here broke because logs can't be used in renderer process.  we'll need to add some new functionality to get logs here, in the mean-time revert to using console.error.
> notifications are not showing

- package.json
- tests/activityDetection.test.js
when building activity detection for tests need to provide node version (e.g., v7.4.0) since we are building for jest env which is running in local version of node.
also re-organized build steps to ensure electron-rebuild is always run first.  this is needed since running tests will build a version that is incompatible with electron.
> fix activity detection tests and build process

- js/notify/electron-notify.js
- package.json
Removed [async](https://www.npmjs.com/package/async) dependency in electron-notify as it was pulling the whole of `lodash` which was huge.
Currently using [async.map](https://www.npmjs.com/package/async.map) & [async.mapseries](https://www.npmjs.com/package/async.mapseries) dependency which is very light.
| Type | Before | After |
| --- | --- | --- |
| `App size` | 123.8 MB | 121 MB |
| `asar node_modules size` | 7.1 MB | 1.5 MB  |
> Electron-104 - (Removed Async Dependency)

- package.json
Removed some unwanted internal dependencies of `electron-spellchecker`.
| Type | Before | After |
| --- | --- | --- |
| **asar** | 157 MB | 50.8 MB |
| **asar unpacked** | 159 MB | 52.8 MB  |
> Electron-111 (Optimised Application Size)

- installer/win/Symphony-x64.aip
**Description**
Fixes an issue where upon using the "Repair" option with the Symphony installer, the unselected config was getting wiped out and that resulted in an invalid JSON config file. (i.e. Global Symphony config).
**Solution**
Advanced Installer allows us to have a configuration to specify not to overwrite certain files during reinstallation. The trick is to restrict this to only the reinstall (repair) case. Without that condition, the specific set of files are left untouched during uninstallation as well.
Anyway, this PR should fix our problem.
@lneir @VikasShashidhar Please review.
> electron-145: fixes the issue with invalid json config upon repair

- js/downloadManager/index.js
Added a browser tooltip to display full filename in download manager. This mimics the default behaviour of the Chrome Download Manager.
@lneir @VishwasShashidhar Please review.
> Add tooltip to display full filename in download manager.

- js/windowMgr.js
**Problem**
When we try to open an external link from inside a pop out window, it opens the link inside electron creating a new window which isn't the expected behavior. Instead, an external link should always be opened in the default browser of the OS.
**Solution Approach**
On a pop-out (child window), we listen for the "new-window" event and prevent the default event from occurring and instead open the link in an external browser.
@VikasShashidhar Please review and merge.
CC: @lneir
> Electron 135: Pop out window -> url opens in external browser

- js/notify/electron-notify.js
**Fixes an error**: Object has been destroyed
Removed the unwanted closeAll function as notification position is updated when a display is added/removed and also it was throwing an error:
> Electron-181 (Error: Object has been destroyed)

- README.md
- js/main.js
Example usage: Symphony.app/Contents/MacOS/Symphony --multiInstance --userDataPath=/tmp/SymphonyElectron
This command will start a new instance of the app and set user data dir to /tmp/SymphonyElectron
This is needed in rtc integration testing in order to spin up multiple instances of the app and setting different user data dirs so they don't share login cookies etc
>  RTC-2648: Added arguments for allowing multi instance and custom data dir

- js/menus/menuTemplate.js
- js/windowMgr.js
[**Issue**](https://perzoinc.atlassian.net/browse/ELECTRON-205)
Currently, with the electron wrapper, we don't have an option to download files onto a path that we want to. All the files are downloaded to the default download directory of the underlying OS.
This issue addresses the above problem by supporting a user to set the downloads directory specifically for electron.
**Approach**
We would be able to set the downloads directory through a menu option which opens a dialog through which we can select a directory and electron saves the path onto the user config file under the attribute "downloadsDirectory".
In case we don't have permission to set some directory, electron throws an error and we use the default downloads directory.
In case the directory is deleted by the user, we create …
> Electron 205 - Allow user to set Downloads folder through Menu dropdown

- installer/mac/preinstall.sh
- installer/mac/symphony-mac-packager.pkgproj
Currently, on macOS, when a new version of electron is installed, we are facing javascript issues, so, we have a ticket [ELECTRON-219](https://perzoinc.atlassian.net/browse/ELECTRON-219) which would address this by removing (quitting the app first) an already installed app on macOS during the mac installation process.
- #### Problem with the code: Currently, there is no pre-install script
- #### Fix : Added a pre-install script which is part of the installer to quit & delete the already installed Symphony app.
N/A
N/A
N/A
N/A
> electron-219: added a pre-install script for macOS

- js/search/search.js
In order to increase the relevancy we should provide the tuples of the entered terms separated by whitespaces. If a quotation mark exists in the query it implies a phrase search, then we should not change the query. Other punctuation marks are not going to be removed from the query and they will be stripped out by the tokenizer in the C library.
> Search 501

- installer/mac/postinstall.sh
With installation on Mac via command line, the installer is not equipped to set default values (podUrl and other settings) currently. This PR addresses the problem [ELECTRON-219](https://perzoinc.atlassian.net/browse/ELECTRON-219)
In the post install script, we check if the podUrl and other values are not empty (case where the installation is done via command line), if they are, we set default values accordingly.
N/A
N/A
N/A
N/A
> electron-219: added logic to set default values in the postinstall script

- js/basicAuth/index.js
Fixed an issue when the basic auth is closed using the native button [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-253)
- #### Problem with the code: basic auth settings were not being cleared when the auth window was closed using the native close button
- #### Fix: added a method to clear the auth settings
> Electron-253 (Fixed an issue whit basic auth)

- js/downloadManager/index.js
- js/windowMgr.js
- tests/DownloadManager.test.js
Supports functionality to set a custom downloads folder in electron [electron-205](https://perzoinc.atlassian.net/browse/electron-205)
Although this was already done, there was an issue where in with a custom downloads folder, an existing file used to be overwritten unlike chrome which appends a number to the new filename in case the file already exists.
- #### Problem with the code: Electron's default download mechanism doesn't support the increment behaviour for a custom folder
- #### Fix : Wrote a custom logic to support the above functionality
N/A
N/A
N/A
N/A
> electron-205: fixed file overwrite issues when a custom download folder is set by the user

- js/main.js
Updated the code not to encode the URL and to just validate the protocol before creating the browser window
[JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-156)
- #### Problem with the code: URL was encoding context-specific delimiters 
- #### Fix: Removed the encoding part of the code
> Electron-156 (Updated Protocol Validation)

- js/preload/preloadMain.js
Implemented a method to reset badge count on window navigation/reload [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-262)
- #### Problem with the code: Badge count was not being reset to 0 when reloaded/navigated
- #### Fix: Added an event to reset badge count whenever the window is reloaded/navigated
> Electron-262 (Fixes Badge Count Issue)

- js/enums/api.js
- js/mainApiMgr.js
- js/preload/preloadMain.js
- js/screenSnippet/index.js
Added an event to terminate screen snippet process whenever the main window is reloaded/navigated [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-228)
Also updated the badge count feature so that there will be one reload event to handle everything.
- #### Problem with the code: Screen snippet was not being terminated when the app is reloaded as the context will be lost
- #### Fix: Added an event to terminate screen snippet whenever the main window is reloaded/navigated
> Electron-228 (Fixes Screen Snippet Reload Issue)

- package.json
Electron 1.7.12 adds a security fix for windows apps.
[JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-299)
> ELECTRON-299: upgrade to Electron 1.7.12

- js/bringToFront.js
- js/enums/api.js
- js/mainApiMgr.js
- js/preload/preloadMain.js
Added a new API for `bringToFront` feature [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-284)
- #### Problem with the code: The previous implementation required the latest version of the wrapper
- #### Fix: Changed the API so it doesn't conflict with the current version of the client
- [] Documentation
> Electron-284 (Changed the bring to front API)

- js/search/searchConfig.js
- js/search/utils/checkDiskSpace.js
- tests/Search.test.js
- tests/SearchUtils.test.js
Electron - Cannot enable swift search on Windows 7
[JIRA-ticket](https://perzoinc.atlassian.net/browse/SEARCH-605)
_Note: This is a temporary patch. If there are permission issue and the disk space is less than 300MB the swift search will be enabled._
- #### Problem with the code: FSUTIL utility requires administrative privileges
- #### Fix: This fix will be released as a part of [SEARCH-621](https://perzoinc.atlassian.net/browse/SEARCH-621)
@VikasShashidhar @serkanmulayim Please review. Thanks
[Fsutil](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753059(v=ws.10))
> SEARCH-605 (Electron - Cannot enable swift search on Windows 7)

- package.json
Upgrade to electron 1.8.2 which bundles chrome 59, node 8.x and fixes a number of bugs. More details are in the [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-305)
> ELECTRON-305: Upgrade to electron 1.8.2

- js/windowMgr.js
Currently, when we try to open the diagnostics link from Electron, it gets opened in a browser. This doesn't help in trying to collect information for the electron client. This PR provides a fix for the same where in a new pop up is opened instead of opening the diagnostics link in a new window. [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-274)
- #### Problem with the code: We have a condition to check if the disposition for opening a new pop up is "new-window" and only those cases are being considered to create a new pop up. For the diagnostics link which is a relative url, the disposition is a "foreground-tab" which is not whitelisted on electron's side.
- #### Fix: We whitelist "foreground-tab" in the list of allowed disposition cases for opening a new pop up window.
> ELECTRON-274: fix issue for diagnostics link

- js/notify/electron-notify.js
Currently, on Windows systems, we restrict the number of notifications to 5 regardless of how big the screen is. GS requested this to be changed to match the screen real estate. [ELECTRON-293](https://perzoinc.atlassian.net/browse/ELECTRON-293)
We calculate the screen size and based on that display the number of notifications.
- #### Problem with the code: Currently, we set the max number of notifications to 5
- #### Fix: Remove the restriction.
[electron-293 - spectron-tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1794046/electron-293.-.spectron-tests.pdf)
[electron-293 - unit-tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1794047/electron-293.-.unit-tests.pdf)
> ELECTRON-293: remove notification limit of 5 and match it with screen size

- installer/win/Symphony-x86.aip
On the windows 32 bit installer, any selections made during the installation was not being persisted to the configuration file. [ELECTRON-360](https://perzoinc.atlassian.net/browse/ELECTRON-360)
- #### Problem with the code: The text update component was missing in the 32 bit advanced installer configuration file
- #### Fix: Added the text update component
N/A
N/A
N/A
N/A
> Electron 360: fix configuration property issues on 32 bit windows installer

- js/notify/notifyImpl.js
Replace HTML tag `<>` from message content to prevent HTML injection [ELECTRON-338](https://perzoinc.atlassian.net/browse/ELECTRON-338)
- Messages with HTML content were not being filtered and was able to inject arbitrary HTML code into notifications
- Replacing HTML tags `<>` with the entity names
[Electron-338 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1803034/Electron-338.Spectron.pdf)
[Electron-338 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1803036/Electron-338.Unit.Tests.pdf)
> Electron-338 (Replace html tags from message content)

- demo/childWin.html
- demo/win.html
- js/windowMgr.js
- tests/spectron/popOuts.spectron.js
Removed restriction from opening a popup from another popup window [ELECTRON-325](https://perzoinc.atlassian.net/browse/ELECTRON-325)
- The previous implementation was restricted to popup a window only from the main window.
- Removed the restriction which validates and creates the pop-out window
[Test Results — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1796756/Test.Results.Spectron.pdf)
[Test Results — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1796758/Test.Results.Unit.Tests.pdf)
- N/A
- N/A
> Electron-325 (Removed restriction from opening a popup from another popup window)

- tests/SearchUtils.test.js
Fix FreeDiskSpace path when running the unit tests
- #### Problem with the code: Exe not present in the path.
- #### Fix: Changed the exe path
N/A
N/A
N/A
[Test Results — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1824440/Test.Results.Unit.Tests.pdf)
[Test Results — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1824441/Test.Results.Spectron.pdf)
@VikasShashidhar @VishwasShashidhar Please review. Thanks 😄
> ELECTRON-371 (Unit test fix)

- js/desktopCapturer/screen-picker.html
Fix issue with closing screen picker modal [ELECTRON-373](https://perzoinc.atlassian.net/browse/ELECTRON-373)
- Close was a child of `app-region: drag` content which was blocking the click event
- Adding `app-region: no-drag` fixes the issue
- [Issue](https://github.com/electron/electron/issues/1354)
[Electron-373 — Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1829514/Electron-373.Spectron.Tests.pdf)
[Electron-373 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1829518/Electron-373.Unit.Tests.pdf)
@VishwasShashidhar & @VikasShashidhar Please review. Thanks 😄
> Electron-373 (Fix issue with closing screen picker modal)

- package.json
Upgrade electron library dependency to 1.8.4 [ELECTRON-370](https://perzoinc.atlassian.net/browse/ELECTRON-370)
N/A
N/A
N/A
N/A
[ELECTRON-370 - Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1824954/ELECTRON-370.-.Unit.Tests.pdf)
[ELECTRON-370 - Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1825000/ELECTRON-370.-.Spectron.Tests.pdf)
> ELECTRON-370: upgrade electron dependency to 1.8.4

- js/menus/menuTemplate.js
- js/windowMgr.js
- tests/spectron/alwaysOnTop.spectron.js
- tests/spectron/full-screen.spectron.js
- tests/spectron/minimize-on-close.spectron.js
As part of [ELECTRON-337](https://perzoinc.atlassian.net/browse/ELECTRON-337), we've removed the "Toggle Dev Tools" menu item from the "View" menu as it is not required for end customers. If we still want to toggle the dev tools, we can do so using "Cmd+Alt+I" on macOS and "Ctrl+Shift+I" on Windows.
- Removed the toggle dev tools item from menu template
- Added a global shortcut in window manager mapping the callback against the above mentioned shortcuts
[ELECTRON-337 - unit-tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1858830/ELECTRON-337.-.unit-tests.pdf)
[ELECTRON-337 - spectron-tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1858835/ELECTRON-337.-.spectron-tests.pdf)
> ELECTRON-337: remove dev tools menu item

- js/windowMgr.js
A regression was caused in opening external urls. Due to the issue [ELECTRON-397](https://perzoinc.atlassian.net/browse/ELECTRON-397), external urls were being opened in a window rather than in the browser.
- #### Problem with the code: The method responsible for validating the URL was returning a string rather than a URL object
- #### Fix: Fixed the above problem to return a URL object rather than a string.
[ELECTRON-397 - unit tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1867666/ELECTRON-397.-.unit.tests.pdf)
[ELECTRON-397 - spectron tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1867667/ELECTRON-397.-.spectron.tests.pdf)
> ELECTRON-397: fix the regression on opening external urls

- js/log.js
- js/menus/menuTemplate.js
- js/utils/archiveHandler.js
- package.json
- tests/spectron/alwaysOnTop.spectron.js
- tests/spectron/full-screen.spectron.js
- tests/spectron/minimize-on-close.spectron.js
- tests/spectron/share-logs.spectron.js
Allows a user to share logs with support teams for troubleshooting [ELECTRON-380](https://perzoinc.atlassian.net/browse/ELECTRON-380)
A new menu item is added in the "Help" menu to share logs that are generated. Upon clicking the menu item, a zip file is created (for the available logs) and finder / explorer is opened highlighting the zip file which can then be shared. If there are no logs, an error dialog is shown accordingly.
[ELECTRON-380 - unit tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1875119/ELECTRON-380.-.unit.tests.pdf)
[ELECTRON-380 - spectron tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1875120/ELECTRON-380.-.spectron.tests.pdf)
> Electron 380: add share logs support

- js/aboutApp/index.js
- js/aboutApp/renderer.js
- js/basicAuth/index.js
- js/basicAuth/renderer.js
- js/crashReporter.js
- js/desktopCapturer/index.js
- js/desktopCapturer/renderer.js
- js/menus/menuTemplate.js
- js/preload/preloadMain.js
- js/utils/archiveHandler.js
- js/windowMgr.js
- package.json
Fixes crash dump not being generated on Windows OS [ELECTRON-401](https://perzoinc.atlassian.net/browse/ELECTRON-401)
- The crash reporter was initialized before `DOM` ready event
- Initializing the crash reporter after `DOM` ready event
- Initialized crash reporter for `about app window`, `desktop capture window`, `basic auth window` 
[Electron-401 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1883622/Electron-401.Spectron.pdf)
[Electron-401 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1883621/Electron-401.Unit.Tests.pdf)
@VishwasShashidhar , @VikasShashidhar Please review. Thanks 😄
> Electron-401 (fixes crash reporter)

- js/notify/electron-notify.js
- tests/spectron/notificationPosition.spectron.js
Reposition active notifications whenever the config is updated instead of closing the notifications [ELECTRON-417](https://perzoinc.atlassian.net/browse/ELECTRON-417)
- Notification was being closed whenever the notification configuration is updated
- Repositioning active notification whenever the config is updated 
[Electron-417 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1919482/Electron-417.Spectron.pdf)
[Electron-417 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1919484/Electron-417.Unit.Tests.pdf)
> Electron-417 (Reposition active notifications whenever the config is updated)

- js/notify/electron-notify-preload.js
- js/notify/electron-notify.js
Add a logic not to close the notifications on mouse hover [ELECTRON-414](https://perzoinc.atlassian.net/browse/ELECTRON-414)
- Non-sticky notification where being closed after a timeout of 5sec even on mouse hover
- Restart the timer on `mouseleave` event to close the notification
[Electron-414 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1907141/Electron-414.Spectron.pdf)
[Electron-414 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1907142/Electron-414.Unit.Tests.pdf)
@VikasShashidhar @VishwasShashidhar Please review. Thanks 😄
> Electron-414 (Add a logic not to close the notifications on mouse hover)

- js/utils/whitelistHandler.js
- package.json
- tests/utils/whitelist.test.js
(Remove third party dependency and write custom implementation) [ELECTRON-385](https://perzoinc.atlassian.net/browse/ELECTRON-385)
- Using a third party package `parseDomain` which had a strict `TLD` validation caused issues with the whitelist for the following TLD `.econet`
- Wrote a custom URL parser that returns any `TLDs`
branch | PR
Old changes | [link](https://github.com/symphonyoss/SymphonyElectron/pull/347)
[Electron-385 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1963421/Electron-385.Spectron.pdf)
[Electron-385 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1963418/Electron-385.Unit.Tests.pdf)
When solved, check the box and explain …
> Electron-385 (Remove third party dependency and write custom implementation)

- package.json
As part of keeping up with the latest version of Electron, this is to upgrade to Electron 2.0.0 stable which comes with Chromium 61 and Node 8.9.3 [ELECTRON-448](https://perzoinc.atlassian.net/browse/ELECTRON-448)
Update the electron dependency in package.json
N/A
N/A
N/A
[ELECTRON-448 - Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1966109/ELECTRON-448.-.Unit.Tests.pdf)
[ELECTRON-448 - Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1966110/ELECTRON-448.-.Spectron.Tests.pdf)
> ELECTRON-448: upgrade electron to 2.0.0 stable

- js/menus/menuTemplate.js
- tests/spectron/share-logs.spectron.js
To make it easier for users to contact the Symphony support team, we've added a new menu item under the "Help" menu in the Electron app [ELECTRON-451](https://perzoinc.atlassian.net/browse/ELECTRON-451)
Add a new menu item in the menuTemplate.js file.
N/A
N/A
N/A
[ELECTRON-451 - Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1966231/ELECTRON-451.-.Unit.Tests.pdf)
[ELECTRON-451 - Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1966243/ELECTRON-451.-.Spectron.Tests.pdf)
> Electron 451: add a new menu item "Symphony Help" under the help menu

- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
Added a URL validation dialog [ELECTRON-471](https://perzoinc.atlassian.net/browse/ELECTRON-471)
- Validation dialog was left out when in the installer redesign ticket
- Added a POD URL validation dialog that validates and displays an error message
branch | PR
Regression_PR | [link](https://github.com/symphonyoss/SymphonyElectron/pull/346)
@VishwasShashidhar @VikasShashidhar Please review. Thanks 😃
> Electron-471 (Add URL validation dialog for the Windows installer)

- js/windowMgr.js
When pop outs are closed, some of the event listeners were not being removed and that was causing memory to not be released on those event listeners. [ELECTRON-455](https://perzoinc.atlassian.net/browse/ELECTRON-455)
- #### Problem with the code: When an event listener is registered, it was not being removed when a pop out was closed.
- #### Fix: Added logic to remove event listeners upon closing pop outs.
N/A
N/A
N/A
[ELECTRON-455 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1979444/ELECTRON-455.Unit.Tests.pdf)
[ELECTRON-455 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1979445/ELECTRON-455.Spectron.Tests.pdf)
> Electron 455: fix memory leak with pop outs

- js/menus/menuTemplate.js
- js/screenSnippet/index.js
- js/windowMgr.js
An issue with `always on top` feature in Electron that brings pop-out to the top refer `Electron-209` and an issue with screen snippet where if always on top is enabled snipping tool goes to background refer `Electron-118`  [Electron470](https://perzoinc.atlassian.net/browse/ELECTRON-470)
- The main window is activated when the snippet is initialized from a pop-out window
- Added a check to activate the main window whenever required
[Electron-470 _ Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1986540/Electron-470._.Spectron.pdf)
[Electron-470 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1986541/Electron-470.Unit.Tests.pdf)
> Electron-470 (Add a new boolean check whether to activate main window)

- js/downloadManager/index.js
- js/main.js
- js/menus/menuTemplate.js
- js/windowMgr.js
When always on top is enabled and an error dialog is to be shown, the dialog goes in the background and the menu items get disabled on Windows. To fix this, we use a message box with the type "error" instead of an error box [ELECTRON-481](https://perzoinc.atlassian.net/browse/ELECTRON-481)
- #### Problem with the code: Using `showErrorBox` to show dialogs
- #### Fix: Using `showMessageBox` to show dialogs with type "error"
N/A
N/A
N/A
[ELECTRON-481 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1991003/ELECTRON-481.Unit.Tests.pdf)
[ELECTRON-481 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1991077/ELECTRON-481.Spectron.Tests.pdf)
> ELECTRON-481: fix the error dialogs with always on top use case

- js/mainApiMgr.js
- js/memoryMonitor.js
- js/menus/menuTemplate.js
- js/preload/preloadMain.js
Disable auto reload feature for r51 [ELECTRON-136](https://perzoinc.atlassian.net/browse/ELECTRON-136)
- Disable this feature for r51 as client changes need to be in before this feature is released
branch | PR
SFE-Client-App(r52) | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/9635)
SFE-Client-App(dev) | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/9634)
Symphony-Electron | [link](https://github.com/symphonyoss/SymphonyElectron/pull/360)
[Electron-136 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1992399/Electron-136.Spectron.pdf)
[Electron-136 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1992401/Electron-136.Unit.Tes …
> ELECTRON-136 (Disable auto reload feature for r51 release)

- js/windowMgr.js
Change method to use getFocusedWindow instead of fromWebContents [ELECTRON-491](https://perzoinc.atlassian.net/browse/ELECTRON-491)
- Calling a `fromWebContents` method with undefined `webContents` throwing an error
- Using `getFocusedWindow` for get the browser window access
- Cleaned up spaces
[Electron-491 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2004714/Electron-491.Spectron.pdf)
[Electron-491 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2004713/Electron-491.Unit.Tests.pdf)
> ELECTRON-491 (Fixes a Javascript error when pop-in a meeting)

- config/Symphony.config
- js/utils/whitelistHandler.js
- js/windowMgr.js
Some customers would like to ignore certificate transparency checks for specific domains. This PR implements the required functionality [ELECTRON-453](https://perzoinc.atlassian.net/browse/ELECTRON-453)
- #### Problem with the code: Currently, there's no way to ignore certificate transparency checks
- #### Fix: Add a new listener for ignoring certificate transparency checks on a browser window. Compare this with the whitelist configured and take necessary action.
N/A
N/A
N/A
[ELECTRON-453 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2021511/ELECTRON-453.Unit.Tests.pdf)
[ELECTRON-453 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2021512/ELECTRON-453.Spectron.Tests.pdf)
> ELECTRON-453: add functionality to ignore cert transparency checks

- package.json
Upgrade to the latest version of the electron framework [ELECTRON-513](https://perzoinc.atlassian.net/browse/ELECTRON-513)
N/A
N/A
N/A
N/A
[ELECTRON-513 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2021620/ELECTRON-513.Unit.Tests.pdf)
[ELECTRON-513 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2021622/ELECTRON-513.Spectron.Tests.pdf)
> ELECTRON-513: upgrade electron framework to 2.0.1

- js/windowMgr.js
Restore maximized and fullscreen application state on launch based on previous state [ELECTRON-350](https://perzoinc.atlassian.net/browse/ELECTRON-350)
- `Maximized` and `Fullscreen` state was not stored/handled
- Storing the `maximized` and `fullscreen` states in the user config and restoring on launch
[Electron-350 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2025358/Electron-350.Spectron.pdf)
[Electron-350 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2025403/Electron-350.Unit.Tests.pdf)
> Electron-350 (Store/Restore maximized and fullscreen application state on launch)

- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
As advance settings, dialog cancel button has no effect, so disable the cancel button [ELECTRON-525](https://perzoinc.atlassian.net/browse/ELECTRON-525)
- Advance settings in the installer is a custom dialog, so the cancel button has no effect
- Removed the cancel button from the advanced settings dialog
> ELECTRON-525 (Hide cancel button in the Windows installer advance settings)

- package.json
Due to a regression in the electron framework 2.0.1, notification windows were not being displayed properly. This PR fixes the issue by going with electron framework 2.0.2 which has fixed the transparent window issue. [ELECTRON-526](https://perzoinc.atlassian.net/browse/ELECTRON-526)
- #### Fix: Upgrade electron framework to 2.0.2
https://github.com/electron/electron/issues/12989
N/A
N/A
[ELECTRON-526 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2035281/ELECTRON-526.Unit.Tests.pdf)
[ELECTRON-526 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2035284/ELECTRON-526.Spectron.Tests.pdf)
> ELECTRON-526: fix notification transparent window issue

- js/search/search.js
- tests/spectron/getVersionInfo.spectron.js
Rework "deleteIndexFolders" in the Electron Preload Script
[SEARCH-764](https://perzoinc.atlassian.net/browse/SEARCH-764)
- #### Problem with the code: Files can be deleted when creating an instance of Search class and calling the method 'deleteIndexFolders' with the path as the parameter
- #### Fix: Now the method won't accept any parameter and the path is hardcoded
N/A
N/A
branch | PR
SymphonyElectron-Dev | [link](https://github.com/symphonyoss/SymphonyElectron/pull/378)
[Test Results — Unit Tests-R52.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2030203/Test.Results.Unit.Tests-R52.pdf)
[Test Results — Spectron-R52.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2030 …
> SEARCH-764-R52 (Rework "deleteIndexFolders" in the Electron Preload Script)

- js/desktopCapturer/getSource.js
- js/desktopCapturer/getSources.js
Prevents exposing Electron's EventEmitter in the preload script [ELECTRON-508](https://perzoinc.atlassian.net/browse/ELECTRON-508)
- Electron's EventEmitter `ipcRenderer` was returned to the web app, which is capable of sending arbitrary IPC messages and interacting directly with the Node.js runtime.
- Removed the unnecessary return statement 
[Electron-508 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2044044/Electron-508.Spectron.pdf)
[Electron-508 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2044045/Electron-508.Unit.Tests.pdf)
> ELECTRON-508 (Fix security issue with getSource and getSources)

- demo/index.html
- js/screenSnippet/index.js
A few sentences describing the overall goals of the pull request's commits. Describe the problem or feature in addition to a link to the [ELECTRON-508](https://perzoinc.atlassian.net/browse/ELECTRON-508)
- Throwing runtime expectation exposes application path
- Update error function to return simple object
[Electron-508 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2067263/Electron-508.Spectron.pdf)
[Electron-508 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2067265/Electron-508.Unit.Tests.pdf)
> ELECTRON-508 (Change error and warn functions to prevent from exposing application path)

- js/main.js
- js/windowMgr.js
By default, macOS dictates that when the "x" button on a window is clicked, the app is not supposed to be quit. This behaviour should apply to Symphony as well. This PR applies that logic. [ELECTRON-549](https://perzoinc.atlassian.net/browse/ELECTRON-549)
- #### Problem with the code: When the app quit event is triggered, we are not checking if the platform is macOS and quitting the app.
- #### Fix: Add checks to ensure that the app is not quit if the platform is macOS.
N/A
N/A
N/A
[ELECTRON-549 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2086814/ELECTRON-549.Unit.Tests.pdf)
[ELECTRON-549 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2086815/ELECTRON-549.Spectron.Tests.pdf)
> ELECTRON-549: support not quitting app on mac upon closing window

- js/menus/menuTemplate.js
Adds a menu item where users can enable or disable memory refresh functionality
[Electron-445 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2083683/Electron-445.Spectron.pdf)
[Electron-445 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2083687/Electron-445.Unit.Tests.pdf)
> ELECTRON-445 (Adds memory refresh menu item)

- js/search/searchUtils.js
`constructor` was removed as part of SEARCH-767 which caused the isEmpty check to fail.
[SEARCH-767](https://perzoinc.atlassian.net/browse/SEARCH-767)
- #### Problem with the code: Without the constructor, the isEmpty check to fail
- #### Fix: Adds constructor
N/A
N/A
N/A
[Test Results — Unit-Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2079509/Test.Results.Unit-Tests.pdf)
[Test Results — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2079505/Test.Results.Spectron.pdf)
> SEARCH-767 (Rework "path" in Electron Preload Script)

- js/main.js
- js/windowMgr.js
When we click on the app icon before the app is fully launched, we get a javascript error that the main window is not initialised. This PR adds an extra check to ensure the main window is initialised before showing it. [ELECTRON-549](https://perzoinc.atlassian.net/browse/ELECTRON-549)
- #### Problem with the code: There's no check to see if the mainWindow object is initalized
- #### Fix: Add a condition to check if the mainWindow object is initialized and then show the main window.
N/A
N/A
N/A
[ELECTRON-549 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2093391/ELECTRON-549.Unit.Tests.pdf)
[ELECTRON-549 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2093399/ELECTRON-549.Spectron.Tests.pdf)
> Electron 549: fix main window show javascript error issues

- js/main.js
Starting Chrome 57, chrome throttles background tabs (in Electron's case, background / minimised Windows). This PR disables throttling so Electron can perform better during the client app bootstrap. [ELECTRON-530](https://perzoinc.atlassian.net/browse/ELECTRON-530)
- #### Problem with the code: N/A
- #### Fix: Add the `--disable-background-timer-throttling` flag to chrome.
N/A
N/A
N/A
[ELECTRON-530 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2093208/ELECTRON-530.Unit.Tests.pdf)
[ELECTRON-530 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2093218/ELECTRON-530.Spectron.Tests.pdf)
> ELECTRON-530: add chrome flag to disable background timer throttling

- js/main.js
- js/windowMgr.js
On macOS, if the main window is closed using the “x” button, the main window is being destroyed and upon activation, we are seeing javascript errors because the main window is null. This PR fixes the issue [ELECTRON-563](https://perzoinc.atlassian.net/browse/ELECTRON-563)
- #### Problem with the code: In windowMgr, we are not checking for platform and simply destroying the main window regardless of the platform
- #### Fix: Add check to see if the platform is macOS and hide the main window rather than destroy it
N/A
N/A
N/A
[ELECTRON-563 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2097936/ELECTRON-563.Unit.Tests.pdf)
[ELECTRON-563 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2097937/ELECTRON-563.Spectron.Tests.pdf)
> ELECTRON-563: fix main window close issue on macOS

- js/desktopCapturer/getSource.js
- js/desktopCapturer/getSources.js
Added a missing check that returns applications only if the window is passed as `types` and `isAeroGlassEnabled`  [ELECTRON-568](https://perzoinc.atlassian.net/browse/ELECTRON-568)
- Always returns the applications if `isAeroGlassEnabled` is enabled no matter window is passed in the `types`
- Added a check that first validate for `types`
[ELECTRON-568 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2107978/ELECTRON-568.Spectron.pdf)
[ELECTRON-568 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2107979/ELECTRON-568.Unit.Tests.pdf)
> ELECTRON-568 (Enable applications tab only if it is passed in the types)

- js/screenSnippet/index.js
- js/translation/i18n.js
- package.json
Bump screen snippet version to 1.0.2 and add support for screen snippet localization [ELECTRON-535](https://perzoinc.atlassian.net/browse/ELECTRON-535)
- Bump screen snippet version to 1.0.2
- Add support for screen snippet localization by passing locale arg as the second arg
branch | PR
ScreenSnippet | [link](https://github.com/symphonyoss/ScreenSnippet/pull/4)
> ELECTRON-535 (Add support for screen snippet localization)

- js/spellChecker/index.js
Disable automatically detection of language for Windows OS [ELECTRON-573](https://perzoinc.atlassian.net/browse/ELECTRON-573)
- Automatic detection of language requires input HTML tags as it is currently not supported for RTE
- Disable automatic detection of language and set the default language to the system locale
branch | PR
SymphonyElectron(master) | [link](https://github.com/symphonyoss/SymphonyElectron/pull/411)
[ELECTRON-573 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2130594/ELECTRON-573.Spectron.pdf)
[ELECTRON-573 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2130595/ELECTRON-573.Unit.Tests.pdf)
> ELECTRON-573 (Disable automatic detection of language and set system locale)

- js/notify/settings/configure-notification-position.js
Resize of the notification configuration window was disabled and was causing issues when the window was moved [ELECTRON-538](https://perzoinc.atlassian.net/browse/ELECTRON-538)
Enabled resizing the window option which fixes the issue
[ELECTRON-538 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2148405/ELECTRON-538.Unit.Tests.pdf)
[Electron-538 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2148413/Electron-538.Spectron.pdf)
> ELECTRON-538 (Fix the scrollbar issue on Windows)

- config/Symphony.config
- js/enums/api.js
- js/mainApiMgr.js
- js/originCheck.js
- js/preload/preloadMain.js
- js/utils/whitelistHandler.js
Safety to protect from exposing `window.ssf` API to an unknown origin [ELECTRON-512](https://perzoinc.atlassian.net/browse/ELECTRON-512)
Emitting origin check event to the main process whenever the preload script is loaded
The main process receives the event published by the renderer process and validates the origin 
if the origin is valid the main process emits an event to the renderer process which then creates the API
N/A
[ELECTRON-512 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2174816/ELECTRON-512.Unit.Tests.pdf)
[Electron-512 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2174818/Electron-512.Spectron.pdf)
> ELECTRON-512 (Create API only if the location.origin matches with whitelist or pod URL)

- demo/index.html
- js/desktopCapturer/getSource.js
- js/desktopCapturer/getSources.js
- js/windowMgr.js
Disable screen share when media permissions are disabled [ELECTRON-492](https://perzoinc.atlassian.net/browse/ELECTRON-492)
Read `permision.media` from global config and disable showing the screen picker modal
[ELECTRON-492 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2191882/ELECTRON-492.Unit.Tests.pdf)
[Electron-492 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2191884/Electron-492.Spectron.pdf)
> ELECTRON-492 (Disable screen share when media permissions are disabled)

- js/main.js
This is needed for Mac OS as it brings pop-outs to the foreground (if it has been previously focused) instead of the main window [ELECTRON-378](https://perzoinc.atlassian.net/browse/ELECTRON-378)
Bring the main window to the foreground whenever the protocol actions are used
https://perzoinc.atlassian.net/wiki/spaces/DES/pages/143731901/Electron+Feature+-+Protocol+Handler
branch | PR
SFE-Client-App | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/10455)
[Electron-378 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2179421/Electron-378.Unit.Tests.pdf)
[Electron-378 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2179422/Electron-378.Spectron.pdf)
> ELECTRON-378 (Focus the correct module with protocol actions)

- js/windowMgr.js
- package.json
Enforce main window's `webPreference` to child window to prevent RCE  [ELECTRON-661](https://perzoinc.atlassian.net/browse/ELECTRON-661)
Also bump the Electron version to `2.0.6`
Reassign the child window's `webPreference` with the main window's `webPrefrence`  on `new-window` event
[ELECTRON-661 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2256184/ELECTRON-661.Unit.Tests.pdf)
[ELECTRON-661 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2256185/ELECTRON-661.Spectron.pdf)
> ELECTRON-661 (Security fix for pop-outs RCE)

- js/windowMgr.js
Hide menu instead of setting it to `null` [ELECTRON-670](https://perzoinc.atlassian.net/browse/ELECTRON-670)
Setting the menu to `null` will remove keyboard shortcuts, so hide it will solve the issue
branch | PR
SymphonyElectron | [link](https://github.com/symphonyoss/SymphonyElectron/pull/451)
[ELECTRON-670 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2270935/ELECTRON-670.Unit.Tests.pdf)
[ELECTRON-670 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2270936/ELECTRON-670.Spectron.pdf)
> ELECTRON-670 (Remove setting menu to null for pop-out)

- package.json
Electron "child_process" promisify issue
[SEARCH-905](https://perzoinc.atlassian.net/browse/SEARCH-905)
Electron "child_process" promisify issue was fixed in `electron 2.0.7` bumping the electron version
N/A
branch | PR
SwiftSearch | [link](https://github.com/symphonyoss/SwiftSearch/pull/2)
[Test Results — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2282537/Test.Results.Spectron.pdf)
[Test Results — Unit-Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2282538/Test.Results.Unit-Tests.pdf)
> SEARCH-905 (Electron "child_process" promisify issue)

- js/preload/preloadMain.js
- js/windowMgr.js
- js/windowsTitleBar/index.js
- locale/en-US.json
- locale/en.json
- locale/ja-JP.json
- locale/ja.json
Localize custom title bar buttons for Windows 10 [ELECTRON-665](https://perzoinc.atlassian.net/browse/ELECTRON-665)
Listen for locale changed event and update respectively
[ELECTRON-665 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2287089/ELECTRON-665.Unit.Tests.pdf)
[ELECTRON-665 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2287090/ELECTRON-665.Spectron.pdf)
> ELECTRON-665 (Localize custom title bar buttons for Windows 10)

- js/desktopCapturer/index.js
- tests/__mocks__/electron.js
- tests/config.test.js
- tests/jest_unit.json
Assign focused window to the screen picker to make it a modal window which disables user interaction with the content below [ELECTRON-651](https://perzoinc.atlassian.net/browse/ELECTRON-651)
- Updated unit test
Assigning focused window to the screen picker window fixes the issue
[ELECTRON-651 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2301670/Test.Results.Unit.Tests.pdf)
[ELECTRON-651 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2301668/ELECTRON-651.Spectron.pdf)
> ELECTRON-651 (Assign focused window to the screen picker) [Windows]

- package.json
Useing N-API version of ffi to support Node > v10.0.0
[SEARCH-915](https://perzoinc.atlassian.net/browse/SEARCH-915)
node-ffi is still not yet supported node version > v10.0.0 so using the N-API version of node-ffi
N/A
branch | PR
Swift-Search | [link](https://github.com/symphonyoss/SwiftSearch/releases/tag/v2.0.0-r53)
[Test Results — Unit-Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2305182/Test.Results.Unit-Tests.pdf)
> SEARCH-915 - Use N-API version of ffi to support Node > v10.0.0

- js/main.js
To support development use cases, we allow developers to set chrome flags via command line arguments [ELECTRON-655](https://perzoinc.atlassian.net/browse/ELECTRON-655)
**Note**: This is only applicable for a development environment.
Parse the command line arguments passed and set chrome flags accordingly
https://perzoinc.atlassian.net/wiki/spaces/DES/pages/414810426/Electron+Feature+-+Command+Line+Arguments
N/A
[ELECTRON-655 Unit Tests Results.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2306238/ELECTRON-655.Unit.Tests.Results.pdf)
> ELECTRON-655: implement dynamic chrome command line flags logic

- js/downloadManager/index.js
- js/windowMgr.js
- locale/en-US.json
- locale/en.json
- locale/ja-JP.json
- locale/ja.json
Currently, the actions "Open" & "Show in Folder" are not localised as part of the download manager. This commit adds japanese localisation for the above two actions.
Along with the above, we also add a better UX by using the string "Reveal in Finder" for macOS users.
[ELECTRON-669](https://perzoinc.atlassian.net/browse/ELECTRON-669)
An IPC event (`locale-changed`) is triggered upon language change. We add localisation for download manager actions by listening on this IPC event.
N/A
N/A
[ELECTRON-669 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2322799/ELECTRON-669.Unit.Tests.pdf)
> ELECTRON-669: add japanese localisation for download manager actions

- js/activityDetection/index.js
- js/windowMgr.js
Send activity only if network status is online [ELECTRON-694](https://perzoinc.atlassian.net/browse/ELECTRON-694)
Prevent from sending activity status to the web app when the network status is offline.
[ELECTRON-694 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2305103/ELECTRON-694.Unit.Tests.pdf)
[ELECTRON-694 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2305102/ELECTRON-694.Spectron.pdf)
> ELECTRON-694 (Send activity only if network status is online)

- js/notify/electron-notify-preload.js
- js/notify/electron-notify.js
Close tooltip is not displayed when hovering over on Close button
Describe the problem or feature in addition to a link to the [ELECTRON-695](https://perzoinc.atlassian.net/browse/ELECTRON-695)
- After fixing
branch | PR
ELECTRON-695-r53 | [link](https://github.com/symphonyoss/SymphonyElectron/pull/476)
> ELECTRON-695 (master)- Fixing hover close button on notification

- js/notify/electron-notify-preload.js
Change the color of notification text from white to black  [ELECTRON-729](https://perzoinc.atlassian.net/browse/ELECTRON-729)
- Before 
- After
> ELECTRON-729 - Accessibility color fix for customizing toast notifications

- js/windowMgr.js
- package.json
Electron framework v3.0.0-beta.8 fixes remote object count issue due to which we had to turn on sandboxing which lead to spell checker and right click actions not working. 
[ELECTRON-685](https://perzoinc.atlassian.net/browse/ELECTRON-685)
Upgrade the Electron version to beta8 and disable sandboxing.
N/A
N/A
[ELECTRON-685 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2334880/ELECTRON-685.Unit.Tests.pdf)
> ELECTRON-685: upgrade electron framework version to 3.0.0-beta.8

- js/menus/menuTemplate.js
"Relaunch Application" windows displays many times when selecting Native/ Custom
[ELECTRON-719](https://perzoinc.atlassian.net/browse/ELECTRON-719)
> ELECTRON-719 - Relaunch Application displays many times when selecting Native/ Custom

- js/menus/menuTemplate.js
- locale/en-US.json
- locale/en.json
- locale/ja-JP.json
- locale/ja.json
- Localise "Relaunch" and "Cancel" strings in the menu dialog
- Also point users to the Japanese support site if the user is using Japanese as the language
[ELECTRON-718](https://perzoinc.atlassian.net/browse/ELECTRON-718)
[ELECTRON-707](https://perzoinc.atlassian.net/browse/ELECTRON-707)
Add new strings to the messages file
N/A
N/A
[ELECTRON-718 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2339011/ELECTRON-718.Unit.Tests.pdf)
> ELECTRON-718: localise the relaunch and cancel strings,

- js/windowMgr.js
"Developer Tools" window flashes briefly before "Dev Tools disabled" pop-up displays [ELECTRON-676](https://perzoinc.atlassian.net/browse/ELECTRON-676)
Expected Result:
"Developer Tools" window should not flashes when displaying "Dev Tools disabled" pop-up
- Before
- After 
> ELECTRON-676 - Fixing Developer Tools window flashes before the popup

- js/notify/electron-notify.js
Electron - Always on top - Toast notification does not show on top (front) of the Electron if close toast notification before
> ELECTRON-710 - Fix Always on top: notification does not show on top

- js/cacheHandler/index.js
- js/main.js
- js/menus/menuTemplate.js
- locale/en-US.json
- locale/en.json
- locale/ja-JP.json
- locale/ja.json
A few customers have reported that the cache gets corrupted when the app is not exited cleanly. And, upon the next start, we get cache_read_failures.
[ELECTRON-788](https://perzoinc.atlassian.net/browse/ELECTRON-788)
This fix adds an extra check during startup and exit to check if the app was exited cleanly and clears the corrupted cache accordingly during startup.
Also adds a new menu item for users to manually clear cache and reload the app.
N/A
N/A
[ELECTRON-788 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2410701/ELECTRON-788.Unit.Tests.pdf)
> ELECTRON-788: add clear cache functionality

- js/downloadManager/index.js
- locale/en-US.json
- locale/en.json
- locale/ja-JP.json
- locale/ja.json
The messages "Downloaded" and "File not found" were not localised in Japanese, this PR adds localisation to those messages.
[ELECTRON-795](https://perzoinc.atlassian.net/browse/ELECTRON-795)
[ELECTRON-789](https://perzoinc.atlassian.net/browse/ELECTRON-789)
Add appropriate strings to the localisation files.
N/A
N/A
[ELECTRON-795 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2419273/ELECTRON-795.Unit.Tests.pdf)
> ELECTRON-795, ELECTRON-789: localise download manager messages

- js/menus/menuTemplate.js
- locale/en-US.json
- locale/en.json
- locale/ja-JP.json
- locale/ja.json
The menu item "Learn More" under the "Help" menu doesn't take a user to the appropriate page when Japanese is set as the user's language. This fixes the issue
[ELECTRON-790](https://perzoinc.atlassian.net/browse/ELECTRON-790)
Add appropriate links in the localisation files
N/A
N/A
[ELECTRON-790 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2422734/ELECTRON-790.Unit.Tests.pdf)
> ELECTRON-790: add japanese localisation support for "Learn more" menu item

- js/aboutApp/index.js
Window shows at top-left corner without header (About Symphony title/Minimize/Maximize/Close) after some steps 
[ELECTRON-756](https://perzoinc.atlassian.net/browse/ELECTRON-756)
- Before
- After
Setting window to fullscreen, when resizing is disabled, breaks fullscreen functionality [8166](https://github.com/electron/electron/issues/8166)
Fix full screen when resizable is set to true [9814](https://github.com/electron/electron/pull/9814)
> ELECTRON-756 - About Symphony: Window shows at top-left corner after fullscreen

- js/main.js
- js/mainApiMgr.js
- js/memoryMonitor.js
- js/preload/preloadMain.js
Change the active network request logic to use the one available in the electron framework instead of client API [ELECTRON-758](https://perzoinc.atlassian.net/browse/ELECTRON-758)
Using the electron's session object `WebRequest` to detect the active network request
branch | PR
SymphonyElectron - Related | [#494](https://github.com/symphonyoss/SymphonyElectron/pull/494)
[ELECTRON-758 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2423152/ELECTRON-758.Unit.Tests.pdf)
> ELECTRON-758 (Change network request implementation to use electron's API)

- js/main.js
- js/mainApiMgr.js
- js/memoryMonitor.js
- js/preload/preloadMain.js
- js/windowMgr.js
`process.getCPUUsage` method cannot be accessed if sandboxed [ELECTRON-870](https://perzoinc.atlassian.net/browse/ELECTRON-870)
Accessing the CPU usage in from the main process fixes the issue
branch | PR
Master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/521)
> (R53) ELECTRON-870 (Remove process.getCPUUsage from renderer process due to sandbox)

- js/main.js
- js/mainApiMgr.js
- js/memoryMonitor.js
- js/preload/preloadMain.js
- js/windowMgr.js
`process.getCPUUsage` method cannot be accessed if sandboxed [ELECTRON-870](https://perzoinc.atlassian.net/browse/ELECTRON-870)
Accessing the CPU usage in from the main process fixes the issue
branch | PR
R53 | [link](https://github.com/symphonyoss/SymphonyElectron/pull/520)
> ELECTRON-870 (Remove process.getCPUUsage from renderer process due to sandbox)

- js/aboutApp/index.js
- js/aboutApp/renderer.js
- js/main.js
- package.json
Change app version numbering to include client version number [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-874)
Version numbering Format **(clientVersion-SymphonyElectron) (Build Number) - 1.53-3.4.0 (16)**
Add a new field `clientVersion` in the package.json file.
> ELECTRON-874 (Change version numbering 1.53-3.4.0)

- js/windowMgr.js
- tests/utils/getRegistry.test.js
Show menu at 0,0 cord if the window is in full-screen mode [ELECTRON-736](https://perzoinc.atlassian.net/browse/ELECTRON-736)
Display popup menu at cord 0,0 if the window is in full-screen mode
[ELECTRON-736 Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2437616/ELECTRON-736.Test.Result.pdf)
> ELECTRON-736 (Show menu at 0,0 cord if the window is in full-screen mode)

- js/aboutApp/index.js
- js/basicAuth/index.js
- js/notify/settings/configure-notification-position.js
Set the menu to null for about, basic auth & configure notification windows [ELECTRON-720](https://perzoinc.atlassian.net/browse/ELECTRON-720)
Setting the menu to null will prevent from showing the menu on Windows
https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetmenumenu-linux-windows
[ELECTRON-720 Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2437721/ELECTRON-720.Test.Result.pdf)
> ELECTRON-720 (Set the menu to null for about, basic auth & configure notification windows)

- package.json
Fix and error in copy image context menu [ELECTRON-906](https://perzoinc.atlassian.net/browse/ELECTRON-906)
Use `request` module to fetch and convert images to dataUrl and write it to the clipboard
> ELECTRON-906 (Fix copy image context menu)

- package.json
Electron - Swift search - A JavaScript error displays when the user reloads the Electron while the file .lz4 is creating
[SEARCH-1059](https://perzoinc.atlassian.net/browse/SEARCH-1059)
Add try catch and this is anyways replaced by lz4 extraction.
N/A
branch | PR
Swift-Search | [PR](https://github.com/symphonyoss/SwiftSearch/pull/6)
Attach unit in PDF format against the above task lists for this branch
> SEARCH-1059 (Electron - Swift search - A JavaScript error displays when the user reloads the Electron while the file .lz4 is creating)

- config/titleBarStyles.css
- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
- js/windowMgr.js
- js/windowsTitleBar/contents.js
- js/windowsTitleBar/style.css
- package.json
Add support for customizing Windows title bar styles [ELECTRON-925](https://perzoinc.atlassian.net/browse/ELECTRON-925)
Provide access to the `titleBarStyles.css` file and can modify the styles which is then reflected on the Windows custom title bar styles
https://perzoinc.atlassian.net/wiki/spaces/DES/pages/320995509/Electron+Feature+-+Custom+Title+Bar
> ELECTRON-925 (Add support for customizing Windows title bar styles)

- js/windowMgr.js
Fix typo in a permissions message related to screen-sharing permissions [ELECTRON-825](https://perzoinc.atlassian.net/browse/ELECTRON-825)
Update the strings
N/A
N/A
[ELECTRON-825 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2641861/ELECTRON-825.Unit.Tests.pdf)
> ELECTRON-825: fix typo in screen-sharing permissions message

- js/config.js
- js/menus/menuTemplate.js
- js/windowMgr.js
[ELECTRON-899](https://perzoinc.atlassian.net/browse/ELECTRON-899): Add dev tools as a menu item to the "Troubleshooting" menu under "Help" so users can easily access the dev tools.
[ELECTRON-905](https://perzoinc.atlassian.net/browse/ELECTRON-899): Dynamically read the dev tools config (to enable / disable) to ensure important data is not missed while troubleshooting.
- Add menu item in menu template
- Read config file dynamically for dev tools config
N/A
N/A
[ELECTRON-899 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2641857/ELECTRON-899.Unit.Tests.pdf)
> ELECTRON-899: add dev tools to menu & ELECTRON-905: read dev tools config dynamically

- package.json
Change node-ffi base fork to symphonyoss
Bump swift-search version which now also uses symphonyoss.
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SwiftSearch/files/2671788/Symphony.Electron.Test.Result.pdf)
> Change node-ffi base fork to symphonyoss

- js/windowMgr.js
Toast notification does not show on top (front) of the Electron app after it is minimized and maximized again [ELECTRON-955](https://perzoinc.atlassian.net/browse/ELECTRON-955)
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2672985/Symphony.Electron.Test.Result.pdf)
> ELECTRON-955 - fixing toast notification does not show on top of the Electron after it is minimized and maximized again

- js/log.js
To gather data from multiple instances, sometimes, we would need to have different logs folder for different instances. 
We add support for setting custom logs folder via command line with this PR.
[ELECTRON-839](https://perzoinc.atlassian.net/browse/ELECTRON-839)
Read command line arguments and set the appropriate value as the log path
https://perzoinc.atlassian.net/wiki/spaces/DES/pages/414810426/Electron+Feature+-+Command+Line+Arguments
N/A
[ELECTRON-839 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2723311/ELECTRON-839.Unit.Tests.pdf)
> ELECTRON-839: add logic to set custom logs folder

- demo/index.html
- js/enums/api.js
- js/mainApiMgr.js
- js/preload/preloadMain.js
- js/screenSharingIndicator/index.js
- js/screenSharingIndicator/renderer.js
- js/screenSharingIndicator/screen-sharing-indicator.html
- js/screenSharingIndicator/showScreenSharingIndicator.js
- locale/en-US.json
- locale/en.json
- locale/fr-FR.json
- locale/fr.json
- locale/ja-JP.json
- locale/ja.json
Implement screensharing indicator banner similar to Chrome one.
(https://perzoinc.atlassian.net/browse/RTC-5104)
New JS API creates a frameless, transparent, draggable window.
`showScreenSharingIndicator({stream, displayId}, callback)`.
`stream` is [https://developer.mozilla.org/en-US/docs/Web/API/MediaStream](MediaStream). Banner deletes itself automatically when stream deactivates. `displayId` is a hint - which display to attach banner to. display_id is a part of [DesktopCapturerSource](https://electronjs.org/docs/api/structures/desktop-capturer-source#desktopcapturersource-object) returned by `getSource()`. `callback` is for errors and to escalate "Stop Sharing" button.
https://github.com/SymphonyOSF/SFE-RTC/pull/1488
> RTC-5104: screensharing indicator

- js/windowMgr.js
Change the window focusing logic for Windows to preserve the window snapped state [ELECTRON-826](https://perzoinc.atlassian.net/browse/ELECTRON-826)
Use the Focus method instead of the show method to preserve the window snapped state
> ELECTRON-826 (Change the focusing logic for Window)

- js/aboutApp/index.js
- js/basicAuth/index.js
- js/desktopCapturer/index.js
- js/moreInfo/index.js
- js/screenSharingIndicator/index.js
- js/windowMgr.js
Currently on Windows, when the app is killed, a crash event is emitted which sends the wrong signal to the user that the app actually crashed which isn't the case because the app was in fact killed. So, this PR adds an extra check to see if the app was killed and shows the crash dialog based on that.
[ELECTRON-816](https://perzoinc.atlassian.net/browse/ELECTRON-816)
Adds an extra check to see if the app was killed and shows the crash dialog based on that
N/A
N/A
[ELECTRON-816 Unit Test Results.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2745156/ELECTRON-816.Unit.Test.Results.pdf)
> ELECTRON-816: add checks for crash events when it is killed

- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
When sso checkbox was checked, the dialog was not being refreshed which resulted in the pod url text box not being updated. Now, we refresh the dialog when the SSO checkbox is checked or unchecked both.
[ELECTRON-989](https://perzoinc.atlassian.net/browse/ELECTRON-989)
Refresh the dialog when the SSO checkbox is checked or unchecked both.
N/A
N/A
[ELECTRON-989 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2749218/ELECTRON-989.Unit.Tests.Report.pdf)
> ELECTRON-989: fix sso checkbox refresh

- js/main.js
- js/mainApiMgr.js
- js/preload/preloadMain.js
- js/spellChecker/index.js
- js/windowMgr.js
Enables spellchecker for main window [link](https://perzoinc.atlassian.net/browse/ELECTRON-869)
Enable spellchecker only for the main window until the underline memory leak is fixed on electron
https://github.com/electron/electron/issues/15459
branch | PR
Electron | [Issue](https://github.com/electron/electron/issues/15459)
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2754871/Symphony.Electron.Test.Result.pdf)
> ELECTRON-869 (Enable spellchecker for main window)

- js/menus/menuTemplate.js
Hamburger Menu - Window: Close option does not work when triggering with shortcut (Ctrl+W). [ELECTRON-1003](https://perzoinc.atlassian.net/browse/ELECTRON-1003)
The keyboard shortcut stopped work in v4 any menu item with default role are not registered by default. 
To force registration the registerAccelerator was set to true.
More information in https://github.com/electron/electron/issues/16303
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2749714/Symphony.Electron.Test.Result.pdf)
> ELECTRON-1003: fix menuitems with roles default

- js/notify/electron-notify.js
Notification text overflows under user avatar [ELECTRON-903](https://perzoinc.atlassian.net/browse/ELECTRON-903)
When a message is sufficiently long, the text of the message overflows under the user's avatar and blocks a good chunk of the message.
- before 
- after 
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2756041/Symphony.Electron.Test.Result.pdf)
> ELECTRON-903: fixing the notification text overflowing under user avatar

- package.json
Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019
[SEARCH-1243](https://perzoinc.atlassian.net/browse/SEARCH-1243)
The cause of the crash is still unknown. But this PR is just to re-create the index
N/A
branch | PR
Swift-Search | [link](https://github.com/symphonyoss/SwiftSearch/pull/8)
> SEARCH-1243 (Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019)

- js/menus/menuTemplate.js
- js/windowMgr.js
App is not minimized upon "Configure Desktop Alert Position" modal when "Always on Top" = True.  [ELECTRON-956](https://perzoinc.atlassian.net/browse/ELECTRON-956)
[UnitTest.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2673191/UnitTest.pdf)
> ELECTRON-956 - removing the minimize and maximize from the configure desktop alert position

- package.json
Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019.
[SEARCH-1243](https://perzoinc.atlassian.net/browse/SEARCH-1243)
The fix is in the client app and this is just to clear the corrupted index.
N/A
SFE-Client-App | SEARCH-1243 | [PR #13335](https://github.com/SymphonyOSF/SFE-Client-App/pull/13335)
SwiftSearch | SEARCH-1243-new | [PR #9](https://github.com/symphonyoss/SwiftSearch/pull/9)
> SEARCH-1243 - Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019.

- package.json
Upgrading Electron to 4.0.2 resolves the following 2 issues:
-  Pop-outs crashing
- File dialog going to background. We use sheets in place of modals now.
[ELECTRON-992](https://perzoinc.atlassian.net/browse/ELECTRON-992)
[ELECTRON-978](https://perzoinc.atlassian.net/browse/ELECTRON-978)
Upgrade to electron version 4.0.2
N/A
N/A
[ELECTRON-992-978 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2786523/ELECTRON-992-978.Unit.Tests.Report.pdf)
> ELECTRON-992, ELECTRON-978: upgrade electron version to fix issues

- js/windowsTitleBar/index.js
Hamburger Menu - Copy/ Reload in menu context displays when right clicking on minimize, maximize, close button of the hamburger menu. [ELECTRON-769](https://perzoinc.atlassian.net/browse/ELECTRON-769)
- before
- after
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2788305/Symphony.Electron.Test.Result.pdf)
> ELECTRON-769: removing context menu when right click on minimize, maximize and close button

- js/notify/electron-notify.js
When a notification’s position is changed and the browser window is destroyed, SDA throws up an undesired error message which is not apt for users to see. 
This was because of a validity check missing to see if the browser window still exists.
[ELECTRON-962](https://perzoinc.atlassian.net/browse/ELECTRON-962)
Add an extra check to see if the browser window is not null
N/A
N/A
[ELECTRON-962 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2790434/ELECTRON-962.Unit.Tests.Report.pdf)
> ELECTRON-962: fix undesired javascript error

- js/aboutApp/index.js
- js/aboutApp/renderer.js
- locale/en-US.json
- locale/en.json
- locale/fr-FR.json
- locale/fr.json
- locale/ja-JP.json
- locale/ja.json
Add localisation (japanese, french) for about symphony window on Windows 
[ELECTRON-1030](https://perzoinc.atlassian.net/browse/ELECTRON-1030)
N/A
N/A
N/A
[ELECTRON-1030 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2790555/ELECTRON-1030.Unit.Tests.Report.pdf)
> ELECTRON-1030: add localisation for about symphony window on Windows

- spec/__mocks__/electron.ts
- spec/activityDetection.spec.ts
> typescript: activityDetection unit test

- js/windowMgr.js
- package.json
- Upgrade electron framework version to address security vulnerability with native window open and node integration [ELECTRON-1066](https://perzoinc.atlassian.net/browse/ELECTRON-1066)
- Disable background throttling on requests when creating a new window [ELECTRON-1067](https://perzoinc.atlassian.net/browse/ELECTRON-1067)
N/A
N/A
N/A
[ELECTRON-1066 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2854121/ELECTRON-1066.Unit.Tests.Report.pdf)
> ELECTRON-1066, 1067: upgrade electron version

- js/main.js
- package.json
Because of [ELECTRON-805](https://perzoinc.atlassian.net/browse/ELECTRON-805), we weren't creating all the required registry entries on Windows for handling custom protocol in SDA. This PR addresses that issue.
[ELECTRON-1070](https://perzoinc.atlassian.net/browse/ELECTRON-1070)
N/A
N/A
N/A
[ELECTRON-1070 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2859729/ELECTRON-1070.Unit.Tests.Report.pdf)
> ELECTRON-1070: let electron handle protocol registration

- js/preload/preloadMain.js
- package.json
Enable spellchecker to popup window [ELECTRON-1019](https://perzoinc.atlassian.net/browse/ELECTRON-1019)
N/A
Memory leak with use sandbox true and webFrame.setSpellCheckProvider [link](https://github.com/electron/electron/issues/15459)
Fix memory leak when using webFrame and spell checker (4-0-x) [link](https://github.com/electron/electron/pull/16772)
N/A
> ELECTRON-1019: Enable spellchecker for popup window

- js/windowMgr.js
Fix issue where we were opening new window for same pod url 
[ELECTRON-1050](https://perzoinc.atlassian.net/browse/ELECTRON-1050)
Check if the new window url is the same as the main window url and if they are, open it in a browser rather than in a new window
N/A
N/A
[ELECTRON-1050 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2924847/ELECTRON-1050.Unit.Tests.Report.pdf)
> ELECTRON-1050: fix issue where we were opening new window for same pod url

- package.json
This error is shown when is executed: 
> npm run start
bump @types/react to 16.8.3 version
[enzyme Compiler error: Generic type 'ReactElement<P, T>' requires between 1 and 2 type arguments](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33048)
> fixing Compiler error: Generic type ReactElement<P, T>

- js/config.js
- js/main.js
Fix first time config update logic [ELECTRON-1129](https://perzoinc.atlassian.net/browse/ELECTRON-1129)
- Fix issue in `Promise`
- Change logic to update user config only if the install type is `per user`
- Change the logic to set first time launch if config version less than the installer version
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/590)
> ELECTRON-1129 (Fix first time launch config update logic)

- spec/__snapshots__/aboutApp.spec.ts.snap
- spec/aboutApp.spec.ts
> about app unit test

- js/screenSnippet/index.js
Unable to sent screenshots captured from the snipping tool in Electron [ELECTRON-1131](https://perzoinc.atlassian.net/browse/ELECTRON-1131)
Change the image extension from jpg to png on Windows OS
- WIndows
branch | PR
SFE-Client-App | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/13962)
ELECTRON-3.x | [link](https://github.com/symphonyoss/SymphonyElectron/pull/595)
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2963235/Symphony.Electron.Test.Result.pdf)
> ELECTRON-1131: changing extension from jpeg to png on windows

- js/windowMgr.js
- package.json
Currently, due to security reasons, we don't open any url which is not the same as the main window url in a new window, instead, we open it in a new tab of the system default browser.
However, this impacts the email app as we'll need new window to be opened to compose an email. This commit fixes that issue by checking if we need to open a sub-domain of the pod url domain.
[ELECTRON-1138](https://perzoinc.atlassian.net/browse/ELECTRON-1138)
Checking if we need to open a sub-domain of the pod url domain.
N/A
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/602)
[ELECTRON-1138 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2982607/ELECTRON-1138.Unit.Tests.Report.pdf)
> ELECTRON-1138: support opening email composition in new window

- js/enums/api.js
- js/mainApiMgr.js
- js/networkError/contents.js
- js/networkError/index.js
- js/networkError/style.css
- js/preload/preloadMain.js
- js/windowMgr.js
- locale/en-US.json
- locale/en.json
- locale/fr-FR.json
- locale/fr.json
- locale/ja-JP.json
- locale/ja.json
- package.json
Display a UI screen for network related issue instead of the blank screen [ELECTRON-967](https://perzoinc.atlassian.net/browse/ELECTRON-967)
Subscribe for `did-fail-load` and `did-stop-loading` webContents events to display an error message along with retrying network endpoint by fetching pod URL using `electron-fetch` module
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/600)
> ELECTRON-967 (Handle network state and implement retry logic)

- spec/autoLaunchController.spec.ts
fixing autoLaunchController unit test
it was necessary mock the updateUserConfig on autoLaunchController.spec
> mocking updateUserConfig on autoLaunchController unit test

- js/enums/api.js
- js/mainApiMgr.js
- js/networkError/contents.js
- js/networkError/index.js
- js/windowMgr.js
- locale/en-US.json
- locale/en.json
- locale/fr-FR.json
- locale/fr.json
- locale/ja-JP.json
- locale/ja.json
- package.json
This changes the auto refresh logic to manual refresh where users can use the retry button to reload the client
[ELECTRON-967](https://perzoinc.atlassian.net/browse/ELECTRON-967)
Add a `Retry` button which on clicked loads the main window with the global config URL
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/637)
> ELECTRON-967 (Remove auto retry logic and add manual retry)

- js/aboutApp/index.js
- js/basicAuth/index.js
- js/desktopCapturer/index.js
- js/moreInfo/index.js
- js/notify/electron-notify.js
- js/notify/settings/configure-notification-position.js
- js/screenSharingIndicator/index.js
Add safety check in electron-notify to prevent javascript errors
[ELECTRON-1239](https://perzoinc.atlassian.net/browse/ELECTRON-1239)
Add a safety check to access the window instance
> ELECTRON-1239 (Add safety check in electron-notify to prevent javascript errors)

- config/titleBarStyles.css
- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- spec/appCacheHandler.spec.ts
- spec/appMenu.spec.ts
- src/app/app-cache-handler.ts
- src/app/child-window-handler.ts
- src/renderer/components/windows-title-bar.tsx
- src/renderer/styles/title-bar.less
Change title-bar from className to id as it is dependent on the SFE side
Related to - [ELECTRON-748](https://perzoinc.atlassian.net/browse/ELECTRON-748)
- Change the `title-bar` to id from className
- Fix linter issues
> Typescript (Change title-bar from className to id ) (ELECTRON-748)

- package.json
App crashes when opening the Message tab after closing the app while the batch index is starting (3.x)
[SEARCH-1496](https://perzoinc.atlassian.net/browse/SEARCH-1496)
When the app is force terminated while the data is being written to disk the file gets corrupted and when we are opening that file which led to the crash. So to prevent this we clear the folder before decompression. 
N/A
branch | PR
Swift-Search - `master` | [#17](https://github.com/symphonyoss/SwiftSearch/pull/17)
> SEARCH-1496 - Clear search_index folder before decompressing

- js/menus/menuTemplate.js
Remove registerAccelerator from menuItem options
[ELECTRON-988](https://perzoinc.atlassian.net/browse/ELECTRON-988)
Setting registerAccelerator `electron` seem to register some accelerators twice.
In Electron version `3.1.6` registerAccelerator defaults to true and hence all the shortcuts works as expected
branch | PR
ELECTRON-1003 | [link](https://github.com/symphonyoss/SymphonyElectron/pull/546)
> ELECTRON-988 (Remove registerAccelerator from menuItem options)

- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- spec/windowsTitleBar.spec.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
- src/renderer/components/windows-title-bar.tsx
Fix custom title bar's `maximized` and `restore` titles
[ELECTRON-771](https://perzoinc.atlassian.net/browse/ELECTRON-771)
Check the window state and update the button titles
New translation added
- FR - "Restore": "Restaurer"
- JP - "Restore": "戻す"
> ELECTRON-771 (Fix custom title bar button titles & localization)

- package.json
LZ4 not creating in custom user data path (was using cd on the drive)
[SEARCH-1466](https://perzoinc.atlassian.net/browse/SEARCH-1466)
Use the drive name to navigate to that drive before performing any task
branch | PR
Swift-Search | [#18](https://github.com/symphonyoss/SwiftSearch/pull/18)
Swift-Search | [#19](https://github.com/symphonyoss/SwiftSearch/pull/19)
SymphonyElectron - master | [#653](https://github.com/symphonyoss/SymphonyElectron/pull/653)
> SEARCH-1466 - Data not tracking in user custom path

- js/autoLaunch/index.js
- package.json
Remove old Symphony launch agent plist file 
[ELECTRON-1247](https://perzoinc.atlassian.net/browse/ELECTRON-1247)
Using the third party `auto-launch` module (used previously) to remove the plist file.
The new launch on startup API provided by Electron creates an entry @ login items
> ELECTRON-1247 (Remove old Symphony launch agent plist file)

- js/windowMgr.js
Fix checks for handling links & popouts
[ELECTRON-1265](https://perzoinc.atlassian.net/browse/ELECTRON-1265)
Only validate Domain Name (symphony.com) if the pop-out window URL is from the same Domain name as the main window
- Compare only domain name i.e `symphony.com`
- **FrameName** must be present
- **Disposition** must be either new-window or foreground-tab
This solution works in every possible scenario including other subdomains
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/662)
> ELECTRON-1265 (Fix checks for handling links & pop-outs)

- package.json
Bump Electron version to `3.1.11`
https://github.com/electron/electron/releases/tag/v3.1.11
> fix: Typescript (Bump electron version to 3.1.11)

- package.json
Include Index-Validator for verifying the index.
[SEARCH-1514](https://perzoinc.atlassian.net/browse/SEARCH-1514)
When we initialize the corrupted index it crashes the electron app. So in order to prevent unexpected crashes, we validate the index before initializing.  
branch | PR
SymphonyElectron `5.x` | [#670](https://github.com/symphonyoss/SymphonyElectron/pull/670)
SwiftSearch | [#22](https://github.com/symphonyoss/SwiftSearch/pull/22)
> feat: SEARCH-1514 - Include Index-Validator for verifying the index

- src/renderer/ssf-api.ts
Support Swift-Search from `1.55.2`
1. Swift-Search will be supported from 1.55.2
2. All the older build we will be deprecated
branch | PR
SymphonyElectron - `5.x` | [#675](https://github.com/symphonyoss/SymphonyElectron/pull/675)
> feat: SEARCH-1313 - Bump swift-search version from 3.0.0 to 1.55.2

- src/renderer/components/notification-comp.tsx
Add role alert to the notification container to make screenreader read it properly 
[ELECTRON-1297](https://perzoinc.atlassian.net/browse/ELECTRON-1297)
Add `role: 'alert'` to the notification container
> feat: ELECTRON-1297 (Add role alert to the notification container)

- src/app/window-handler.ts
Fix Japanese chars from overlapping with button 
[ELECTRON-1169](https://perzoinc.atlassian.net/browse/ELECTRON-1169)
Increase the size of the window from `592` to `620`
> fix: ELECTRON-1169 (Increase screen sharing indicator to support Japanese chars)

- src/common/i18n-preload.ts
- src/common/i18n.ts
- src/locale/fr-FR.json
- src/locale/fr.json
- src/renderer/components/download-manager.tsx
Update French locale for: 
- Menu Items
- Download Manager
[ELECTRON-1177](https://perzoinc.atlassian.net/browse/ELECTRON-1177)
[ELECTRON-1172](https://perzoinc.atlassian.net/browse/ELECTRON-1172)
| Contents  | Translations |
| ------------- | ------------- |
| Always on Top  | Garder Symphony au premier plan  |
| Auto Launch On Startup  | Lancement automatique au démarrage  |
| Bring All to Front  | Amener les fenêtres au premier plan |
| Bring to Front on Notifications | Afficher les notifications au premier plan |
| Learn More | En savoir plus sur Symphony |
| Hide Others | Cacher les autres applications |
| More Information | Informations détaillées |
| Redo | Répéter la dernière opération |
| Show crash dump in Finder  | Montrer dans l'application 'Finder' le rapport de l'arrêt …
> fix: ELECTRON-1177 (Update French translations for menu items)

- src/renderer/ssf-api.ts
Bump search API version to 1.55.3 to support from R55.3
N/A
N/A
> feat: Bump search API version to 1.55.3 to support from R55.3

- config/Symphony.config
- package.json
- src/app/chrome-flags.ts
- src/app/config-handler.ts
- src/app/window-handler.ts
Fix ATS for localhost and update TLS version to `1.2`
[ELECTRON-1264](https://perzoinc.atlassian.net/browse/ELECTRON-1264)
- Disable sending crash dumps to server
To prevent vulnerable in the adjacent network
ATS for the localhost has been updated with 
- NSTemporaryExceptionAllowsInsecureHTTPLoads - NO
- NSTemporaryExceptionMinimumTLSVersion - 1.2
```
<key>NSAppTransportSecurity</key>
<dict>
<key>NSExceptionDomains</key>
<dict>
<key>localhost</key>
<dict>
<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
<false />
<key>NSTemporaryExceptionMinimumTLSVersion</key>
<string>1.2</string>
</dict>
</dict>
<key>NSAllowsLocalNetworking</key> // note: can't be updated via electron-builder
<true />
<key>NSAllowsArbitraryLoads</key> // note: can't be updated via electron-builder
<true /> …
```
> fix: ELECTRON-1264 (Fix ATS for localhost and update TLS version to 1.2)

- src/locale/fr-FR.json
- src/locale/fr.json
Fix the main menu option "Minimize on Close" which did not have french translation
[ELECTRON-1310](https://perzoinc.atlassian.net/browse/ELECTRON-1310)
Add appropriate strings to the french translation files
N/A
> fix: ELECTRON-1310 L10N: Minimize on Close not localized in French

- package.json
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
- src/renderer/components/more-info.tsx
- src/renderer/ssf-api.ts
Display swift-search version details in the More Info
[SEARCH-1527](https://perzoinc.atlassian.net/browse/SEARCH-1527)
**Preview:** 
Sets the version info data in the `process.env` and displayed in the more-info window only if `Swift Search` is enabled.
branch | PR
Swift-Search | [#26](https://github.com/symphonyoss/SwiftSearch/pull/26)
> feat: SEARCH-1527 - Display swift-search version details in the More Info

- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
- package.json
Include `.node` bindings files to support proper signing of the files
[ELECTRON-1292](https://perzoinc.atlassian.net/browse/ELECTRON-1292)
Include `spellchecker.node` & `keyboard-layout-manager.node` in asarUnpack
https://github.com/brave/browser-laptop/issues/12534
Notes: Include node bindings files in packager
> feat: ELECTRON-1292 (Unpack node binding files)

- package.json
Check Index File Size Before Initializing Swift Search
[SEARCH-1562](https://perzoinc.atlassian.net/browse/SEARCH-1562)
- **Checking disk space is done every time before Swift-Search is initialized.**
- If low on disk space Swift-Search will be disabled
- Else Swift-Search will continue with next process
- **Next, If the LZ4 file exists I check the size of the file**
- If the file size exceeds, Swift-Search is disabled
- We look at the size of LZ4 file. Let's say it is X. Then we need to check if there is (300MB - X) disk space. If so we should continue
- Else Swift-Search will be disabled
- **Next, Validate the index**
- Set the size of the index to the response from the validator
- If the validation failed, initialize with fresh …
> feat: SEARCH-1562 - Check Index File Size Before Initializing Swift Search

- config/Symphony.config
- package.json
- spec/chromeFlags.spec.ts
- src/app/chrome-flags.ts
- src/app/config-handler.ts
- src/app/main.ts
- src/app/perf-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
Add support for disabling throttling and background rendering.
[ELECTRON-1243](https://perzoinc.atlassian.net/browse/ELECTRON-1243)
Add a flag `disableThrottling` in `Symphony.config` that would allow users to disable throttling.
> fix: ELECTRON-1243: fix chrome flags tests

- package.json
Set `useLegacyV2RuntimeActivationPolicy` to support Virtual Devices
[ELECTRON-1278](https://perzoinc.atlassian.net/browse/ELECTRON-1278)
Set `useLegacyV2RuntimeActivationPolicy` to support Virtual Devices
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/startup/startup-element
https://devblogs.microsoft.com/dotnet/in-process-side-by-side-part1/
branch | PR
ScreenSnippet | [link](https://github.com/symphonyoss/ScreenSnippet/pull/9)
> fix: ELECTRON-1278 (Bump up screen snippet version)

- src/app/window-actions.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
- src/renderer/desktop-capturer.ts
Add translations for permissions dialog
[ELECTRON-1227](https://perzoinc.atlassian.net/browse/ELECTRON-1227)
- French
- Japanese
> fix: ELECTRON-1227 (Add translations for permissions dialog)

- src/app/main.ts
- src/app/protocol-handler.ts
Protocol handler was not processing requests on Windows because of a bug in the code that made an incorrect check upon a protocol request. 
[ELECTRON-1345](https://perzoinc.atlassian.net/browse/ELECTRON-1345)
Add an app running check and process the protocol action accordingly
N/A
> fix: ELECTRON-1345: fix protocol handler action issues

- spec/downloadManager.spec.ts
- src/app/main.ts
- src/renderer/components/download-manager.tsx
We had the following problems with the download manager
- We used to get a pop-up dialog every time we download a file. This was a regression for not using `electron-dl`
- If the same file was downloaded twice, the download manager was not updating the filename count appropriately
[ELECTRON-1338](https://perzoinc.atlassian.net/browse/ELECTRON-1338)
- Use `electron-dl` that automatically downloads the file to the user's download folder on the local system
- Update count in react state
N/A
> fix: ELECTRON-1338: fix download manager issues

- config/titleBarStyles.css
- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- src/renderer/components/windows-title-bar.tsx
- src/renderer/styles/title-bar.less
Fix Custom title bar title margin issue
[ELECTRON-1371](https://perzoinc.atlassian.net/browse/ELECTRON-1371)
Change `title-bar-title` from className to id
> fix: ELECTRON-1371 (Fix Custom title bar title margin issue)

- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
- src/renderer/components/download-manager.tsx
Fix spacing issue in the download manager b/w the `unit (KB, MB)` & `downloaded` string.
[ELECTRON-1373](https://perzoinc.atlassian.net/browse/ELECTRON-1373)
Add a space b/w the strings and localise it.
N/A
> fix: ELECTRON-1373: fix spacing in download manager

- src/renderer/components/notification-comp.tsx
Fixes notification text & background color
[ELECTRON-1346](https://perzoinc.atlassian.net/browse/ELECTRON-1346)
[ELECTRON-1370](https://perzoinc.atlassian.net/browse/ELECTRON-1370)
Convert colors to `hex` which fixes the issue
> fix: ELECTRON-1346 & ELECTRON-1370 (Fix notification text & background color)

- package.json
Bump electron version to 3.1.12 to fix notification crash issue
Bump electron version to `3.1.12` that fixes https://github.com/electron/electron/issues/19081
> chore: ELECTRON-1362 (Bump electron version to 3.1.12 to fix notification crash issue)

- src/renderer/components/windows-title-bar.tsx
Update custom title bar's title only once
[ELECTRON-1369](https://perzoinc.atlassian.net/browse/ELECTRON-1369)
Set the title once the window is loaded and ignore other `document.title` updates
> fix: ELECTRON-1369 (Set custom title bar's title once)

- src/app/window-utils.ts
Fix localisation for file not found cases in download manager 
[ELECTRON-1381](https://perzoinc.atlassian.net/browse/JIRA-ticket)
Add missing `DOWNLOAD_MANAGER_NAMESPACE` for the file not found i18n.t calls.
> fix: ELECTRON-1381: fix localisation for file not found cases

- spec/__snapshots__/aboutApp.spec.ts.snap
- src/app/window-handler.ts
- src/renderer/components/about-app.tsx
Fix localisation for "Version" string in the "About Symphony" window.
[ELECTRON-1379](https://perzoinc.atlassian.net/browse/ELECTRON-1379)
Add version string through localisation in the about-app component.
> fix: ELECTRON-1379: fix localisation for "Version" string

- src/renderer/components/notification-settings.tsx
Fix typo in notification setting radio button text
[ELECTRON-1388](https://perzoinc.atlassian.net/browse/ELECTRON-1388)
Update text in the notification configure component
> fix: ELECTRON-1388: fix typo in notification setting radio button text

- src/app/app-menu.ts
Fix issue where toggle dev tools wasn't working as per the global config
[ELECTRON-1408](https://perzoinc.atlassian.net/browse/ELECTRON-1408)
Destructure the config object correctly to get the devToolsEnabled config value in app menu component
> fix: ELECTRON-1408: fix toggle dev tools menu item

- src/app/window-handler.ts
Update window construction options
[ELECTRON-1396](https://perzoinc.atlassian.net/browse/ELECTRON-1396)
[ELECTRON-1429](https://perzoinc.atlassian.net/browse/ELECTRON-1429)
- Update `alwaysOnTop` based on mainWindow's `alwaysOnTop` settings
- Set `fullscreanable` to false for screen sharing indicator window
> fix: ELECTRON-1396 & ELECTRON-1429 (Fix window constructor opts)

- spec/screenPicker.spec.ts
- src/renderer/components/screen-picker.tsx
Identify screens based on the name instead of `display_id` for Windows
[ELECTRON-1409](https://perzoinc.atlassian.net/browse/ELECTRON-1409)
- **Windows** Identify screens based on `source.name` using regex
- **Mac** Identify screens based on `source.display_id`
Open issue https://github.com/electron/electron/issues/15111
> fix: ELECTRON-1409 (Identify screens based on name instead of display_id for Windows)

- package.json
Index Version in the config file gets updated immediately before the lz4 file gets updated
[SEARCH-1621](https://perzoinc.atlassian.net/browse/SEARCH-1621)
When there is index version bump the version is updated on the config file on bootstrap which is causing to use the old index on a new library.
branch | PR
SwiftSearch | [#34](https://github.com/symphonyoss/SwiftSearch/pull/34)
> fix: SEARCH-1621 - Index Version in the config file gets updated immediately before lz4 file gets updated

- src/renderer/components/more-info.tsx
fix: typo (Search API version displays as N/A #703 )
> fix: typo (Search API version displays as N/A)

- src/app/window-handler.ts
When Minimize On Close option is not selected and if we try to close the app by clicking on x button, the app should be in the minimize position.
[ELECTRON-1445](https://perzoinc.atlassian.net/browse/ELECTRON-1445)
Update logic to customise close behaviour for macOS
> fix: ELECTRON-1445: fix minimise on close behaviour on macOS

- package.json
FreeDiskSpace check uses FREE instead of AVAILABLE
[SEARCH-1627](https://perzoinc.atlassian.net/browse/SEARCH-1627)
Using the free as a source will affect the disk space check. If the root system has allocated some amount of space that will be added to the free. So we need to use available in instead of free 
The calculation for available is `available = free - reserved filesystem blocks(for root)`
branch | PR
SwiftSearch | [#35](https://github.com/symphonyoss/SwiftSearch/pull/35)
> fix: SEARCH-1627 - FreeDiskSpace check uses FREE instead of AVAILABLE

- spec/windowsTitleBar.spec.ts
- src/renderer/components/windows-title-bar.tsx
Update custom title bar's title based on `document.title`
[ELECTRON-1464](https://perzoinc.atlassian.net/browse/ELECTRON-1464)
- User `MutationObserver` to observe the document title changes and update CTB's title
> fix: ELECTRON-1464 (Update custom title bar's title correctly)

- src/app/screen-snippet-handler.ts
Change the screen snippet image extension to `.png`
[ELECTRON-1459](https://perzoinc.atlassian.net/browse/ELECTRON-1459)
Rename the `temp` file extension to `.png`
> fix: ELECTRON-1459 (Update screen snippet image type to png from jpg)

- src/app/config-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- src/common/i18n.ts
Persist locale changes to the user config file
[ELECTRON-1465](https://perzoinc.atlassian.net/browse/ELECTRON-1465)
- Save the locale changes to the user config file
- Use the locale from the config file for the initial launch
> fix: ELECTRON-1465 (Persist locale changes to the user config file)

- package.json
Migrate to napi version of node-ffi
Change the `ffi` module to use the napi version as there is no subsequent release for `ffi`.
This bumps both `ffi` and `ref` modules.
branch | PR
SwiftSearch | [#39](https://github.com/symphonyoss/SwiftSearch/pull/39)
> fix: Migrate to napi version of node-ffi/ref

- src/app/app-menu.ts
- src/app/window-handler.ts
Currently, even if the dev tools is disabled in the Symphony config file, we show the menu item and display an error message. This change fixes the confusion of showing the error message and instead just doesn't bring up the dev tools if it is disabled in the configuration file
[ELECTRON-1478](https://perzoinc.atlassian.net/browse/ELECTRON-1478)
Remove the error message & hide menu item
N/A
> fix: ELECTRON-1478: remove dev tools menu item via configuration

- src/app/init.ts
Group multiple processes into a single taskbar icon
[SDA-1347](https://perzoinc.atlassian.net/browse/SDA-1347)
- Set `setAppUserModelId` to `com.symphony.electron-desktop` so Windows makes sure any processes created will be merged into single taskbar icon.
- https://docs.microsoft.com/en-us/windows/win32/shell/appids
- https://www.electron.build/configuration/configuration#Configuration-squirrelWindows
> fix: SDA-1347 (Group multiple processes into a single task bar icon)

- spec/childWindowHandle.spec.ts
- src/app/child-window-handler.ts
Currently, in the Symphony message list, we supporting any link (ftp) that is non http(s), this PR fixes that by supporting opening of just http(s) links.
[SDA-1526](https://perzoinc.atlassian.net/browse/SDA-1526)
Add filter to check the protocol of a url to verify if it is http(s)
N/A
> fix: SDA-1526: remove support for opening non http(s) links

- config/Symphony.config
- docs/features/pod-whitelisting.md
- src/app/chrome-flags.ts
- src/app/config-handler.ts
- src/app/window-handler.ts
Currently, any url passed via command line is not validated, and, SDA essentially acts as a browser. To counter this, we add a "podWhitelist" parameter in the config file that allows admins to configure what pod urls can be passed via command line. And, only those URLs will be supported to be loaded via command line.
[SDA-1525](https://perzoinc.atlassian.net/browse/SDA-1525)
Add configurable parameter to whitelist urls passed from command line.
N/A
> feat: SDA-1525: add support for pod whitelisting

- package.json
- src/app/child-window-handler.ts
Fix validation check
[SDA-1530](https://perzoinc.atlassian.net/browse/SDA-1530)
Replace `http` with `http:` as URL parser returns protocol with a colon
branch | PR
Spellchecker | [link](https://github.com/symphonyoss/electron-spellchecker/pull/9)
> fix: SDA-1530 (Fix url validation check)

- package.json
- src/common/logger.ts
- Currently, if we use custom logs path and a directory doesn't exist, logs are created in the default Electron path.
- This change fixes that by creating the custom logs directory (recursively) on the fly
- This change also fixes issue with clearing old log files. Now, we keep the log files for the last 5 days instead of 10 days
[SDA-1487](https://perzoinc.atlassian.net/browse/SDA-1487)
- Use nodeJS `mkdirSync` api recursively to create the custom logs folder if it doesn't exist.
N/A
> fix: SDA-1487: add support for creating custom log folders on the fly

- package.json
Some of our customers need all DLL files to be extracted within the installation directory rather than dynamically being done in the temp folder on Windows.
This change addresses the requirement. 
[SDA-1292](https://perzoinc.atlassian.net/browse/SDA-1292)
Use electron-builder configuration to extract all DLL files to the installation directory.
N/A
> feat: SDA-1292: unpack all .node files in asar

- package.json
This PR addresses issues with DLL files getting unpacked in temp directories on Windows.
[SDA-1557](https://perzoinc.atlassian.net/browse/SDA-1557)
As part of the build process, we unpack all the asar DLL files in the installation folder
branch | PR
3.8.x | [https://github.com/symphonyoss/SymphonyElectron/pull/794 ](3.8.x)
> feat: SDA-1557: unpack asar DLL files locally

- spec/childWindowHandle.spec.ts
- src/app/init.ts
- src/app/reports-handler.ts
- src/common/logger.ts
Some of the customers use roaming profiles mapped to network drives, this creates issues when trying to run SDA in different VMs.
This PR addresses the issue by moving app / user data and logs to the local profile
[SDA-1561](https://perzoinc.atlassian.net/browse/SDA-1561)
Move app / user data and logs to local profile from roaming profile
branch | PR
master | https://github.com/symphonyoss/SymphonyElectron/pull/795
> feat: SDA-1561: move app data to local profile

- src/renderer/preload-component.ts
Set document title for all the window
[SDA-1581](https://perzoinc.atlassian.net/browse/SDA-1581)
Set `document.title` for all the frameless window
branch | PR
3.8.x | [link](https://github.com/symphonyoss/SymphonyElectron/pull/802)
> fix: SDA-1581 (Set document title for all the window)

- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
Update acvanced installer
[SDA-1582](https://perzoinc.atlassian.net/browse/SDA-1582)
- Include missing `.node` files in AIP
> fix: SDA-1582 (Include missing .node files in AIP)

- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
https://perzoinc.atlassian.net/browse/sda-1498 L10N: "Press Esc to exit full screen" not localized
branch | PR
> SDA-1498 Update test for full screen for french & japanese

- package.json
Fix security vulnerability in a third-party module
[INFOSEC-392](https://perzoinc.atlassian.net/browse/INFOSEC-392)
Upgrade electron-dl's internal dependency `pupa` to `2.0.0` 
Read more: https://snyk.io/vuln/SNYK-JS-PUPA-174563%5D
> fix: INFOSEC-392 (Fix a security vulnerability with pupa an internal dependency of electron-dl)

- package.json
- src/app/init.ts
- src/app/window-utils.ts
Port changes from 3.8.x branch to master
[SDA-48](https://perzoinc.atlassian.net/browse/SDA-48)
- Port changes from 3.8.x branch to 6.0.0
- Enable full sandbox for all the `browseWindow`
- Upgrade electron version to `6.1.5`
> fix: SDA-48 (Port changes from 3.8.x & force sandbox for all BrowserWindow instances)

- src/app/window-handler.ts
User have zoom in the screen-picker so the buttons are not visible
https://perzoinc.atlassian.net/browse/sda-1608 RTC: Missing Cancel % Select Screen buttons when sharing screen (MacOS)
Disable zoom functionality for screen picker
> fix: Disable zoom of screen-picker

- src/app/app-menu.ts
For windows I fixed
- ZoomIn to "Ctrl +" (was Ctrl Shift +)
- Short cuts in menu
https://perzoinc.atlassian.net/browse/sda-1102 Zoom: Resizing content/fonts with Command (+) fails (Mac only)
> fix: Fix Ctrl +, plus shortcut visible in menu's

- src/app/screen-snippet-handler.ts
- src/renderer/ssf-api.ts
Add logic to close screen snippet tool
[SDA-1284](https://perzoinc.atlassian.net/browse/SDA-1284)
- Add logic close the screen snippet tool from the client app
- optimize the codebase
branch | PR
SFE-Client-App | [16362](https://github.com/SymphonyOSF/SFE-Client-App/pull/16362)
> fix: SDA-1284 (Add logic to close screen snippet tool)

- entitlements.mac.plist
- package.json
macOS Catalina requires that we add entitlements to enable camera & microphone. This PR addresses that concern.
[SDA-1668](https://perzoinc.atlassian.net/browse/SDA-1668)
- Add entitlements file
- Include the entitlements files for build with electron-builder.
N/A
> fix: SDA-1668: add entitlements for macOS catalina

- package.json
Screen snippet version is set to an old version
[SDA-1673](https://perzoinc.atlassian.net/browse/SDA-1673)
Bumping the version in package.json
branch | PR
> fix: SDA-1673 Bumping version number for screen snippet tool

- src/app/window-handler.ts
Fix a regression caused by this commit 4484d44528a16816b1e435148c35faf7f8e10394
[SDA-1704](https://perzoinc.atlassian.net/browse/SDA-1704)
- Remove the window `closable` property
branch | PR
SymphonyElectron | [#798](https://github.com/symphonyoss/SymphonyElectron/pull/798)
> fix: SDA-1704 (Make screen sharing indicator window closable)

- installer/win/Mana-x64.aip
- installer/win/Mana-x86.aip
Bumping the product code and upgrade code in the installers, to enable side-by-side installation of mana and 1.5
[SDA-1683](https://perzoinc.atlassian.net/browse/SDA-1683)
branch | PR
> fix: Changing the product id to allow co-existance with 1.5

- src/app/window-handler.ts
Make screen sharing indicator window focusable to fix the focus issue
[SDA-1666](https://perzoinc.atlassian.net/browse/SDA-1666)
- Set `focusable` to true for screen sharing indicator window
> fix: SDA-1666 (Make screen sharing indicator window focusable)

- spec/__snapshots__/windowsTitleBar.spec.ts.snap
- src/renderer/components/windows-title-bar.tsx
Disable context menu for action buttons in the custom title bar
[SDA-1395](https://perzoinc.atlassian.net/browse/SDA-1395)
- Prevent default for context menu action on buttons
> fix: SDA-1395 (Disable context menu for action buttons)

- src/renderer/components/screen-picker.tsx
Fix issues with source name case-sensitivity
As `Electron` updated the source name from `Entire screen` to `Entire Screen` which causes this regression
[SDA-1716](https://perzoinc.atlassian.net/browse/SDA-1716)
- Update the case of the source name before comprising
> fix: SDA-1716 (Fix issues with source name case-sensitivity)

- package.json
- src/app/window-handler.ts
Use display id to identify screen instead of display position
[SDA-1743](https://perzoinc.atlassian.net/browse/SDA-1743)
branch | PR
> fix: SDA-1743 Use display id to identify screen instead of display position

- src/renderer/styles/notification-comp.less
Adding text-overflow: ellipsis was not enough, so copied all the styles from "message", which was already working
[SDA-1501](https://perzoinc.atlassian.net/browse/SDA-1501)
branch | PR
> fix: SDA-1501 Using ellipsis for notification title overflow

- src/app/window-utils.ts
Load the complete pod URL instead of hostname
[SDA-1778](https://perzoinc.atlassian.net/browse/SDA-1778)
Load the complete config pod URL instead of just the hostname
branch | PR
SymphonyElectron | [link](https://github.com/symphonyoss/SymphonyElectron/pull/893)
> fix: SDA-1778 - Load the complete pod url instead of hostname

- src/locale/fr-FR.json
- src/locale/fr.json
Fix the restart dialog message for French translation.
[SDA-1847](https://perzoinc.atlassian.net/browse/SDA-1847)
Add translation to the French language files.
https://github.com/symphonyoss/SymphonyElectron/pull/884
> fix: SDA-1847: fix french translation for restart dialog message

- src/locale/fr-FR.json
- src/locale/fr.json
> fix: SDA-1847: fix French translations for GPU dialog

- src/app/config-handler.ts
Filter out empty strings in cloud-config 
[SDA-1866](https://perzoinc.atlassian.net/browse/SDA-1866)
- Filter out empty strings so the values will fall back to the user or global config files
branch | PR
SymphonyElectron | [6.1.x](https://github.com/symphonyoss/SymphonyElectron/pull/909)
> fix: SDA-1866 (Filter out empty strings in cloud config)

- src/app/app-menu.ts
Fix shortcut issue specific to macOS
[SDA-1857](https://perzoinc.atlassian.net/browse/SDA-1857)
- Manually assign the accelerator for `ZoomIn`
https://github.com/electron/electron/issues/15496
branch | PR
SymphonyElectron | [master](https://github.com/symphonyoss/SymphonyElectron/pull/913#issue-387255915)
> fix: SDA-1857 (Add accelerator for zoom in for MacOS)

- installer/mac/postinstall.sh
- src/app/app-menu.ts
- src/app/window-handler.ts
Add cloud-config installer changes for macOS & fix ZoomIn shortcut menu item
[SDA-1859](https://perzoinc.atlassian.net/browse/SDA-1859)
[SDA-1857](https://perzoinc.atlassian.net/browse/SDA-1857)
- Update macOS installer script to use `ENABLED/DISABLED` instead of boolean values
- Set the ZoomIn accelerator as ⌘+ and also register global shortcuts for both `⌘+ & ⌘=`
branch | PR
SymphonyElectron | [master](https://github.com/symphonyoss/SymphonyElectron/pull/917)
> fix: SDA-1859 & SDA-1857 (Add cloud config installer changes for MacOS & fix ZoomIn shortcut menu item)

- config/Symphony.config
- spec/chromeFlags.spec.ts
- src/app/chrome-flags.ts
- src/app/config-handler.ts
- src/app/perf-handler.ts
- src/app/window-handler.ts
Enabling `disableThrottling` makes the main window go blank when creating a child windows
[SDA-1880](https://perzoinc.atlassian.net/browse/SDA-1880)
[SDA-1882](https://perzoinc.atlassian.net/browse/SDA-1882)
https://github.com/electron/electron/issues/22551
- Disable background Throttling only when the cloud-config is `disableThrottling` field is "ENABLED"
- Fix log message to make the data and the fields clear
- Add unit test cases for `disableThrottling`
branch | PR
SymphonyElectron | [master](https://github.com/symphonyoss/SymphonyElectron/pull/925)
> fix: SDA-1880 & SDA-1882 (Fix background Throttling changes for cloud config)

- package.json
Upgrade electron to 6.1.9
[SDA-1893](https://perzoinc.atlassian.net/browse/SDA-1893)
> fix: SDA-1893: upgrade electron to 6.1.9

- package.json
- src/app/main.ts
Fixes blank pop-out issue in 8.x versions of Electron
[SDA-1877](https://perzoinc.atlassian.net/browse/SDA-1877)
- Set `allowRendererProcessReuse` to `true`. 
- Starting from Electron version `9` this will default to `true`
> fix: SDA-1877 (Fix blank pop-out issue in 8.x electron version)

- src/renderer/notification.ts
- src/renderer/preload-main.ts
Workaround to fix an issue with exiting fullscreen when in an active RTC session
[SDA-1268](https://perzoinc.atlassian.net/browse/SDA-1268)
- exit HTML fullscreen whenever the notifications are clicked
> fix: SDA-1268 (Workaround to exit fullscreen when notification is clicked)[RTC]

- src/app/main-api-handler.ts
> fix: SDA-1895 (Escape backslash characters for autoLaunchPath)

- package-lock.json
- package.json
Fix medium security vulnerability from `electron-dl` dependency by upgrading it.
[SDA-1922](https://perzoinc.atlassian.net/browse/SDA-1922)
Upgrade dependency
> fix: SDA-1922: upgrade electron-dl dependency to 3.0.0

- src/app/window-handler.ts
Unregister global shortcuts for client switch on window blur
[SDA-1945](https://perzoinc.atlassian.net/browse/SDA-1945)
Unregister global shortcuts on window blur and register them again once the window is focused.
N/A
> fix: SDA-1945: unregister global shortcuts for client switch on window blur

- gulpfile.js
Skip setting expiry if value is 0
[SDA-1942](https://perzoinc.atlassian.net/browse/JSDA-1942)
Add condition to check if expiry period supplied is lesser than 1 and skip setting expiry if that's the case.
N/A
> chore: SDA-1942: skip setting expiry if value is 0

- src/app/screen-snippet-handler.ts
Some customers have reported that ant-virus tools block snipping tool images saved in temp directory. So, we write it to user data directory in a temp folder inside that now.
[SDA-1948](https://perzoinc.atlassian.net/browse/SDA-1948)
We write snipping tool output image files to user data directory in a temp folder inside that now
N/A
> fix: SDA-1948: write snippet image to user data directory temp folder

- installer/win/Symphony-x64.aip
- installer/win/Symphony-x86.aip
Swift-Search module related .node files were not included in the AIP files
[SDA-1901](https://perzoinc.atlassian.net/browse/SDA-1901)
Include .node file to support Swift-Search (windows only).
N/A
> fix: SDA-1901 - Add swift-search related .node files

- installer/mac/preinstall.sh
- installer/mac/symphony-mac-packager.pkgproj
- On macOS, currently, when trying to install new version of SDA, we simply kill the app before asking user if they'd like to quit and proceed.
- This fixes the issue and provides a better user experience.
[SDA-1062](https://perzoinc.atlassian.net/browse/SDA-1062)
- Add `bundleIdentifier` as part of packages to check if `Symphony` is running.
- Remove the `killall Symphony` command from `preinstall` script.
N/A
> feat: SDA-1062: warn users before closing running app

- src/app/window-actions.ts
PermissionRequestHandler was capturing permission requests from SFE and resolving them without querying system. 
This PR keeps SDAs own permission overrides, but adds checking against systemPreferences to properly reject permission requests from SFE when user has disabled media access for SDA.
> fix: tweaked PermissionRequestHandler to resolve correctly on macOS

- src/app/child-window-handler.ts
- src/app/window-handler.ts
After simplified installer was implemented, we were still reading the origin from global config, with this fix, we'll change that by reading the main window url (in cases where we pass the url as a command line argument)
[SDA-2013](https://perzoinc.atlassian.net/browse/SDA-2013)
Change origin to main window url
N/A
> fix: SDA-2013: fix origin check for simplified installer

- package-lock.json
- src/app/window-handler.ts
- src/renderer/styles/welcome.less
Upon implementing welcome screen, displaying custom title bar broken on Windows because we were loading the url on the main window prior to handling events.
This PR fixes that issue.
[SDA-2016](https://perzoinc.atlassian.net/browse/SDA-2016)
- Move the main window load url to the end of the sequence after listening on events
- Also disable scrollbars on Windows for the welcome screen
N/A
> fix: SDA-2016: fix title bar issue

- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-2009 RTC: Screen sharing red border still showing after call ended
Before the fix this was the steps to reproduce
- start meeting
- share screen
- right click and close screen sharing indicator
- click leave meeting button
Red indicator frame stayed before
> fix: screen share frame stay

- installer/win/Symphony-x64.aip
- src/app/main.ts
- src/app/window-handler.ts
This PR fixes 2 issues:
- Shows welcome screen (setting pod url) on every new install
- Adds dialog back to Windows installer that allows users to close Symphony
[SDA-2056](https://perzoinc.atlassian.net/browse/SDA-2056)
[SDA-2019](https://perzoinc.atlassian.net/browse/SDA-2019)
- Show welcome screen based on first time launch
#972 #973
> fix: SDA-2056: welcome screen on every install

- src/renderer/components/windows-title-bar.tsx
- src/renderer/styles/title-bar.less
Fix a target CSS issue with SFE-Lite 
Fix title bar button issue in 9.x
[SDA-2080](https://perzoinc.atlassian.net/browse/SDA-2080)
- As class names get regenerated by `jss` in the production we need to target `jss` class names
- Add content align to centre to fix the SVG aliment issue In 9.x
> fix: SDA-2080 (Fix a target CSS issue with SFE-Lite & fix title bar button issue in 9.x)

- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/notification.ts
Remove non-serializable content
[SDA-2091](https://perzoinc.atlassian.net/browse/SDA-2091)
As of 9.x Sending, non-JS objects over IPC now throws an exception
> fix: SDA-2091 (Remove non-serializable content)

- src/renderer/notification.ts
prevent notifications from opening in a fullscreen state in MacOS
[SDA-2092](https://perzoinc.atlassian.net/browse/SDA-2092)
- set `fullscreenable: false` to prevent the notification from opening in a full-screen state
- set resizable to true only for Windows
> fix: SDA-2092 (prevent notifications from opening in fullscreen state in MacOS)

- package.json
[SDA-2022](https://perzoinc.atlassian.net/browse/SDA-2022)
branch | PR
> fix: SDA-2022 Don't save snippet when annotation is aborted

- src/app/window-handler.ts
On mac the previous code worked, but for windows the screen share indicator was pushed behind other applications. With this change both on mac and windows the screen share indicator is on top
https://perzoinc.atlassian.net/browse/sda-2115 Screen Sharing: SS indicator disappears when sharing 1st screen
> fix: sda-2115 on windows the screen-share-indicator goes to background

- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-2140 CLONE - SDA 9.0.0-392- RTC: Screen share indicator does not close after reloading/closing SDA
screen share indicator is not closeable so we have to destroy it
> fix: SDA-2140: Screen share indicator does not close after reloading/closing SDA

- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-2140 CLONE - SDA 9.0.0-392- RTC: Screen share indicator does not close after reloading/closing SDA
Forgot when screen share and than quitting sda
> fix: sda-2140 forgot when screen share and than quiting sda

- src/app/main.ts
Add logic to disable `NSAutomaticPeriodSubstitutionEnabled` which is causing DraftJS to crash on SFE.
[SDA-2215](https://perzoinc.atlassian.net/browse/SDA-2215)
- Use the Electron's `systemPreferences.setUserDefault` API to disable `NSAutomaticPeriodSubstitutionEnabled`
N/A
> fix: SDA-2215: macos preference override

- src/app/window-handler.ts
- src/app/window-utils.ts
Currently, if network connection is lost on SDA post the welcome screen implementation, the pod url we load is from the global config file, instead we should load the proper url.
[SDA-2151](https://perzoinc.atlassian.net/browse/SDA-2151)
- Pass the correct url to the appropriate methods from within `window-handler`
N/A
> fix: SDA-2151: fix network request url reload

- src/app/window-handler.ts
- src/app/window-utils.ts
Ensuring screen share indicator frame is turned off when switching client versions, both using hotkeys and menu option
[SDA-2197](https://perzoinc.atlassian.net/browse/SDA-2197)
Closing the screen share indicator when the mainwindow url change and when hotkeys are invoked
branch | PR
> fix: SDA-2179 Ensuring screen share indicator frame is turned off when switching client versions

- installer/mac/intro.html
All fonts in the installer should be sans-serif and the correct sizes
[SDA-2209](https://perzoinc.atlassian.net/browse/SDA-2209)
Moved the styling to apply to the whole html document and not just the first text block.
branch | PR
> fix: SDA-2209 Applied consistent font styling

- gulpfile.js
Currently, source root path is not correctly set when compiling ts files. This creates a problem while debugging as source maps are not mapped correctly with the corresponding ts files.
This PR fixes the issue.
Note: Debugging on VSCode with TS files was not possible prior to this fix.
Add correct source root path when compiling ts files
N/A
> fix: add gulp ts source root for building

- config/Symphony.config
- docs/features/config-file.md
- src/app/app-menu.ts
- src/app/child-window-handler.ts
- src/app/config-handler.ts
- src/app/window-handler.ts
- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
Add parameter to push the renderer logs inside the SDA-logs
**Main window**
```
13:01:37.233 › renderer main: symphonyanalytics : register
13:01:41.895 › renderer main: error in chat list, MessageList Error: Large room unqueued
13:01:41.896 › renderer main: error in chat list, MessageList Error: Large room unqueued
```
**Pop-out**
```
15:15:05.548 › renderer SDA devs - Chat Room: Cannot register renderer for custom-message-context-renderer: There is no renderer available under [object Object]
15:15:05.548 › renderer SDA devs - Chat Room: Cannot register renderer for message-from-me: There is no renderer available under [object Object]
```
> feat: add parameter to push the renderer logs inside the SDA-logs

- package.json
- src/app/window-handler.ts
- Bump typescript version to fix 3rd party lint issues
- Fixes the build failing issue 
branch | PR
SDA-2285 | [link](https://github.com/symphonyoss/SymphonyElectron/pull/1032)
> build: SDA-2285 (Bump typescript version to fix 3rd party lint issues)

- package.json
- src/app/window-handler.ts
Bump SDA version to `9.1.0`
9.0.1 shipping with a fix for memory refresh issue
https://github.com/symphonyoss/SymphonyElectron/pull/1032
> chore: Bump SDA version to 9.1.0

- spec/chromeFlags.spec.ts
- src/app/chrome-flags.ts
Adds a new flag to allow network service in chromium to run in the same process as the renderer
[SDA-2315](https://perzoinc.atlassian.net/browse/SDA-2315)
Add the below flag in `chrome-flags.ts`
```
'enable-features': 'NetworkService,NetworkServiceInProcess',
```
#1048 
#1049
> feat: SDA-2315: add chrome flag for network in process

- src/app/app-state-handler.ts
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/app-bridge.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
Exposes an API on the bridge to allow SFE to restart SDA on demand.
[SDA-2352](https://perzoinc.atlassian.net/browse/SDA-2352)
- Add a new API in the ssf api
- Expose that on the context bridge and post message as well
https://github.com/SymphonyOSF/SFE-Client-App/pull/17241
> feat: SDA-2352: add new api for restarting SDA

- package.json
Upgrade Electron to the latest 9.2.1 release to fix the RTC meeting failure issue.
Upgrade Electron to the latest 9.2.1 release
#1054
> fix: address RTC meeting failure

- scripts/jenkins-win64.bat
To ensure that each branch/fork of SDA has independent control of how it is built, we are migrating the build script from jenkins into a local script file. This is part of that process, and the jenkins-win64.bat added in this PR is just a straight copy of the build script currently in jenkins. Once in place, the current jenkins script will be amended with a check at the start, to see if jenkins-win64.bat exists, and if so run it. If not present, the old script will be run (to ensure older repos without jenkins-win64.bat  keeps working)
[SDA-2386](https://perzoinc.atlassian.net/browse/SDA-2386)
branch | PR
> feat: SDA-2386 Added build script to replace the one in jenkins

- installer/win/Symphony.cs
Using the built in Version property in Wix#, and populating if from the same version string (stored in environment variable SYMVER) as is currently used by Advanced Installer 
[SDA-2389](https://perzoinc.atlassian.net/browse/SDA-2389)
branch | PR
> feat: SDA-2389 Added version number to installer

- src/locale/en-US.json
- src/locale/en.json
- src/locale/fr-FR.json
- src/locale/fr.json
- src/locale/ja-JP.json
- src/locale/ja.json
https://perzoinc.atlassian.net/browse/sda-2261 SDA 9.0.0.452 - Localization - Sub -Menu - 'Enable Renderer Logs' is not localized
> fix: sda-2261 translate enable console logs

- src/common/api-interface.ts
- src/renderer/desktop-capturer.ts
- src/renderer/notification.ts
Filter out custom notification window from showing up in the screen share application tab
[SDA-2279](https://perzoinc.atlassian.net/browse/SDA-2279)
- Filter out all the window with name `Notification - Symphony`
notes: custom notifications will no longer be displayed in screen picker application tab
> fix: SDA-2279 (Filter out notification windows from desktop capturer)

- package.json
- src/app/stats.ts
This change removes capturing all system information to decrease startup time.
[SDA-2418](https://perzoinc.atlassian.net/browse/SDA-2418)
N/A
#1073 #1072 
notes: remove capturing extra system information to decrease startup time.
> fix: SDA-2418: remove capturing all stats

- crowdin.yml
[Crowdin](https://crowdin.com) is a cloud-based localization platform used to manage multilingual content. 
We will use Crowdin to manage the text that appears in the user interface of Symphony client apps. 
Epic [I18N-968](https://perzoinc.atlassian.net/browse/I18N-968) tracks tasks required to integrate the platform with our clients. (For details, see [Crowdin Sync Process](https://docs.google.com/document/d/1kp_j-l6psNEYcRZ0HmFC57y1yeZ0kMi3pA7kLcMg4AE).)
This PR adds a configuration file that describes which resources to manage: the files to be uploaded into Crowdin and the locations of the corresponding translations.
For details, see https://support.crowdin.com/cli-tool/.
✅ Tested with Crowdin CLI, source strings & translations are successfully uploaded.
- Fixes …
> feat: I18N-978: Add configuration file for Crowdin CLI

- installer/win/WixSharpInstaller/CloseDlg.cs
- installer/win/WixSharpInstaller/CloseDlg.designer.cs
- installer/win/WixSharpInstaller/Symphony.cs
Handle upgrading of Symphony properly, by setting product GUID and upgrade code appropriately, and handling closing down of the app if it is running when installing
[SDA-2395](https://perzoinc.atlassian.net/browse/SDA-2395)
For the close dialog, it is not possible to close the app when the user press "Close Symphony" button, but instead the stopping of the app happens just before it starts installing files.
N/A
notes: address use case of upgrading an existing version of SDA in the installer
> feat: SDA-2395 Upgrading existing Symphony

- installer/win/WixSharpInstaller/Symphony.cs
Auto launch symphony after installation complete
[SDA-2462](https://perzoinc.atlassian.net/browse/SDA-2462)
By giving the main exe file an Id when added, we can use an InstalledFileAction referring to that Id to launch it no matter where it was installed to.
notes: auto launch symphony after installation complete
> feat: SDA-2462 Auto launch symphony after installation complete

- src/app/config-handler.ts
- src/app/main.ts
- Currently, if a user config file is already present, and if any changes are made to any parameter in the global config file, they don't get reflected in the user config file. This can be a problem for IT administrators whose changes to the global config file don't reflect.
- This PR addresses that problem by copying over config values that do not affect user settings but helps IT admins.
[SDA-2421](https://perzoinc.atlassian.net/browse/SDA-2421)
- Copy the relevant global config values to user config on startup
- Also format the user config and cloud config files on write
N/A
notes: copy global config values to user config on startup
> fix: SDA-2421: copy config on startup

- package.json
If the user have swapped left/right mouse button in control panel, the snippet tool was behaving incorrectly.
[SDA-2476](https://perzoinc.atlassian.net/browse/SDA-2476)
This fix detects if that setting has been changed, and swaps left/right button as necessary when calling GetAsyncKeyState. Note that the use of WM_LBUTTONDOWN does not need to be modified, as that is handled automatically by windows - but GetAsyncKeyState is not (see the Remarks section of https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate)
notes: Handling user having swapped left/right mouse buttons
> fix: SDA-2476 Handling user having swapped left/right mouse buttons

- package.json
When running windows 7 and using the classic theme, the screen snippet gets offset by a small amount. 
[SDA-2171](https://perzoinc.atlassian.net/browse/SDA-2171)
I don't know what is causing it, but found that by adding a call to set the position of the window after it's been initialized seems to fix it without any adverse effects on other themes or OS versions.
notes: Fix for screen snippet offset on windows 7
> fix: SDA-2171 Fix for screen snippet offset on windows 7

- package.json
Backport of #1088 
notes: upgrade electron to 9.3.2
> fix: SDA-2524, SDA-2525: upgrade electron to 9.3.2

- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/WixSharpInstaller/WelcomeDlg.cs
The windows installer runs UI as 32 bit process even if installer is 32 bit, so the %PROGRAMFILES% resolves to  C:\Program Files(x86) instead of C:\Program Files.
[SDA-2516](https://perzoinc.atlassian.net/browse/SDA-2516)
Resolve %PROGRAMFILES% before UI, and pass it through a property instead of resolving it in the UI.
notes: Extract programs folder location into property
> fix: SDA-2516 Extract programs folder location into property

- installer/win/WixSharpInstaller/WelcomeDlg.cs
Paths should be on the form CompanyName\ProductName, so in our case Symphony\Symphony, but there is only one Symphony
[SDA-2516](https://perzoinc.atlassian.net/browse/SDA-2516)
Added a second Symphony for company name
notes: Added missing 'Symphony' to paths
> fix: SDA-2516 Added missing 'Symphony' to paths

- installer/win/WixSharpInstaller/CloseDlg.cs
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/WixSharpInstaller/WelcomeDlg.cs
The Back button was not working from the Install Dir screen. This was caused by the Close Symphony screen, which would skip past itself if Symphony is not running, giving the appearance that Back button did nothing
[SDA-2511](https://perzoinc.atlassian.net/browse/SDA-2511)
Change the flow of the dialogs, to make the Welcome screen go to the Close Symphony screen only when Symphony is running, and manually control the flow from the Close Symphony screen 
notes: Making back button work from InstallDir screen
> fix: SDA-2511 Making back button work from InstallDir screen

- installer/win/WixSharpInstaller/Symphony.cs
By default, wixsharp does not display a confirmation dialog on uninstall, like the previous installer did
[SDA-2526](https://perzoinc.atlassian.net/browse/SDA-2526)
Added a dialog box on uninstall, to let user confirm uninstall.
Notes: Display uninstall confirmation dialog
> fix: SDA-2526 Display uninstall confirmation dialog

- spec/appCacheHandler.spec.ts
- src/app/app-cache-handler.ts
As opposed to how it was done in #1091, we only delete a select set of directories now that are related to the cache.
[SDA-2559](https://perzoinc.atlassian.net/browse/SDA-2559)
Only delete a select set of directories related to the cache.
#1091 
Notes: Delete app cache on Install & Crash
> fix: SDA-2559: Delete app cache on Install

- src/app/window-handler.ts
Two mac users have pinged me and said/showed the screen share indicator is zoomed.
1) Always reset zoom at start of the screen-sharing indicator
2) onZoomIn for mac, disregard if it is the screen-sharing indicator
Note: Tried on windows, can not zoom in/out on the screen-share indicator. Only on mac
Notes: fix screen-share indicator zoomed in
> fix: screen-share indicator zoomed in

- src/app/window-handler.ts
Set `Context Isolation` to true by default in the window handler
[SDA-2170](https://perzoinc.atlassian.net/browse/SDA-2170)
- If there's no config value for context isolation, set it to true by default
Notes: set context isolation to true by default
> feat: SDA-2170: set context isolation to true by default

- installer/win/WixSharpInstaller/ProgressDialog.Designer.cs
In the flow as originally defined, the cancel button on the progress dialog, while technically working (at the end of install, if cancelled had been pressed the installation was rolled back), it made for a confusing user experience
[SDA-2593](https://perzoinc.atlassian.net/browse/SDA-2593)
Disabled the cancel button on the progress dialog
notes: Disabled cancel button in progress dialog
> fix: SDA-2593 Disabled cancel button in progress dialog

- scripts/build-linux.sh
- scripts/build-mac.sh
- scripts/build-win32.bat
- scripts/build-win64.bat
Add support to run `snyk monitor` in the build pipeline along with `snyk test` to support snapshot testing directly on Snyk.
[SDA-2451](https://perzoinc.atlassian.net/browse/SDA-2451)
Add `snyk monitor` command in the shell script (Mac, Linux) and batch script (Windows)
N/A
Notes: add support to run snyk monitor on build scripts
> chore: SDA-2451: add support to run snyk monitor on build scripts

- installer/win/WixSharpInstaller/Symphony.cs
The install path is incorrect when doing silent installation from commandline, and command line parameters to install for current user only does not work at all.
[SDA-2681](https://perzoinc.atlassian.net/browse/SDA-2681)
Before installation starts, check if we are doing quiet install or installing with GUI (if installing with GUI, the welcome screen will modify the ALLUSERS property)
notes: Ensuring correct paths and function for silent install
> fix: SDA-2681 Ensuring correct paths and function for silent install

- installer/win/WixSharpInstaller/Symphony.cs
- src/app/window-handler.ts
There's a crash while trying to uninstall the SDA on the 1st try.
Note: User can uninstall SDA successfully on the 2nd try.
[SDA-2651](https://perzoinc.atlassian.net/browse/SDA-2651)
When installing or uninstalling, we want Symphony to be closed down, but the standard way of sending a WM_CLOSE message will not work for us, as we have a "minimize on close" option, which stops the app from terminating on WM_CLOSE. So we instruct the installer to not send a Close message, but instead send the EndSession message, and we have a custom event handler in the SDA code which listens for this message, and ensures app termination when it is received.
branch | PR
Notes: FIxed uninstall shutdown
> fix: SDA-2651 Using EndSession message to terminate SDA on uninstall

- .vscode/launch.json
- package.json
- src/app/config-handler.ts
- src/app/main.ts
- src/app/version-handler.ts
- src/app/window-handler.ts
- Move the logic of deleting app cache on install to before the app being initialized
- Add logic to force restart app on first install to avoid network issues
[SDA-2694](https://perzoinc.atlassian.net/browse/SDA-2694)
- Delete app cache before app is initialized to avoid blank screen issues
N/A
Notes: fix blank screen issues occurred by app cache deletion
> fix: SDA-2694: fix blank screen issues occurred by app cache deletion

- src/app/main.ts
Remove the logic of deleting app cache on first install
[SDA-2731](https://perzoinc.atlassian.net/browse/SDA-2731)
N/A
#1129 
Notes: remove logic of deleting app cache on first install
> fix: SDA-2731: remove logic of deleting app cache on first install

- src/renderer/styles/snipping-tool.less
This PR fixes the bug on Windows with scroll bars both on window and image for annotate tool. No bug ticket was created since it was found during production, tested by @NavyaGopalakrishna.
Notes: Fix double scroll bars
> fix: SDA-2533 Fixed double scroll bars on windows

- installer/win/install_instructions_win.md
- scripts/jenkins-win64.bat
We want installation instructions in markdown, and to generate a pdf file from that on every build
[SDA-2650](https://perzoinc.atlassian.net/browse/SDA-2650)
Using markdown-pdf npm module
branch | PR
Notes: Added install instructions
> feat: SDA-2650 Generate PDF with installation instruction

- src/app/window-handler.ts
- src/app/window-utils.ts
This PR makes devTools enabled or not for renderer processes dependent on environment.
Notes: engineering
> fix: Make devTools enabled dependent on if dev environment

- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/WixSharpInstaller/WelcomeDialog.cs
- installer/win/install_instructions_win.md
Support for APPDIR param was missing
[SDA-2745](https://perzoinc.atlassian.net/browse/SDA-2745)
Added support for APPDIR params
branch | PR
Notes: Added support for APPDIR params
> fix: SDA-2745 Added support for APPDIR parameter

- spec/mainApiHandler.spec.ts
- src/app/main-api-handler.ts
- src/app/notifications/electron-notification.ts
- src/app/notifications/notification-helper.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
The feature that adds support for inline reply for notifications
[SDA-2614](https://perzoinc.atlassian.net/browse/SDA-2614)
[SDA-2615](https://perzoinc.atlassian.net/browse/SDA-2615)
[SDA-2618](https://perzoinc.atlassian.net/browse/SDA-2618)
- Use Electron notification to display a notification
- Create a helper to choose between custom/native notification
- Bump SDA API version from `2.0.0` to `3.0.0`
- Remove remote module usage
branch | PR
SFE-Lite | [link](https://github.com/SymphonyOSF/SFE-Lite/pull/4993)
Notes: Add support for native electron notifications
> feat: SDA-2614 (Implement native electron notifications)

- scripts/jenkins-win64.bat
Old installer should be prefixed "Legacy", and the new installer should no longer have prefix "Experimental"
[SDA-2764](https://perzoinc.atlassian.net/browse/SDA-2764)
Changed the output names in the build script
branch | PR
Notes: Made new installer the default one
> fix: SDA-2764 Changed names of installer files

- config/Symphony.config
- docs/features/network-error.md
- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
For special cases like corp, load the actual pod url if login is not complete yet in case of network connection issues.
[SDA-2762](https://perzoinc.atlassian.net/browse/SDA-2762)
- Add a new flag called `isLoggedIn` in window handler
- Initialize the above flag to false by default
- Once SFE is loaded, set the flag to true
- If the above flag is false, load the original pod url
- If the flag is true, load the current window url
N/A
Notes: load correct page on network issues
> fix: SDA-2762: load correct page on network issues

- src/renderer/notification.ts
- Fix notification inline reply focus issue with Windows
- Write a custom logic to move all the notifications with inline reply open to the top
Notes: Fix notification inline reply focus issue with Windows
> fix: SDA-2806 (Fix notification inline reply focus issue with Windows)

- src/app/notifications/notification-helper.ts
- Replace existing notification with the same tag as new notification
Note: Replace existing notification with the same tag as new notification
> fix: SDA-2811 (Replace native electron notification with same tag)

- src/app/window-handler.ts
- src/renderer/styles/notification-settings.less
When switching to french language, the notification settings window has alignment issues on the buttons. This PR fixes the issue.
> fix: SDA-2838: Fix notification settings button for french

- installer/mac/install_instructions_mac.md
- installer/mac/postinstall.sh
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/install_instructions_win.md
Currently, there's no way to set the context origin url from the installers on Windows & macOS.
This PR adds support for the same.
> feat: SDA-2846, SDA-2847: add support for context origin url in installer

- src/common/logger.ts
When we are cleaning up old logs, we check for timestamp of a log file, and, if there's no defensive check to see if the file exists, we see a JS exception. This PR fixes that issue.
N/A
> fix: SDA-2875: add defense for statSync in logger

- src/renderer/components/notification-comp.tsx
- Validate toast notification background-color
[SDA-2882](https://perzoinc.atlassian.net/browse/SDA-2882)
[SFE-Lite](https://github.com/SymphonyOSF/SFE-Lite/pull/5573)
Notes: Validate toast notification background-color
> fix: SDA-2882 (Validate notification background color)

- package.json
Upgrade Electron to fix security vulnerability -> https://github.com/electron/electron/security/advisories/GHSA-hvf8-h2qh-37m9
N/A
> fix: SDA-2934: Upgrade electron to 9.4.1

- installer/win/WixSharpInstaller/Symphony.cs
When cleaning the registry entries on uninstall, some entries has to be cleaned with elevated rights, but when executing an elevated action, the HKEY_CURRENT_USER key will be the Local System Account ("S-1-5-18" or ".DEFAULT") rather than the currently logged in user. This PR fix that by separating the registry cleaning actions in elevated and non-elevated ones.
> fix: SDA-2912 Split registry cleaning actions to elevated/non-elevated

- installer/win/WixSharpInstaller/Symphony.cs
The default Publisher/Manufacturer name is the user name of the user logged in when building the installer. This PR fix it by explicitly setting it to "Symphony"
> fix: SDA-2931 Set Symphony as the publisher name

- src/app/analytics-handler.ts
- src/renderer/notification.ts
- Update toast_closed analytic event to track only UI click actions
[SFE-Lite](https://github.com/SymphonyOSF/SFE-Lite/pull/5714)
Notes: Analytic events for toast_closed
> fix: SDA-2889 (Send analytic events for toast_closed)

- package.json
When we copy email address from right click context menu, it should copy the email address properly, this wasn't the case before, this PR fixes the issue.
Effectively, I've fixed the issue on the `electron-spellchecker` repo here -> https://github.com/symphonyoss/electron-spellchecker/commit/956382a98f4985a218d980b0fb4be96261ccf228
https://github.com/symphonyoss/electron-spellchecker/commit/956382a98f4985a218d980b0fb4be96261ccf228
> fix: SDA-2977: fix copying email address on context menu

- package.json
https://perzoinc.atlassian.net/browse/sda-3041 CORE - SDA - Right click > Search with Google does not parse the correct syntax for search results
> fix: update electron spellchecker

- src/app/window-handler.ts
https://perzoinc.atlassian.net/browse/sda-2992 SDA 9.2 766 doesn't retain "SSO" setting on upgrade
> fix: persist sso

- src/app/child-window-handler.ts
Add `symphony:` protocol to the new-window whitelist so users can open Symphony links from within SDA.
N/A
> SDA-3039: whitelist symphony protocol for new windows

- src/app/window-actions.ts
Force opening external app in case the Url's protocol is `symphony` or `mailto`
#1205
> SDA-3039: force opening external app for symphony and mailto

- package.json
- src/app/screen-snippet-handler.ts
For compatibility, make use of the built in windows tool if available. If not, use custom implementation.
> SDA-3079 Use built-in screen snippet tool on windows if available

- package.json
Using the git repo of swift-search, solves the build problem but the SDA can not consume swift-search, we get errors in the console output swift-search
> fix: go back to swift-search 2.0.2

- package.json
Make the build green, with a broken swift-search
> fix: Make the build green, with a broken swift-search

- package.json
- src/app/screen-snippet-handler.ts
Added version check to not use built in snipping tool when /clip flag is not available
> SDA-3167 Added version check 

- config/Symphony.config
- docs/development/DEV_SETUP.md
- docs/features/silent-installation-windows.md
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/install_instructions_win.md
- spec/chromeFlags.spec.ts
- src/app/chrome-flags.ts
- src/app/config-handler.ts
- src/app/window-handler.ts
RBC is blocked: they are using Azure ADFS for SSO.
Azure is using a regular expression to check user-agents. This regular expression reject queries having "Electron" as user agent.
We decided to remove "Electron" from our user-agents  to quickly fix this issue and allow RBC users (maybe other customers as well) to have SSSO.
JIRA Ticket: 
[SDA-3201](https://perzoinc.atlassian.net/browse/SDA-3201)
> SDA-3201 RBC hotfix -  Removing Electron from user-agents to support SSSO

- installer/win/WixSharpInstaller/Symphony.cs
Ability to set boolean values as args when installing SDA on Windows:
```
msiexec /i Symphony-Win64-9.3.0-909.msi OVERRIDE_USER_AGENT=true DEV_TOOLS_ENABLED=false
```
> SDA-3210 Supporting boolean as msi arg

- package.json
Version bump to get the fix for SDA-3203
> SDA-3203 Removed leftover delete which caused a crash on some Windows versions

- src/app/window-handler.ts
We are not removing Electron from user-agents anymore as it has impacts on our app (unable to call and to take screenshots + BI).
```Electron``` user-agent is replaced by ElectronSymphony to not be caught by Microsoft Azure regex.
> SDA-3201 Replacing user-agent to support Calls and snipping tool

- src/renderer/components/notification-comp.tsx
- src/renderer/styles/notification-comp.less
- src/renderer/styles/notifications-animations.less
- src/renderer/styles/variables.less
Adding behaviours to custom notifications:
- non flashing mode and external message: should use custom color if available.
- having a lighter border color when gettting a custom color (valid only in dark mode)
Took the opportunity to fix new lines not being displayed properly in notification message preview.
[SDA-3237](https://perzoinc.atlassian.net/browse/SDA-3237)
[SDA-3271](https://perzoinc.atlassian.net/browse/SDA-3271)
> SDA-3237 SDA-3271 Additional colors use-cases

- src/renderer/components/notification-comp.tsx
- src/renderer/styles/notification-comp.less
This fix aims at supporting Client 1.5 custom colors and theme with SDA >= 9.2.3.
Comments have been added to avoid any regression.
Flashing behaviour will be changed: we won't have flashing notifications background color switching from custom to red but it will switch from base color (light grey / dark grey) to custom color.
This PR contains a bugfix (SDA-3267) for notification closing that brings SDA to the front.
> Backward compatibility fix with SDA 9.2.0 and client 1.5

- package.json
- src/renderer/styles/notifications-animations.less
Notification border doesn't have the right border color in light mode. This PR aims at back-porting this issue on 9.2.3
> SDA-3237 Notification border color fix in light mode

- spec/notificationComp.spec.ts
- src/renderer/components/notification-comp.tsx
In client 1.5, "See sample" button which displays a notification sample in Settings > Alerts is sending notification data without any icon, reason why we don't have any notification displayed.
This PR fix this issue.
> SDA-3281 Client 1.5 not sending user picture

- auto_update/ipc.h
- auto_update/tests.cpp
The unit test "Can connect multiple IPC clients multiple times" failed on the build machine. This turned out to be caused by a ERROR_PIPE_BUSY error when creating the named pipe instance, most likely caused by the build machine being slower. Adding a retry (once) after a short delay makes the test succeed consistently.
> SDA-3345 Fix for failing unit test

- src/app/window-handler.ts
- Hide electron's default menu bar for Windows
> 🐛  SDA-3428 (Hide electron's default menu bar for Windows)

- src/app/crash-handler.ts
- src/app/reports-handler.ts
As long as crash dumps folder contains a crash dump, ```getLastCrashReport``` function returns a crash report with useless data ( no date, no id). Consequently, each time we launch SDA, a new crash event is sent to our BI dashboard, reason why we have so many crashes reported that doesn't reflect the reality.
> SDA-3126 Stop reporting main process crashes

- package.json
- Bump electron spellcheck version to 2.3.3
- This adds support for copying blob images to clipboard
[electron-spellchecker](https://github.com/finos/electron-spellchecker/pull/11)
> SDA-3489 (Bump electron spellcheck version to 2.3.3)

- src/app/window-handler.ts
If we try to take a large screenshot using our custom snipping tool in a "Portrait" screen mode, preview wasn't well positioned, leading to a hidden "Done button".
https://user-images.githubusercontent.com/51402489/148101981-05bfb3b7-0dad-4fb3-b981-fbbf2f3a2d04.mp4
> SDA-3534 Centering SDA snipping tool

- src/app/window-handler.ts
Blocking snipping tool height to max of screen height and width to support screen rotation.
This PR complements https://github.com/finos/SymphonyElectron/pull/1311
https://perzoinc.atlassian.net/browse/SDA-3534
> SDA-3534 Snipping tool height shouldn't be greater than screen width and height

- src/app/window-handler.ts
Blocking snipping tool width to max of screen height and width to support screen rotation.
This PR complements https://github.com/finos/SymphonyElectron/pull/1324
https://perzoinc.atlassian.net/browse/SDA-3534
> SDA-3534 Snipping tool width shouldn't be greater than screen width and height

- spec/mainApiHandler.spec.ts
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/demo/win.html
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
In order to support Citrix Media Optimization, the Citrix SDK requires that we can fetch the handle of the native window when playing video, in order to be able to place it correctly. This requires exposing the Electron function GetNativeWindowHandle to the SDA renderer process.
> SDA-3561 - Allow C2 / extensions to retrieve the native window handle

- package-lock.json
- package.json
- spec/citrixHandler.spec.ts
- spec/mainApiHandler.spec.ts
- src/app/citrix-handler.ts
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
In order to support Citrix Media Optimization, it is necessary for an extension to be able to query the current status. Only when the redirection support is active is it necessary to proceed with loading and initializing the full Citrix client-side SDK.
> SDA-3565 - Allow C2 / extensions to determine the presence of Citrix media redirection

- src/renderer/components/notification-comp.tsx
No more "Reply" tooltip on toast notifications reply button.
> SDA-3525 Removing reply tooltip for notifications

- src/app/window-handler.ts
Snipping tool should remain on the top on Windows and macOS
> SDA-3532 Snipping tool should remain on the top on Windows and MacOS

- src/app/child-window-handler.ts
- Electron is no longer setting the bounds for the newly created child bounds
- Manually set the bounds for newly created child window on `start-loading`
- [main](https://github.com/finos/SymphonyElectron/pull/1359)
> SDA-3596 (Set the bounds for newly created child window)

- spec/hwndHandler.spec.ts
- src/app/hwnd-handler.ts
- src/app/main-api-handler.ts
When calling the new (#1332) API `getNativeWindowHandle` from the main application window, the returned handle (on Windows platforms) is not correct. This is due to an implementation details of Chrome, which uses separate child windows for the two frames that make up the main window. The window where the application is hosted is a separate window that is positioned slightly below the main application window handle returned by the underlying Electron API.
> SDA-3607 - Return correct native window handle for the main window

- package-lock.json
- package.json
- src/app/window-handler.ts
Closing the penultimate window activates the last window with Electron 17 on macOS.
As a consequence, when we try to screen share an app and click on "Share" button of the screen sharing screen picker, main application is brought to the front.
Here the proposal is the create a 0x0 transparent window before closing the screen sharing screen picker. This way, shared app remains at the front.
> SDA-3646 Screen sharing hack

- src/app/window-handler.ts
- src/app/window-utils.ts
setCertificateVerifyProc sets the certificate verify proc.
There are 3 possible options:
- 0 - Indicates success and disables Certificate Transparency verification.
- -2 - Indicates failure.
- -3 - Uses the verification result from chromium.
Returning -3 let Chromium handle the result. In case the certificate is wrong (expired etc..) , `certificate-error` event is triggered.
> SDA-3140 Certificates validation bugfix

- src/app/window-handler.ts
Aligning fix #1389  on Windows and macOS
> SDA-3677 Screen sharing issue on VDIs

- src/app/window-handler.ts
- Close placeholder window only on Windows as SDA-3656/SDA-3715 only happens on Mac
Backport https://github.com/finos/SymphonyElectron/pull/1428/files
> SDA-3656 - Close placeholder window only on Windows

- src/app/app-menu.ts
- src/renderer/styles/about-app.less
As of today, several API endpoints are calling `buildMenu` function.
This method was performing a `setApplicationMenu` which is supposed to set the menu at the top of each window on Windows.
In some specific edge-cases such as opening the 'About app' window before the web app has finished loading, we noticed that a menu was displayed where it shouldn't.
This PR aims at avoiding this behaviour on Windows.
> SDA-3761 Prevent setting the menu on Windows for the whole app

- installer/win/WixSharpInstaller/WelcomeDialog.designer.cs
- package.json
Installing SDA 17 was requiring elevated privileges. That shouldn't be the case.
> SDA-3776 Ability to install SDA for local users and all users 

- spec/hwndHandler.spec.ts
- src/app/hwnd-handler.ts
Cherry-picked from the 17.0.x branch:
On Windows, the API to retrieve the native window handle selects the child window that Chrome uses to host the actual web content. If the window is maximized this unfortunately fails, as the parent window top coordinates may not be at (0,0) like the child is, but can be at something like (-8,-8) instead (depends on border decorations). This causes the RTC Citrix media optimization to position video overlays incorrectly in maximized windows.
To fix this we instead only look at the child windows. The one that is the least tall is the child window, so we can return any of the other ones. (Normally there is only one other candidate, but if developer tools are open there is a second one. They are however positioned identically so there's no need to choose …
> SDA-3707 - Fix getting window handle for maximized windows

- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
`unmaximize` event is no more triggered on Electron v19. This regression has been introduced in Electron v18.4 (cannot reproduce on v18.3). As a consequence, `on('unmaximize')` function isn't triggered anymore.
As a work-around, we force app resizing if we need to unmaximize SDA.
> SDA-3839 Resize SDA if unmaximizing

- src/app/main-api-handler.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
Screen-sharing frame and screen picker window should be closed after the end of a meeting
> SDA-3871 Closing screen-sharing frame and screen picker window after the end of a meeting

- src/app/window-handler.ts
SDA has a retry mechanism in case it fails loading target URL. If the retry mechanism happens while modal is open, the application receives a "login" event another time. Thus, we were having several modals created and we were losing control. Goal here is to unsure that we only have one single proxy auth modal at a time that correspond to latest proxy negotiation.
> bugfix/SDA-3799 Avoid having multiple proxy basic auth modals open at the same time

- src/app/config-handler.ts
Prevent from overriding global config if it's already done and parsed content is empty.
> Prevent from overriding global config if it's already done and parsed content is empty.

- src/app/window-handler.ts
Pressing native windows close will automatically crash the app for temporary. Fixed
> SDA-3958: Fix crash app on close

- installer/win/WixSharpInstaller/CloseDialog.cs
- installer/win/WixSharpInstaller/MaintenanceDialog.cs
- installer/win/WixSharpInstaller/Symphony.cs
Currently the installer tries to terminate any running C9Shell processes during installation, to avoid problems with open files that cannot be overwritten. However, as these processes may not actually be related to Symphony, this is not safe.
This reverts the installer changes from #1446
> SDA-3954 Avoid terminating C9Shell.exe during install

- spec/notificationComp.spec.ts
- src/common/api-interface.ts
- src/renderer/components/notification-comp.tsx
- src/renderer/notification.ts
For Symphony-C9 extension we need to be able to ignore an incoming call from a notification.
These changes will display an `Ignore` button on notifications when a new `hasIgnore: true` notification parameter is added.
A click on this button will trigger a `notification-ignore` event.
This is very similar to the existing notification `Reply` button.
> RTC-13524 Add notification ignore button

- spec/c9ShellHandler.spec.ts
- src/app/c9-shell-handler.ts
- src/app/main-api-handler.ts
- src/common/api-interface.ts
- src/renderer/preload-main.ts
- src/renderer/ssf-api.ts
Adds an API to make it possible to terminate a Cloud9 process, if that process was initially launched by the SDA. This will be used to forcefully stop / restart Cloud9 in the event of a failure.
> SDA-3946 - Make it possible to terminate a launched Cloud9 process

- spec/mainApiHandler.spec.ts
- src/app/main-api-handler.ts
- src/app/screen-snippet-handler.ts
- src/app/window-handler.ts
- src/renderer/styles/snipping-tool.less
- Button click will no longer keeps its previous state after click and hold and drag out then mouse up
- Popout will always be at front after screen capture windows is close (this includes add to chat)
- Default folder to save will now be located at Downloads
- Api to hide SDA will not apply for both main and popout, whenever user capture, SDA (including popout will all be hidden) then right after restoring SDA (Close, add to chat, save as), the previously focused windows will be brought to front.
> SDA-3976: Add few bugs fixed

- spec/__snapshots__/menu-button.spec.tsx.snap
- src/renderer/components/menu-button.tsx
Add a fix that forbid drag n drop on SVG Icon
> SDA-3987: Chevron SVG will no longer be draggable

- src/app/main-api-handler.ts
The data field for these messages contain an Uint8Array which causes very verbose log messages (one line per byte). The logs are much more readable if they are on a single line in a more efficient encoding such as base64.
> SDA-3998 Improve logging for API call parameters related to apiCmds.writeCloud9Pipe

- src/renderer/components/about-app.tsx
This is a side-effect of FOUC optimization:
Post FOUC optim, created window is displayed by calling `BrowserWindow.show()` method which automatically bring focus on current window. On macOS, this will automatically bring focus on "Copy" button. Goal is to blur it.
> SDA-4035 (Prevent auto-focus on copy button on component loading)

- src/app/window-handler.ts
- src/renderer/components/welcome.tsx
Add support for app restart while enabling browser authentication before defining pod URL at first time launch
Fix for pod URLs: must be prefixed by https
> SDA-4076 Add support for app restart while enabling browser authentication before defining pod URL at first time launch

- src/app/window-handler.ts
POD_URL will now be able to update URL at welcome screen
> SDA-4113: Add url from CMD

- src/app/window-utils.ts
Reload will no longer:
- Show badges (Presence and Notif)
- Show Systray Presence Menu
- Show Systray Presence
While logging out Reload will no longer
- Show badges (Presence and Notif)
- Show Systray Presence Menu
- Show Systray Presence
While going to admin page Reload will no longer
- Show badges (Presence and Notif)
- Show Systray Presence Menu
- Show Systray Presence
While going to be signed out (Suspended, Deactivated) Reload will no longer
- Show badges (Presence and Notif)
- Show Systray Presence Menu
- Show Systray Presence
> SDA-4144: The presence status is still shown when reloading SDA

- src/app/window-handler.ts
Add complete flow for authentication control
With these 6 cases:
Case 1
SSO: false
BrowserLogin: false
POD_URL: false
--> Show Enter Pod
Case 2
SSO: true
BrowserLogin: false
POD_URL: true
--> Show SSO Page
Case 3
SSO: false
BrowserLogin: true
POD_URL: false
--> Show Browser Login page
Case 4
SSO: true
BrowserLogin: true
POD_URL: true
--> Show Browser Login without POD URL Page
Case 5
SSO: false
BrowserLogin: true
POD_URL: true
--> Show Browser Login without POD URL Page
Case 6
SSO: false
BrowserLogin: false
POD_URL: true
--> Show Browser Login without POD URL Page
> SDA-4143: Add complete flow for authentication control

- installer/mac/postinstall.sh
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/install_instructions_win.md
- src/app/app-menu.ts
- src/app/config-handler.ts
- src/app/window-utils.ts
Add a new setting into config
"forceAutoUpdate"
Add new argument for msiexec
CMD: "FORCE_AUTO_UPDATE"
This config will have a higher authority since it can overwrite the config at higher level. Make local a preferable config, for Auto-update
> SDA-4223: Add new option to overwrite auto-update pmp

- src/renderer/components/call-notification.tsx
- src/renderer/styles/call-notification.less
Fonts on MacOS are slightly bigger and hence the button size needs to be bigger
> SDA-4231 (Fix button width for macOS)

- src/app/registry-handler.ts
Getting Registry has a delay. That it wont update the latest value
This PR is intended to fix the issue
> SDA-4182_racing: Add racing condition

- src/app/stores/window-store.ts
- Change logic to use minimize/restore for `Windows` and hide/show for `macOS`
Popout
Fullscreen
Minimize / Restore single window
> SDA-4219 (Change logic to use minimize/restore instead of hide/show)

- src/renderer/styles/call-notification.less
- Fix long user name in call toast notification
> SDA-4299 (Fix long user name in call toast notification)

- config/Symphony.config
- installer/mac/postinstall.sh
- installer/win/WixSharpInstaller/Symphony.cs
- installer/win/install_instructions_win.md
- spec/aboutApp.spec.ts
- src/app/config-handler.ts
- src/renderer/components/about-app.tsx
Add config to allow / disallow user to edit podconfig
User can add this property via:
in Command line: msiexec /i Symphony.msi IS_POD_URL_EDITABLE="false"
in Config file: isPodUrlEditable
> SDA-4288_main: Add config to allow / disallow user to edit podconfig

- src/app/activity-detection.ts
- src/common/utils.ts
- src/renderer/components/call-notification.tsx
- src/renderer/notification.ts
- src/renderer/styles/call-notification.less
- src/renderer/styles/theme.less
- src/renderer/styles/tool-tip.less
This PR fixes all the below issues
[SDA-4300](https://perzoinc.atlassian.net/browse/SDA-4300)
[SDA-4297](https://perzoinc.atlassian.net/browse/SDA-4297)
[SDA-4318](https://perzoinc.atlassian.net/browse/SDA-4318)
[SDA-4298](https://perzoinc.atlassian.net/browse/SDA-4298)
[SDA-4319](https://perzoinc.atlassian.net/browse/SDA-4319)
[SDA-4325](https://perzoinc.atlassian.net/browse/SDA-4325)
[SDA-4298](https://perzoinc.atlassian.net/browse/SDA-4298)
[SDA-4340](https://perzoinc.atlassian.net/browse/SDA-4340)
[SDA-4341](https://perzoinc.atlassian.net/browse/SDA-4341)
[SDA-4337](https://perzoinc.atlassian.net/browse/SDA-4337)
- Also fix typings issue with clearTimeout & clearInterval in GitHub actions
https://github.com/SymphonyOSF/SFE-RTC/pull/4826
> SDA-4300 (Fix issues related to call toast notification)

- src/app/window-handler.ts
- Add a case in which user cannot edit POD_URL if not allowed
By default this option is set to **true**, other condition if have (IS_POD_URL_EDITABLE=false)
> SDA-4321: Pod Url should be synced latest

- src/app/auto-update-handler.ts
- src/renderer/notification-handler.ts
- Limit the number of toast notifications displayed to prevent overlying of call notification
- Displays 3 toast notifications less to give space for call notification
- fix reading cloud-config field `betaAutoUpdateChannelEnabled`
> SDA-4332 & SDA-4359 (Limit toast notification to prevent overlying of call notification)

- src/renderer/components/about-app.tsx
Add ability to:
- Dismiss PodURL via pressing ESC
- Revert to previous "ENTER" PodURL
> SDA-4322: About Symphony - Unable to dismiss the pod URL editor by pressing ESC key

- src/app/auto-update-handler.ts
- `betaAutoUpdateChannelEnabled` was missed as part of https://github.com/finos/SymphonyElectron/pull/1931 due to some confusion 
https://github.com/finos/SymphonyElectron/pull/1931
> SDA-4235 (Add missing check for betaAutoUpdateChannelEnabled)

- src/renderer/notification.ts
Normal windows seem to work unexpectedly on Toast Notification
By using toolbar we can keep the notification config remained intact
> SDA-4214: Update Toast notification to use toolbar

- spec/aboutApp.spec.ts
- src/app/window-handler.ts
- src/renderer/components/about-app.tsx
Backport of https://github.com/finos/SymphonyElectron/pull/1988
but instead it will only has
Adding fix to the issue related to document.location.href changed will make pod url went unchanged
Copy to clipboard will remove updatedHostName
> SDA-4370: Switching Pod url will also change about us, remove unnecessary field in config

- src/app/stores/window-store.ts
This pr intended to resolve 2 issues:
- If you hover on the capture and capture screenshot then tooltip should disappear along with it
- If you restore after capture minimize all workspace either popout should've been restored as in order they were in before
Backport of https://github.com/finos/SymphonyElectron/pull/2002
> SDA-4329_23.11: Fixing 4329 & 4327

- src/app/stores/window-store.ts
This pr intended to resolve 2 issues:
- If you hover on the capture and capture screenshot then tooltip should disappear along with it
- If you restore after capture minimize all workspace either popout should've been restored as in order they were in before
> SDA-4329: Fixing 4329 & 4327

- src/app/stores/window-store.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- Exit fullscreen before hiding a window
https://github.com/electron/electron/issues/39572
> SDA-4256 (Exit fullscreen before hiding the main window)

- src/app/window-handler.ts
- src/renderer/preload-main.ts
Fixing Issues relating to blank screen while pressing back at all screen, some will be blacked out
Fixing another issue relating to on reloading black screen after pressing back from login screen after enter pod.
Side Note: This fix wont be able to apply to loading frame (API calling and waiting for response). Since, Electron did not provide any API supports this.
> SDA-4271: SIG-Back button causes SDA 23.4 to present a blank screen

- src/common/api-interface.ts
- src/renderer/ssf-api.ts
`showScreenSharingIndicator` is a method used by Symphony Meetings. However, when we switched from Client 1.5 to 2.0, the window object for SymphonyElectron changed name and we haven't used this method in about 3 years. However, I am investigating https://perzoinc.atlassian.net/browse/RTC-14615 about screen sharing issues and one possible explanation is that our current way of sharing screen by posting messages via `window.postMessage` disappears or don't get picked up. Therefore we should look into using the exposed SymphonyElectron methods via the window object. It could be more reliable.
> RTC-14731 - update "showScreenSharingIndicator" method

- spec/__snapshots__/aboutApp.spec.ts.snap
- spec/aboutApp.spec.ts
- src/renderer/components/about-app.tsx
Adding A11Y to Close, Close and Restart, Cancel button
Adding Remove ability to change Pod if pod is invalid and button save is disabled (Change pod to invalid -> Enter -> Cancel -> New pod has been updated -> This issue)
> SDA-4443_4444: Adding A11Y to Close and Prevent enter while pod is disabled

- .run/Demo (Build & Run).run.xml
- config/Symphony.config
- package-lock.json
- src/app/app-menu.ts
- src/app/auto-update-handler.ts
- src/app/config-handler.ts
- src/app/window-utils.ts
- Apply the latest or beta channel based on user entitlement
PMP - sda-auto-update 🛑 - Auto update disabled
PMP - sda-auto-update 🟢 - Entitlement Visibility 🛑 - Latest Channel
PMP - sda-auto-update 🟢 - Entitlement Visibility 🟢 - Check for User Entitlements as below
| Setting  | Channel |
| ------------- | ------------- |
| User Entitlement 🟢 User Entitlement Beta 🟢 | Beta Channel  |
| User Entitlement 🛑 User Entitlement Beta 🛑 | Auto Update Diabled 🛑 |
| User Entitlement 🟢 User Entitlement Beta 🛑 | Latest Channel |
| User Entitlement 🛑 User Entitlement Beta 🟢 | Beta Channel |
-----
User Entitlement = `latestAutoUpdateChannelEnabled`
User Entitlement Beta = `betaAutoUpdateChannelEnabled`
------
Entitlement Visibility = `sdaInstallerMsiUrlEnabledVisible || …
> SDA-4459 (Apply latest or beta channel based on user entitlement)

- installer/mac/postinstall.sh
- package-lock.json
- spec/__mocks__/electron.ts
- spec/childWindowHandle.spec.ts
- spec/dialogHandler.spec.ts
- spec/plistHandler.spec.ts
- src/app/config-handler.ts
- src/app/plist-handler.ts
- Migrate Symphony.config & installVariant into `/Library/Preference`
Leverages `systemPreferences.getUserDefault` to retrieve data from .plist files, configuring the application globally instead of relying on the `/config/Symphony.config` file.
> SDA-4472 (Migrate Symphony.config & installVariant into /Library/Preference)

- src/app/config-handler.ts
- Initializing a new config file will no longer include `configVersion` field
> SDA-3856 (Remove config version from user config)

- src/app/init.ts
- src/common/api-interface.ts
- src/demo/index.html
- src/renderer/components/call-notification.tsx
- src/renderer/components/notification-comp.tsx
- src/renderer/notification-theme.ts
- src/renderer/notification.ts
- src/renderer/styles/call-notification.less
- src/renderer/styles/notification-comp.less
- src/renderer/styles/notifications-animations.less
- src/renderer/styles/variables.less
- Add a federated green theme for notifications
@sbenmoussati 
- Federated light theme flashing is barely visible
- Without a badge for federated notification there is no difference between federate vs mention notification
https://github.com/finos/SymphonyElectron/assets/13243259/608ae113-599b-4bce-8d74-78b6d241336c
https://github.com/SymphonyOSF/SFE-Lite/pull/16967
> SDA-4503 (Add federated green theme for notifications 🟢)

- src/app/context-menu-builder.ts
The fix targets to remove regression on cannot copy image of Workspace / Popout. This fix does not include pasting from workspace/popout to 3rd parties, currently tech limitation.
https://github.com/finos/SymphonyElectron/assets/97150869/8b80d832-f336-4b3b-916d-b94675cfc114
> SDA-4481: Add Fix to image cannot be copied

- src/app/stores/window-store.ts
Fixing a bug relating to capture screenshot with application hidden,
If you minimize a popout and capture with app hidden, then the minimized popout will be temporarily disappeared until the next reload
> SDA-4528: Minimize Windows wont disappear on capture with SDA Hidden

- build/installer.nsh
Adding new NSIS script for migration of config file from 23.1 upto day
this script will eliminate duplicated config
> SDA-4514: NSIS Migration

- package-lock.json
- package.json
- scripts/build-linux.sh
- scripts/build-mac.sh
- scripts/build-win32.bat
- scripts/build-win64.bat
- Bump node-adapter version to 40.102.1
- Update required node version to 20.18.1
> SDA-4799 - Bump node-adapter & audit fix

- package-lock.json
- package.json
- Bump native tool versions
- Update the application icon for all the native tools
- screen-share-indicator-frame
- screen-snippet
- symphony-native-window-handle-helper
> SDA-4792 - Bump native tool versions

- src/app/window-handler.ts
- Prevent keystroke Ctrl + Shift + M from propagating in Windows
> SDA-4858 - Prevent keystroke Ctrl + Shift + M from propagating in Windows

- src/app/display-media-request-handler.ts
- src/app/notifications/call-notification.ts
- src/app/window-handler.ts
- src/app/window-utils.ts
- src/common/env.ts
- src/renderer/notification.ts
- Remove bleeding edges in all windows while zooming
- Support border radius in new acrylic / mica design of Windows
Applied only for Notifications (Call / Toast) and Screen Sharing
> SDA-4937_4944: Adding border radius to window 11 and handle bleeding edges
