README.md

Added reference to project goals and Foundation Desktop Wrapper working group.

Updated Readme w/Project Goals per JC's guidance

---

package.json

upgrade to latest electron version.

upgrade to latest electron

---

package.json

new dependency needed to build on windows.

add dep for building on windows

---

js/child-preload.js
js/main-preload.js
js/main.js

for API calls, add a security check to ensure call comes from window we have created.
also turned on sandboxing.
supports ticket: https://perzoinc.atlassian.net/browse/ELECTRON-21

Add security check

---

js/child-preload.js
js/main-preload.js

change name of api from ELECTRON_API to SYM_API

change name of api

---

config/Symphony.config
js/getConfig.js
js/main.js
js/utils.js
package.json

adds a configuration file to hold container specific value (e.g., url).
refactored a few items into utils.js

Read config

---

README.md
package.json

update readme to include more details about msi installer and start url configuration.

readme update

---

package.json

bump dev dependency ver

---

package.json

add back item accidentally deleted from package.json

fix missing item in package.json

---

README.md
js/getConfig.js
js/utils.js
package.json
tests/__mocks__/electron.js
tests/getConfig.test.js
tests/utils.test.js

add test framework 'jest' - provides unit tests and code coverage.

add unt test framework

---

tests/__mocks__/electron.js
tests/fixtures/config/Symphony.config
tests/getConfig.test.js

update tests so that runs properly on build server.
use config file in test framework.

update test for build server

---

js/dialogs/showCertError.js
js/dialogs/showLoadError.js
js/main.js
js/preload.js

add error dialogs:
- certificate errors - allow user to 'allow', 'deny', 'ignore all'
- load errors of main window.

add various error dialogs

---

js/enums/logLevels.js
js/log.js
js/main.js
js/mainApiMgr.js
js/memoryMonitor.js
js/rendererPreload.js
js/windowMgr.js
package.json
tests/README.md

- add logging
- refactor main.js into components: api mgr and window mgr.

add logging and refactor

---

.eslintignore
.eslintrc
js/dialogs/showCertError.js
js/getConfig.js
js/main.js
js/mainApiMgr.js
js/memoryMonitor.js
js/menuTemplate.js
js/rendererPreload.js
js/utils.js
js/windowMgr.js
package.json

adds eslinting using base airbnb rules.

add linting

---

js/badgeCount.js
js/mainApiMgr.js
js/rendererPreload.js
js/windowMgr.js

add badge count api

---

js/windowMgr.js

webContents not available if window has been destroyed.

fix crash on exit

---

.eslintignore
js/badgeCount.js
js/getConfig.js
js/main.js
js/preload/preloadMain.js
js/utils/getGuid.js
js/utils/misc.js
js/utils/throttle.js
js/windowMgr.js
tests/getConfig.test.js
tests/utils.test.js

update badge count interface to include throttling.

update to badge count interface

---

js/preload/createProxy.js
package.json

add missing dependency: async.
also bit of documentation
and fix running tests on windows.

add missing dep: async

---

.eslintignore
installer/Symphony-x64.aip
js/getConfig.js
js/main.js
js/utils/getRegistry.js
package.json

Redo branch & pr for registry

---

js/mainApiMgr.js
js/notify/notifyImpl.js
js/notify/notifyInterface.js
js/preload/createProxy.js
tests/__mocks__/electron.js
tests/apiTests/proxy-polyfill.js
tests/apiTests/proxyAPI.test.js

adds unit tests for proxy based api between renderer and main process.

Proxy unit tests

---

demo/index.html
js/mainApiMgr.js
js/notify/notifyImpl.js
js/notify/notifyInterface.js
js/preload/createProxy.js

adds data field to notify interface to allow arbitrary object to be passed through and accessible on event handler callback.
updates demo to show passing "data" through to callback.

update notify interface

---

js/mainApiMgr.js
js/notify/electron-notify.js
js/notify/notifyImpl.js
js/notify/notifyInterface.js
js/preload/createProxy.js

add support to raise error event to notification when max queue length is exceeded.  
notification will be not be displayed and error event will be raised with msg.

add max queue length for notifications

---

demo/index.html
js/notify/electron-notify-preload.js
js/notify/electron-notify.js
js/notify/notifyImpl.js
js/notify/notifyInterface.js

adds support for grouping of notifications.  notifications with same groupId will replace contents of existing notification.

add notification grouping

---

js/enums/api.js
js/notify/electron-notify.js

- when tag matches existing notf, be sure to raise close event for previous so it gets cleaned up.
- also: remove some unused code

Fix notf close

---

js/log.js
js/preload/preloadMain.js

update logger api

---

js/notify/electron-notify-preload.js
js/notify/electron-notify.html
js/notify/electron-notify.js

update css for notifications to match designer requirements.

update notifications css

---

tests/ScreenSnippet.test.js

skip two tests for now until screen snippet feature is supported on windows.

skip some tests (for now) on windows

---

demo/index.html
js/preload/preloadMain.js
js/search/Search.js

initial search poc code

---

demo/index.html
installer/Symphony-x64.aip
js/screenSnippet/ScreenSnippet.js
package.json

adds dependency for supporting screen snippet on windows.

add screen snippet dep for windows

---

js/utils/getRegistry.js

refactor slightly to make code more readable.
@rbarros-daitan please review.

refactor to be more readable

---

js/config.js
js/utils/isInDisplayBounds.js
js/windowMgr.js
tests/__mocks__/electron.js
tests/config.test.js
tests/fixtures/config/Symphony.config
tests/utils/getGuid.test.js
tests/utils/isInDisplayBounds.test.js
tests/utils/throttle.test.js

- add unit test for isInDisplayBounds
- move some test around

add unit test for isInDisplayBounds and config.js

---

tests/config.test.js

fix test so runs properly in windows environment.

fix config test for windows

---

package.json

downgrade to electron 1.6.7 until we hear about issue: https://github.com/electron/electron/issues/9387

downgrade to electron 1.6.7

---

js/preload/preloadMain.js

add support for both ssf and SYM_API name-space

support ssf name-space

---

.eslintrc
demo/index.html

change demo to use ssf name-space.

more ssf name-space updates

---

js/dialogs/showLoadError.js

allows close button in dialog to cancel dialog rather than attempting retry.

fix dialog when hitting close

---

js/activityDetection/activityDetection.js
tests/activityDetection.test.js

Added unit test cases for activity detection

ELECTRON-32 (Activity Detection)

---

installer/Symphony-x64.aip

Adding checkbox for AUTO_START & MINIMIZE_ON_CLOSE flags.

ELECTRON-51

---

installer/Symphony-x64.aip

changing time stamp server - the previous one is currently not responding - seems to be down for now and so we can not properly sign build.

change time stamp server

---

js/main.js

@rbarros-daitan did a small refactor to your launch on startup.  can you checkout my branch and ensure this works correctly and looks ok.  thanks.

refactor launch on startup

---

demo/index.html
js/preload/preloadMain.js

Implements api to get version info... see api details here: https://symphonyoss.atlassian.net/wiki/display/WGDWAPI/Version+API

adds getVersionInfo api

---

js/main.js
js/menus/menuTemplate.js
js/windowMgr.js

minimize on close updates, based off changes from rodrigo/ELECTRON-40

Minimize on close updates

---

js/main.js

isMac is not used and causing build failure due to linting issue.

fix linting issue in main.js

---

installer/mac/symphony-mac-packager.pkgproj

makes path relative rather than absolute.

fix mac pkg installer path

---

js/main.js

no functional change here, just moving around and renaming a few functions to make more readable.

code cleanup - no functional change

---

package.json

adds build option to build unpacked-mac app

add unpacked build option for mac

---

installer/win/Symphony-x64.aip

fix a couple of missed paths when moving win installer to new dir.

fix bad paths in aip file

---

installer/win/Symphony-x64.aip

Applying same change from DES-14034.

Add Remove Previous Version action during install

---

js/utils/throttle.js
tests/utils/throttle.test.js

throttle should throw exception if invalid args are provided.

throttle should check for valid args

---

tests/ProtocolHandler.test.js

@lneir Please review and merge.

electron-66: increased the branch coverage for the protocol handler

---

tests/activityDetection.test.js

ELECTRON-66 (Unit tests)

---

tests/activityDetection.test.js

remove target to fix activity detection tests

---

installer/win/Symphony-x64.aip
package.json

@lneir Please review and merge.

electron-69: fixes the issue raised in the ticket for windows

---

installer/mac/README.md

@lneir Please review and merge.
I've updated the readme to include limitations of the mac installer plugin (10.7+)

electron-37: updated readme

---

installer/mac/postinstall.sh

@lneir Please review and merge.

electron-75 -> Fixes the issue

---

js/config.js
tests/config.test.js

adds in memory caching of user and global config file when read from disk.  will keep from hitting disk on every read.

cache config files when read from disk

---

.gitignore

updated the gitignore file to exclude vscode settings

---

js/windowMgr.js
tests/DownloadManager.test.js

1. Fixed download manager test issues.
2. Removed usage of jQuery for tests.

electron-94: fixed issues related to download manager tests

---

package.json
tests/alwaysOnTop.test.js
tests/bringToFront.test.js
tests/clipboard.test.js
tests/notificationPosition.test.js
tests/spectron/spectronSetup.js
tests/utils/spectronSetup.js

Refactored spectron tests

---

js/notify/electron-notify.js
js/utils/misc.js
js/windowMgr.js

Implemented method to turn off sandbox mode when the app is running in node env.

Electron-98 (Node Integration and Sandbox for Tests)

---

config/Symphony.config
package.json
tests/alwaysOnTop.test.js
tests/spectron/spectronSetup.js

Implemented robotjs for always on top feature.
@VikasShashidhar & @VishwasShashidhar  Please review. Thanks

Electron-93 (Robotjs for AlwaysOnTop)

---

tests/minimize-on-close.test.js

Have integrated RobotJS as well for both Mac and Windows.

Electron 82: Spectron Tests for Minimize on Close

---

tests/close.test.js

@KiranNiranjan @VishwasShashidhar Please review.

Electron-85: Spectron Tests for close

---

tests/zoom-in-zoom-out.test.js

Integrated RobotJS tests as well for both Mac and Windows.

Electron-83: Spectron Tests for Zoom in and Zoom out

---

tests/full-screen.test.js

Includes RobotJS tests as well for both Mac and Windows.

Electron 84: Spectron Tests for Full Screen

---

tests/activityDetection.test.js
tests/notificationPosition.test.js

Throws an error if rebuild fails

Electron 90 (Catch error)

---

installer/mac/postinstall.sh
js/main.js
package.json

Implemented method to update user config on installer.
@VishwasShashidhar , @VikasShashidhar & @lneir Please review. Thanks.

Electron-77 (User config)

---

package.json
tests/activityDetection.test.js
tests/spectron/alwaysOnTop.spectron.js
tests/spectron/bringToFront.spectron.js
tests/spectron/clipboard.spectron.js
tests/spectron/close.spectron.js
tests/spectron/full-screen.spectron.js
tests/spectron/jest_spectron.json
tests/spectron/minimize-on-close.spectron.js
tests/spectron/notificationPosition.spectron.js
tests/spectron/zoom-in-zoom-out.spectron.js

1. Moved spectron test to a different directory
2. Added a `npm` command to run spectron test separately

ELECTRON-101 - Electron build issues

---

package.json

Disabling Spectron tests temporarily

---

js/main.js
js/windowMgr.js

Fixes the remote desktop(external monitor) issue on windows.
When ever an external display is disconnected we verify and validate the app bounds w.r.t to the available displays and reposition the **``main window``** accordingly.

Electron-107 - (Remote Desktop)

---

installer/mac/postinstall.sh
js/main.js
js/menus/menuTemplate.js

Changed `launchOnStartup` custom implementation to `auto-launch`.
@VikasShashidhar & @VikasShashidhar Please review. Thanks

Electron-109 (Auto Launch on Startup Mac)

---

js/spellChecker/spellChecker.js

Added a condition to not include reload in context menu when clicked on links.

Electron-114 (Reload Context Menu)

---

demo/search.html
js/cryptoLib/index.js
js/main.js
js/search/search.js

- Passing the key and the userId from the client app
- Creating a encrypted file as soon as the batch indexes are merged
- Deleting the data folder when the closes
@VikasShashidhar @jay-k & @serkanmulayim Please review. Thanks

Search-154 & Search-116 (Changed encryption implementation)

---

js/desktopCapturer/getSources.js

Fixed desktop capturer issue which was caused by a regression.
@VikasShashidhar, @VishwasShashidhar & @lneir Please review. Thanks.

Electron-125 (Electron Screen Share)

---

js/screenSnippet/index.js

Implemented a method to turn off `alwaysOnTop` while using screen snippet (windows).

Electron-118 (Screen snippet always on top)

---

js/config.js
js/main.js
js/preload/preloadMain.js
package-lock.json
package.json

Fixes user config issues and supports the latest spec.
@lneir @VikasShashidhar Please review and merge.

Electron 126

---

js/dialogs/showLoadError.js
js/windowMgr.js

@VikasShashidhar @lneir Please review.
There is no use in adding console logging because any of that is in the main process which an user won't have access to.

electron-130: fix

---

js/cryptoLib/crypto.js
package.json

Search 206
- Removed the node-forge from electron 
@VikasShashidhar @jay-k & @serkanmulayim Please review. Thanks

Search 206 (Removed node-forge)

---

demo/search.html
js/search/search.js
package.json

- Changed few checks for messages
- Passing the stringified version of the messages
@VikasShashidhar @lneir @jay-k & @serkanmulayim Please review. Thanks

Search 155 (Real time indexing)

---

installer/win/Symphony-x64.aip

Removed spellchecker dependencies from aip.

Electron-158 (Removed Spellchecker Dependencies)

---

js/windowMgr.js

As soon as a new popout is opened this updates the bound changes to the client app which fixes the pop-out issue

Electron-172 (Pop-out issue)

---

js/aboutApp/index.js

Fixes the issue where it prevents creating multiple instances of the about window.

Electron-142 (Prevents multiple instances of about window)

---

js/notify/settings/configure-notification-position.js

Added an event to update the monitor selection drop-down whenever a display is added/removed.

Electron-170 (Monitor position in notification settings)

---

js/notify/settings/configure-notification-position.js

Fixes the configuration window positioning when multiple monitors are connected

Electron-171 (Configuration window positioning)

---

js/aboutApp/index.js

Method to set the AlwaysOnTop property for about window.
@VikasShashidhar , @VishwasShashidhar & @lneir Please Review. Thanks

Electron-175 (AlwaysOnTop for about Symphony window)

---

installer/mac/symphony-mac-packager.pkgproj
installer/win/Symphony-x64.aip

@VikasShashidhar Please review and merge.

electron-185: bumped up version numbers for mac and windows installers

---

js/notify/settings/configure-notification-position.js

Fixes an error that occurs when we add/remove displays.

Electron-182 (Fixes an error in notification configuration window)

---

js/windowMgr.js

Updated min-height value of the pop-out window.

Electron-196 (Pop-out min-height)

---

js/config.js
js/main.js
js/menus/menuTemplate.js
package.json

Optimized reading config fields which fix the menu items issue on Windows.
- **Problem with the code:** There were multiple requests sent to read the config for every single field and the menu template was returned even before they returned promise.
- **Fix:** Modified the method to read and parse multiple fields so that single request can be made to read all the config fields

Electron-154 (Menu items issue on windows)

---

js/aboutApp/index.js
js/aboutApp/renderer.js
package.json

Included build version in the about app window.

Electron-142 (Build Number)

---

js/windowMgr.js

Disabled menu bar for pop-out windows

Electron-139 (Disabled menu bar)

---

js/search/search.js

Converted the fileType to lower case
@VikasShashidhar @jay-k & @serkanmulayim Please review. Thanks

Search 433 (Attachment search does not work when Electron search is enabled)

---

js/desktopCapturer/getSources.js
js/utils/misc.js

Added a check to only return screen sources if desktop composition is disabled on Windows

Electron-197 (Windows Desktop composition)

---

package.json

Electron-210

---

js/basicAuth/basic-auth.html
js/basicAuth/index.js
js/basicAuth/renderer.js
js/dialogs/showBasicAuth.js

Implemented basic auth error handler.

Electron-206 (Basic auth error handler)

---

js/windowMgr.js

Fixed an issue with the ```alwaysOnTop``` feature where changing the ```alwaysOnTop``` property focus the pop-out window.

Electron-209 (Always on top issue)

---

demo/index.html
js/notify/electron-notify-preload.js
js/notify/electron-notify.html
js/notify/electron-notify.js
js/notify/notifyImpl.js

Updated the toast notification to display company information.

Electron-211 (Added company filed to the notifications)

---

README.md

As per suggestion here https://github.com/symphonyoss/SymphonyElectron/issues/169, added a brief description about the repo.

#169: updated readme with a brief description

---

js/basicAuth/index.js

Increased the height of the BasicAuth window to prevent scrollbar from showing up [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-207)
- #### Problem with the code: Height of the window was small compared to the content
- #### Fix: Increased the height of the window

Electron-207 (Fixed scroll issue for Windows OS)

---

js/search/search.js

Converting the date from `string` to `int` to validate and added safety check
[JIRA-ticket](https://perzoinc.atlassian.net/browse/SEARCH)
@VikasShashidhar @jay-k & @serkanmulayim Please review. Thanks

SEARCH-480 (Message Filters)

---

js/compressionLib/index.js
js/cryptoLib/crypto.js
js/cryptoLib/index.js
js/search/search.js
js/search/searchConfig.js
js/search/searchLibrary.js

Moved all the search constants to a single file `searchConfig.js`
[JIRA-ticket](https://perzoinc.atlassian.net/browse/SEARCH-440)
@VikasShashidhar @serkanmulayim Please review. Thanks

SEARCH-440 (Search configuration file for electron)

---

js/search/search.js

[SEARCH-535](https://perzoinc.atlassian.net/browse/SEARCH-535)
- Using the Node.js to remove the index data folder
- SEARCH-501 fixed some linting issues

SEARCH-535 (Deleting the index folder)

---

js/windowMgr.js

Updated the default window size as per the new requirement [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-225)
@VikasShashidhar & @VishwasShashidhar Please review. Thanks :)

Electron-225 (Updated the default window size)

---

package.json

Bumped up the version to 2.2.0

Beta release 3 (2.2.0)

---

demo/search.html
js/cryptoLib/crypto.js
js/cryptoLib/index.js
js/preload/preloadMain.js
js/search/search.js
js/search/searchConfig.js
js/search/searchUtils.js
js/search/utils/checkDiskSpace.js

[SEARCH-539](https://perzoinc.atlassian.net/browse/SEARCH-539)
Checking the disk space before enabling the electron search(and setting a Minimum of 300MB).
[SEARCH-206](https://perzoinc.atlassian.net/browse/SEARCH-206)
Using the index encryption-key form the backend and writing the rotation information to the user config file.
@VikasShashidhar @serkanmulayim Please review. Thanks

SEARCH-539 & SEARCH-206 (Encryption-Key and Disk Space)

---

demo/search.html
js/search/search.js

Included new API to delete the real-time index folder
[SEARCH-544](https://perzoinc.atlassian.net/browse/SEARCH-544)
@VikasShashidhar @serkanmulayim Please review. Thanks

SEARCH-544 (Re-create real-time index)

---

demo/search.html
installer/win/Symphony-x64.aip
js/compressionLib/index.js
js/cryptoLib/crypto.js
js/cryptoLib/index.js
js/main.js
js/preload/preloadMain.js
js/search/queue.js
js/search/search.js
js/search/searchConfig.js
js/search/searchLibrary.js
js/search/searchUtils.js
js/search/utils/checkDiskSpace.js
js/windowMgr.js
package.json

This reverts commit 1388c835ef7904806560f6ab2c304d8851bd7739, reversing
changes made to c9d6229d6db8eee8b50d1d44a3d567cd691f68e2.

Revert "Merge pull request #269 from keerthi16/skynet"

---

js/downloadManager/index.js
js/windowMgr.js

Fixes electron-205 post merge conflict regression.

electron-205: fixes the already fixed issue post merge conflict regression

---

js/basicAuth/basic-auth.html

Added type button to prevent form from submitting [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-253)
- #### Problem with the code: For the cancel button property `type` was not defined 
- #### Fix: Added property type button

Electron-253 (Basic auth issue)

---

js/notify/electron-notify.js

1. Fixes an error "Object has been destroyed"
2. Added method to close all notifications when the configuration is changed  
[JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-222)
[JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-254)
- #### Problem with the code: There was no safety check added before accessing the browser window
- #### Fix: Added a safety check

Electron-222 (Fixes Notifications Javascript Error)

---

installer/win/Symphony-x64.aip

Fixed the regex in .aip to write the correct value to the user config  [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-231)
- #### Problem with the code: Regex was looking for the `"minimizeOnClose";\s*:\s*false` instead of the value true
- #### Fix: Changed the regex to `"minimizeOnClose";\s*:\s*true`

Electron-231 (Fixes the installer config issue on Windows)

---

package.json

This new electron version fixes security issues [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-286)

electron-286: upgrade electron version to 1.7.11

---

demo/search.html
js/cryptoLib/index.js
js/search/search.js
js/search/searchConfig.js
js/search/utils/randomString.js
package.json
tests/Search.test.js

Removed the randomString library and included custom file
Made some refactoring which was exposing the paths.
[JIRA-ticket](https://perzoinc.atlassian.net/browse/SEARCH-622)
- #### Problem with the code: Using a third party for generating randomString.
- #### Fix: Created a custom js file for generating randomString.

SEARCH-622 (Remove the "randomString" dependency from electron & refactoring)

---

demo/index.html
js/desktopCapturer/getSource.js
js/desktopCapturer/getSources.js
js/desktopCapturer/index.js
js/desktopCapturer/renderer.js
js/desktopCapturer/screen-picker.html
js/enums/api.js
js/mainApiMgr.js
js/preload/preloadMain.js

Previous implementation (`MediaSelectorModal`) had issues with the screen picker not showing when the meeting is in fullscreen mode. Changed the implementation from modal to electron browser window 
[ELECTRON-256](https://perzoinc.atlassian.net/browse/ELECTRON-256)
[ELECTRON-197](https://perzoinc.atlassian.net/browse/ELECTRON-197)
- #### Problem with the code: Clicking on the `share screen` button in the meeting does not show the screen picker modal when the meeting is in fullscreen mode.
- #### Fix:  Changing the implementation from modal to electron browser window fixes the issue
N/A
N/A
@VikasShashidhar & @VishwasShashidhar Please Review. Thanks 😄

Electron-256 (Changed the implementation from modal to electron window)

---

js/notify/electron-notify-preload.js
js/notify/electron-notify.js
js/notify/settings/configure-notification-position.js

Fix javascript error in notification [ELECTRON-235](https://perzoinc.atlassian.net/browse/ELECTRON-235)
- Window close was not handled and using an already closed window throws a javascript error
- Cleaning up the stored notification window whenever the notification window is closed
[Electron-235 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1819113/Electron-235.Spectron.pdf)
[ELECTRON-235 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1819115/ELECTRON-235.Unit.Tests.pdf)

Electron-235 (Fix javascript error in notification)

---

js/utils/archiveHandler.js
package.json

Fix generating crash report [ELECTRON-409](https://perzoinc.atlassian.net/browse/ELECTRON-409)
- File validation module was not working
- Removed `mmmagic` module and added a simple validation
[Electron-409 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1902161/Electron-409.Spectron.pdf)
[Electron-409 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1902164/Electron-409.Unit.Tests.pdf)
@VishwasShashidhar @VikasShashidhar Please review. Thanks 😄

Electron-409 (Fix generating crash report)

---

demo/search.html
js/preload/preloadMain.js
js/search/search.js
js/search/searchConfig.js
js/search/searchLibrary.js
tests/Search.test.js

Real-Time indexing (Memory)
[SEARCH-627](https://perzoinc.atlassian.net/browse/SEARCH-627)
Batch-Indexing (Memory)
[SEARCH-628](https://perzoinc.atlassian.net/browse/SEARCH-628)
- Batch indexing to memory 
- Real-time index to memory.
- Search results from memory.
N/A
N/A
branch | PR
other_pr_rc | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/8744)
other_pr_dev | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/8743)
@VikasShashidhar @serkanmulayim Please review. Thanks 😃

SEARCH-627 & SEARCH-628 (Memory Indexing)

---

installer/mac/postinstall.sh
installer/win/Symphony-x64.aip
installer/win/Symphony-x86.aip
js/config.js
js/log.js
js/main.js
js/utils/compareSemVersions.js
package.json

Changed the logic from updating the user config from launching an instance of the Symphony to when the app is first launched [ELECTRON-433](https://perzoinc.atlassian.net/browse/ELECTRON-433)
- The previous implementation had a permissions issue with the app path being `root`
- Changed the logic to update the user config on the first launch
@VishwasShashidhar @VikasShashidhar Please review. Thanks 😄

Electron-433 (Changes the logic for updating user config)

---

installer/win/Symphony-x64.aip
installer/win/Symphony-x86.aip

Remove unwanted files in advanced installer [ELECTRON-391](https://perzoinc.atlassian.net/browse/ELECTRON-391)
@VishwasShashidhar @VikasShashidhar Please review. Thanks 😃

Electron-391 (Remove unwanted files in advanced installer)

---

js/aboutApp/index.js
js/basicAuth/index.js
js/desktopCapturer/index.js
js/notify/electron-notify.js
js/notify/settings/configure-notification-position.js
js/windowMgr.js

This PR helps in adding another layer of security to the Electron container. Enabling context isolation is going to provide the container and the remote content loaded in it their own sets of JS context thus preventing any modification of global objects. [ELECTRON-430](https://perzoinc.atlassian.net/browse/ELECTRON-430)
N/A
N/A
N/A
N/A

ELECTRON-430: Enable context isolation

---

installer/win/Symphony-x64.aip

Change the value of location and media checkboxes [ELECTRON-460](https://perzoinc.atlassian.net/browse/ELECTRON-460)
- Checkboxes value was wrong and was causing javascript validation to fail for `media` and `geo locations`
- Changed the checkboxes value to `true` which fixes the issue
@VishwasShashidhar @VikasShashidhar Please review. Thanks 😃

Electron-460 (Change the value of location and media checkboxes)

---

js/aboutApp/index.js
js/basicAuth/index.js
js/desktopCapturer/index.js
js/notify/electron-notify.js
js/notify/settings/configure-notification-position.js
js/windowMgr.js

Reverts symphonyoss/SymphonyElectron#340

Revert "ELECTRON-430: Enable context isolation"

---

js/main.js
js/menus/menuTemplate.js

Change the menu item name for "Memory Refresh" as per the new copy writing i.e. "Refresh app when idle" [ELECTRON-456](https://perzoinc.atlassian.net/browse/ELECTRON-456)
N/A
N/A
N/A
N/A
[ELECTRON-456 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1987545/ELECTRON-456.Unit.Tests.pdf)
[ELECTRON-456 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/1987546/ELECTRON-456.Spectron.Tests.pdf)

Electron 456

---

js/main.js

Fix launch on startup issues when the app is installed and launched first time [ELECTRON-479](https://perzoinc.atlassian.net/browse/ELECTRON-479)
- #### Problem with the code: String to boolean comparison doesn't work in the method setStartup of main.js
- #### Fix: Fixed the comparison to use appropriate logic.
N/A
N/A
N/A
[ELECTRON-479 Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2023109/ELECTRON-479.Unit.Tests.pdf)
[ELECTRON-479 Spectron Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2023129/ELECTRON-479.Spectron.Tests.pdf)

ELECTRON-479: fix launch on startup issue on first time launch

---

tests/spectron/alwaysOnTop.spectron.js
tests/spectron/resizeWindows.spectron.js
tests/spectron/spectronSetup.js

Add test "Verify whether the main window can be minimized upto 300px" [AVT-768](https://perzoinc.atlassian.net/browse/AVT-768)
Please refer attachment for more details
[jest_test_report.zip](https://github.com/symphonyoss/SymphonyElectron/files/2110589/jest_test_report.zip)

AVT-768 Add test "Verify whether the main window can be minimized upto 300px"

---

js/memoryMonitor.js
js/preload/preloadMain.js

Change the memory refresh logic to auto-refresh after 4Hrs of user inactivity [ELECTRON-445](https://perzoinc.atlassian.net/browse/ELECTRON-445)
Changed the implementation to auto refresh the application when the user is idle for about 4Hrs
[Memory Refresh](https://perzoinc.atlassian.net/wiki/spaces/DES/pages/437026872/Electron+Feature+-+Memory+Refresh)
branch | PR
Previous Implementation | [link](https://github.com/symphonyoss/SymphonyElectron/pull/360)
[ELECTRON-445 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2140415/ELECTRON-445.Unit.Tests.pdf)
[ELECTRON-455 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2140416/ELECTRON-455.Spectron.pdf)

ELECTRON-445 (Change the memory refresh logic to auto-refresh after 4Hrs of user inactivity)

---

js/windowMgr.js

Fix keyboard shortcut issues on Windows 10 
[ELECTRON-588](https://perzoinc.atlassian.net/browse/ELECTRON-588)
[ELECTRON-590](https://perzoinc.atlassian.net/browse/ELECTRON-590)
[ELECTRON-234](https://perzoinc.atlassian.net/browse/ELECTRON-234)
Attach menu for all platform and hide for a specific platform (Windows 10) so that the accelerators are set properly
[ELECTRON-588 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2162663/ELECTRON-588.Unit.Tests.pdf)
[Electron-588 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2162664/Electron-588.Spectron.pdf)

ELECTRON-588 (Fix keyboard shortcut issue on Windows 10)

---

js/notify/settings/configure-notification-position.js

Prevents from opening multiple instances of notification configuration window [ELECTRON-539](https://perzoinc.atlassian.net/browse/ELECTRON-539)
Checking if the window exists and restoring the window instead of creating a new window
N/A
[Electron-539 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2175379/Electron-539.Unit.Tests.pdf)
[Electron-539 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2175383/ELECTRON-539.Spectron.pdf)

ELECTRON-539 (Prevent multiple instance of notification configuration window)

---

js/windowMgr.js

Register global shortcuts initially [ELECTRON-618](https://perzoinc.atlassian.net/browse/ELECTRON-618)
Registering global shortcuts on app launch
[ELECTRON-618 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2210419/ELECTRON-618.Unit.Tests.pdf)
[ELECTRON-618 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2210421/ELECTRON-618.Spectron.pdf)

ELECTRON-618 (Initially register global shortcut)

---

tests/spectron/alwaysOnTopWithMultApps.spectron.js
tests/spectron/saveLayout.spectron.js
tests/spectron/spectronConstants.js
tests/spectron/spectronInterfaces.js
tests/spectron/spectronSetup.js
tests/spectron/spectronUtils.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWindowsActions.js

Add test "Verify Always on Top options when multiple applications are opened" [AVT-990](https://perzoinc.atlassian.net/browse/AVT-990)
Please refer attachment for more details
[Jest Test Report.zip](https://github.com/symphonyoss/SymphonyElectron/files/2230932/Jest.Test.Report.zip)

 AVT-990 [Spectron][Windows] Add test "Verify Always on Top options when multiple applications are opened"

---

js/menus/menuTemplate.js
js/preload/preloadMain.js
js/windowMgr.js

Aditional Fixes and improments for  [ELECTRON-607](https://perzoinc.atlassian.net/browse/ELECTRON-607)
- SetLocale
- Optimize Alt Keypress 
- Optimize title bar style menu selection
branch | PR
SymphonyElectron | [link](https://github.com/symphonyoss/SymphonyElectron/pull/451)
[ELECTRON-607 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2266305/ELECTRON-607.Unit.Tests.pdf)
[ELECTRON-607 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2266301/ELECTRON-607.Spectron.pdf)

ELECTRON-607 (Optimization and bug fix)

---

tests/spectron/spectronConstants.js
tests/spectron/spectronSetup.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWebDriver.js
tests/spectron/spectronWindowsActions.js
tests/spectron/toastMouseHoveringForIM.spectron.js
tests/spectron/turnONPersistentToast.spectron.js

Verify toast notification for IMs
[AVT-1031](https://perzoinc.atlassian.net/browse/AVT-1031)
Verify toast notification for signals, mentions and keywords
[AVT-1032](https://perzoinc.atlassian.net/browse/AVT-1032)
Please refer attachment for more details
[Jest Test Report.zip](https://github.com/symphonyoss/SymphonyElectron/files/2248904/Jest.Test.Report.zip)

AVT-1031 AND AVT-1032: Verify toast notification for IMs, Signal,Room

---

tests/spectron/resizeWindows.spectron.js
tests/spectron/spectronWindowsActions.js

[Spectron][MAC] Verify whether the main window can be minimized upto 300px
[AVT-1096](https://perzoinc.atlassian.net/browse/AVT-1096)
Add a link to the documentation for this issue / PR. Can be confluence / this repository's file link
branch | PR
Result 
[resizeWindows_On_Mac_And_Windows.zip](https://github.com/symphonyoss/SymphonyElectron/files/2269496/resizeWindows_On_Mac_And_Windows.zip)

[Spectron][MAC] Verify whether the main window can be minimized upto 300px

---

tests/spectron/badgeCount.spectron.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWindowsActions.js

[Spectron][MAC] Show 1 in tray icon when unread message = 1 
[AVT-1095](https://perzoinc.atlassian.net/browse/AVT-1095)
Add a link to the documentation for this issue / PR. Can be confluence / this repository's file link
branch | PR
[badgeCountOnMac.zip](https://github.com/symphonyoss/SymphonyElectron/files/2273062/badgeCountOnMac.zip)

[AVT-1095] - [Spectron][MAC] Show 1 in tray icon when unread message = 1

---

tests/spectron/pop-Outs.spectron.js
tests/spectron/spectronConstants.js
tests/spectron/spectronInterfaces.js
tests/spectron/spectronSetup.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWindowsActions.js
tests/spectron/toastMouseHoveringForIM.spectron.js
tests/spectron/turnONPersistentToast.spectron.js

Add test "pop-out chat, inbox" [JIRA-ticket](https://perzoinc.atlassian.net/browse/JIRA-ticket)
[Jest Test Report.zip](https://github.com/symphonyoss/SymphonyElectron/files/2281721/Jest.Test.Report.zip)

AVT-1081 [Spectron][Windows] pop-out chat, inbox

---

js/aboutApp/renderer.js
js/desktopCapturer/renderer.js
js/notify/electron-notify-preload.js
js/notify/settings/configure-notification-position-preload.js
js/windowMgr.js

Prevent drag and drop of files [ELECTRON-648](https://perzoinc.atlassian.net/browse/ELECTRON-648)
Prevent from navigating to a file whenever users `drag and drop` on to the application
[ELECTRON-648 — Unit Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2286352/ELECTRON-648.Unit.Tests.pdf)
[ELECTRON-648 — Spectron.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2286350/ELECTRON-648.Spectron.pdf)

ELECTRON-648 (Prevent drag and drop of files)

---

tests/spectron/spectronInterfaces.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWebDriver.js
tests/spectron/spectronWindowsActions.js
tests/spectron/toastNotification.spectron.js

Add test "[Spectron][Windows] Configure alert position at top/bottom left/right " [AVT-1026](https://perzoinc.atlassian.net/browse/AVT-1026)
[Jest Test Report.zip](https://github.com/symphonyoss/SymphonyElectron/files/2289853/Jest.Test.Report.zip)

AVT-1026 [Spectron][Windows] Configure alert position at top/bottom left/right 

---

tests/spectron/badgeCount.spectron.js
tests/spectron/pop-Outs.spectron.js
tests/spectron/spectronInterfaces.js
tests/spectron/spectronWebActions.js
tests/spectron/toastMouseHoveringForIM.spectron.js

Add test "[Spectron][Windows] Pop-in popped-out chat" [AVT-1082](https://perzoinc.atlassian.net/browse/AVT-1082)
https://jenkins2.symphony.com/job/electron-robot-playground/102/

AVT-1082 [Spectron][Windows] Pop-in popped-out chat

---

js/cryptoLib.js
package.json

revert: ffi-napi - napi_get_uv_event_loop issue on Windows
[SEARCH-915](https://perzoinc.atlassian.net/browse/SEARCH-915)
branch | PR
SwiftSearch | [link](https://github.com/symphonyoss/SwiftSearch/pull/4)
[Test Results — Unit-Tests.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2313608/Test.Results.Unit-Tests.pdf)

SEARCH-915 - Revert back to ffi (ffi-napi - napi_get_uv_event_loop issue on Windows)

---

js/preload/preloadMain.js
js/windowsTitleBar/index.js

Electron - Full screen mode disappears after reloading app [ELECTRON-647](https://perzoinc.atlassian.net/browse/ELECTRON-647)
- After

ELECTRON-647 - Fixing fullscreen mode disappears after reloading app

---

js/enums/api.js
js/main.js
js/mainApiMgr.js
js/memoryMonitor.js
js/preload/preloadMain.js
js/windowMgr.js

Implement aggressive refresh to optimize refresh [ELECTRON-730](https://perzoinc.atlassian.net/browse/ELECTRON-730)
1. Register preload window (to get the memory info)
2. Register for the following events (minimize, restore, screen locked & unlocked)
3. Based on the above events `main process` requests memory info
4. Preloads sends the `memory info` via IPC
5. If the following conditions satisfy then refreshes the window
- Memory usage > 800
- CPU usage percentage < 5
- User not in a meeting
- Network status is online
- Reload threshold > 1hrs
[ELECTRON-730 Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2339938/ELECTRON-730.Test.Result.pdf)

ELECTRON-730 (Implement aggressive refresh to optimize refresh)

---

package.json

Fix the Spectron issue when upgrading to new Electron version
[AVT-1187](https://perzoinc.atlassian.net/browse/AVT-1187)
Add a link to the documentation for this issue / PR. Can be confluence / this repository's file link
branch | PR

Upgrade electron-chromedriver version to 3.0.0-beta.1

---

tests/spectron/spectronConstants.js

Updated Timeout constants as parameters pass through via Jenkins instead of hardcode.

Updated Timeout constants

---

tests/spectron/spectronInterfaces.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWindowsActions.js
tests/spectron/spellChecker.spectron.js

[Spectron] Review and update the existing tests in spellChecker.spectron [AVT-1155](https://perzoinc.atlassian.net/browse/AVT-1155)
https://jenkins2.symphony.com/job/electron-robot-playground/202/
https://jenkins2.symphony.com/job/electron-robot-playground/201/
https://jenkins2.symphony.com/job/electron-robot-playground/200/

AVT-1155 [Spectron] Review and update the existing tests in spellChecker.spectron

---

tests/spectron/bringToFront.spectron.js
tests/spectron/close.spectron.js
tests/spectron/spectronConstants.js
tests/spectron/spectronInterfaces.js
tests/spectron/spectronWebActions.js
tests/spectron/spectronWebDriver.js
tests/spectron/spectronWindowsActions.js

Review and fix : AVT-1141,AVT-1142,AVT-1144
(https://perzoinc.atlassian.net/browse/AVT-1141)
(https://perzoinc.atlassian.net/browse/AVT-1142)
(https://perzoinc.atlassian.net/browse/AVT-1144)
Please refer attachment for more details
[Spectron Tests Report.zip](https://github.com/symphonyoss/SymphonyElectron/files/2359386/Spectron.Tests.Report.zip)

AVT-1141: Review and fix : AVT-1141,AVT-1142,AVT-1144

---

tests/spectron/full-screen.spectron.js
tests/spectron/pop-Outs.spectron.js
tests/spectron/spectronSetup.js
tests/spectron/spectronWindowsActions.js

Review and update the existing tests in full-screen.spectron [AVT-1146](https://perzoinc.atlassian.net/browse/AVT-1146)
https://jenkins2.symphony.com/job/electron-robot-playground/196/
https://jenkins2.symphony.com/job/electron-robot-playground/195/
https://jenkins2.symphony.com/job/electron-robot-playground/194/

AVT-1146 [Spectron] Review and update the existing tests in full-screen.spectron

---

tests/spectron/getVersionInfo.spectron.js
tests/spectron/spectronInterfaces.js
tests/spectron/spectronWebActions.js

[Spectron] Review and update the existing tests in getVersionInfo.spectron [AVT-1147](https://perzoinc.atlassian.net/browse/AVT-1147)
https://jenkins2.symphony.com/job/electron-robot-playground/198/

AVT-1147 [Spectron] Review and update the existing tests in getVersionInfo.spectron

---

js/notify/electron-notify-preload.js
js/notify/electron-notify.html
js/notify/electron-notify.js

Dynamically update notification based on message length [ELECTRON-801](https://perzoinc.atlassian.net/browse/ELECTRON-801)
Resize/Rearrange notification content based on the message text length
[Electron-801 Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2430660/Electron-801.Test.Result.pdf)

ELECTRON-801 (Dynamically update notification based on message length)

---

js/main.js
js/mainApiMgr.js
js/memoryMonitor.js
js/preload/preloadMain.js

This reverts commit 0c8b322 from ` rc-1.53.0`

Revert "ELECTRON-758 (Change network request implementation to use electron's API)

---

js/cryptoLib.js

SymphonyElectron was being crashed when the app is reloaded [ELECTRON-808](https://perzoinc.atlassian.net/browse/ELECTRON-808)
Remove RSADecrypt related methods temporarily
**Crash Report:**
<details>
<summary>Click to expand</summary>
Process:               Electron [96940]
Path:                  /Users/USER/Documents/*/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.electron
Version:               3.0.2 (3.0.2)
Code Type:             X86-64 (Native)
Parent Process:        webstorm [1633]
Responsible:           webstorm [1633]
User ID:               501
Date/Time:             2018-10-10 12:53:54.592 +0530
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        F2BAC63D-0F2D-38C2-BF1C-8B9A5C760250
Sleep/Wake UUID: …

ELECTRON-808 (Remove RSA related methods to fix crash issue)

---

js/spellChecker/index.js

Describe the problem or feature in addition to a link to the [JIRA-ticket](https://perzoinc.atlassian.net/browse/JIRA-ticket)
Add a link to the documentation for this issue / PR. Can be confluence / this repository's file link
branch | PR

remove attachToInput method

---

js/activityDetection/index.js
js/memoryMonitor.js
js/preload/preloadMain.js
package.json
tests/__mocks__/electron.js
tests/activityDetection.test.js

Blackrock Prod - Electron Desktop Presence in Citrix VDI environment not accurate
[ELECTRON-928](https://perzoinc.atlassian.net/browse/ELECTRON-928).
branch | PR
ELECTRON-928-master | [link](https://github.com/SymphonyOSF/SFE-Client-App/pull/12974)
https://github.com/facebook/jest/issues/936#issuecomment-214939935 
[Symphony Electron Test Result - ELECTRON-928.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2657252/Symphony.Electron.Test.Result.-.ELECTRON-928.pdf)

ELECTRON-928 - Migrate Presence to the Power Monitor API

---

package.json

Reverts symphonyoss/SymphonyElectron#549

Revert "SEARCH-1243 (Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019)"

---

jest.unit.config.json
package.json
spec/__mocks__/electron.ts
spec/log.spec.ts
src/common/logger.ts

Adding log.test.ts this is the unit test of logger.ts

logger unit test

---

js/windowMgr.js
locale/en-US.json
locale/en.json
locale/fr-FR.json
locale/fr.json
locale/ja-JP.json
locale/ja.json
package.json

Revert changes of https://github.com/symphonyoss/SymphonyElectron/pull/553
N/A
N/A
N/A
[ELECTRON-965-revert Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2805926/ELECTRON-965-revert.Unit.Tests.Report.pdf)

ELECTRON-965: revert the changes

---

locale/ja-JP.json
locale/ja.json

Fix localisation strings for download manager 
[ELECTRON-1051](https://perzoinc.atlassian.net/browse/ELECTRON-1051)
N/A
N/A
N/A
[ELECTRON-1051 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2812722/ELECTRON-1051.Unit.Tests.Report.pdf)

ELECTRON-1051: fix localisation strings for download manager

---

package.json

Screen snip- Not working correctly with (2) 4K screens. [ELECTRON-1009](https://perzoinc.atlassian.net/browse/ELECTRON-1009)
N/A
N/A
branch | PR
vrbsm:ELECTRON-1009| [link](https://github.com/symphonyoss/ScreenSnippet/pull/6)

ELECTRON-1009: bump up version screen snippet

---

spec/__mocks__/electron.ts
spec/config.spec.ts

config unit test

---

package.json

Snipping tool capture quality degraded. [ELECTRON-802](https://perzoinc.atlassian.net/browse/ELECTRON-802)
N/A
N/A
branch | PR
vrbsm/ScreenSnippet:ELECTRON-802 | [link](https://github.com/symphonyoss/ScreenSnippet/pull/7)

ELECTRON-802: ScreenSnippet improving capture quality

---

package.json

Improve recency and relevance sort
[SEARCH-1347](https://perzoinc.atlassian.net/browse/SEARCH-1347)
If the sort options are selected as recency  we do not tokenize each word
N/A
branch | PR
SwiftSearch | [link](https://github.com/symphonyoss/SwiftSearch/pull/10)
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2874338/Symphony.Electron.Test.Result.pdf)

SEARCH-1347 [Master] - Improve recency and relevance sort filter

---

js/preload/preloadMain.js

fixing indentation in preloadMain
N/A
N/A
N/A

fixing indentation in preloadMain

---

jest.unit.config.json

fixing jest output report
adjust the jest.config setting
n/a
n/a

fixing jest coverage output report

---

spec/protocolHandler.spec.ts

protocol handle unit test

---

js/log.js
js/main.js
js/mainApiMgr.js
js/windowMgr.js

Fix issue where we were opening new window for same pod url 
[ELECTRON-1050](https://perzoinc.atlassian.net/browse/ELECTRON-1050)
Check if the new window url is the same as the main window url and if they are, open it in a browser rather than in a new window
N/A
N/A
[ELECTRON-1050 Unit Tests Report.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2924847/ELECTRON-1050.Unit.Tests.Report.pdf)

ELECTRON-1050: fix issue where we were opening new window for same pod url 

---

jest.unit.config.json
package.json
spec/__snapshots__/downloadManager.spec.ts.snap
spec/downloadManager.spec.ts
spec/protocolHandler.spec.ts
spec/setup/test-setup.js
src/renderer/components/download-manager.tsx

Typescript download manager unit test

---

spec/__mocks__/electron.ts

fixing config handle unit test

fix app path on windows

---

spec/__snapshots__/basicAuth.spec.ts.snap
spec/basicAuth.spec.ts

basic auth unit test

---

spec/__mocks__/electron.ts
spec/__snapshots__/screenPicker.spec.ts.snap
spec/__snapshots__/screenSharingIndicator.spec.ts.snap
spec/downloadManager.spec.ts
spec/screenPicker.spec.ts
spec/screenSharingIndicator.spec.ts

- screen picker unit test
- screen sharing indicator unit test
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2958205/Symphony.Electron.Test.Result.pdf)

screen picker unit test

---

spec/__snapshots__/loadingScreen.spec.ts.snap
spec/loadingScreen.spec.ts

loading screen unit test
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2956909/Symphony.Electron.Test.Result.pdf)

loading screen unit test

---

spec/__snapshots__/snackBar.spec.ts.snap
spec/snackBar.spec.ts

snack bar unit test
[snackbar-unittest.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2963774/snackbar-unittest.pdf)

snack bar unit test

---

spec/__mocks__/electron.ts
spec/__snapshots__/windowsTitleBar.spec.ts.snap
spec/windowsTitleBar.spec.ts

windows title bar unit test
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2973297/Symphony.Electron.Test.Result.pdf)

windows title bar unit test

---

spec/utils.spec.ts
src/common/utils.ts

utils unit test

---

js/windowMgr.js

Display network error info screen only if SDA ends up in a blank screen
[ELECTRON-967](https://perzoinc.atlassian.net/browse/ELECTRON-967)
[ELECTRON-1141](https://perzoinc.atlassian.net/browse/ELECTRON-1141)
Listen only on `did-stop-load` and verify if SDA ends up in a blank screen to display network error
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/606)
Implementation | [link](https://github.com/symphonyoss/SymphonyElectron/pull/600)

ELECTRON-1141 (Display network error info screen only if SDA ends up in a blank screen)

---

spec/__mocks__/electron.ts
spec/appCacheHandler.spec.ts

app cache handler unit test
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2985187/Symphony.Electron.Test.Result.pdf)

app cache handler unit test

---

spec/__mocks__/electron.ts
spec/appMenu.spec.ts
src/app/app-menu.ts

app menu unit test
[Symphony Electron Test Result.pdf](https://github.com/symphonyoss/SymphonyElectron/files/2990629/Symphony.Electron.Test.Result.pdf)

app menu unit test

---

spec/__snapshots__/aboutApp.spec.ts.snap
src/app/app-menu.ts
src/app/window-handler.ts
src/renderer/components/about-app.tsx

About app component for Windows

Typescript (About app for Windows)

---

spec/__mocks__/electron.ts
spec/activityDetection.spec.ts
spec/autoLaunchController.spec.ts
spec/config.spec.ts
spec/log.spec.ts

Typescript autolaunch unittest

---

spec/__mocks__/electron.ts
spec/childWindowHandle.spec.ts

child window handle unit test

---

package.json

Support New Field for Indexing
This fixes the below bugs
[SEARCH-1346](https://perzoinc.atlassian.net/browse/SEARCH-1346)
[SEARCH-1294](https://perzoinc.atlassian.net/browse/SEARCH-1294)
- Message renderer required fields missing from the index.
- Includes new library which supports indexing any fields inside `renderingBlob` so that we no longer required to change the library if any new fields are added to message object.
N/A
N/A
SFE-Client-App | branch-name | [PR #12184](https://github.com/SymphonyOSF/SFE-Client-App/pull/14184)
Swift-Search | branch-name | [PR #12](https://github.com/symphonyoss/SwiftSearch/pull/12) …

SEARCH-1346 - Support new field renderingBlob Swift Search

---

js/desktopCapturer/renderer.js
js/main.js
js/moreInfo/index.js
js/moreInfo/more-info.html
js/moreInfo/renderer.js
locale/en-US.json
locale/en.json
locale/fr-FR.json
locale/fr.json
locale/ja-JP.json
locale/ja.json

Fix localisation issues on the following tickets.
[ELECTRON-1073](https://perzoinc.atlassian.net/browse/ELECTRON-1073)
[ELECTRON-1074](https://perzoinc.atlassian.net/browse/ELECTRON-1074)
[ELECTRON-1097](https://perzoinc.atlassian.net/browse/ELECTRON-1097)
[ELECTRON-1052](https://perzoinc.atlassian.net/browse/ELECTRON-1052)
N/A
N/A
N/A

Fix Localisation Issues

---

spec/__mocks__/electron.ts
spec/childWindowHandle.spec.ts
spec/chromeFlags.spec.ts

Typescript chromeflags unittest

---

js/menus/menuTemplate.js

Alter the safety check to make sure the window is actually focused [ELECTRON-1100](https://perzoinc.atlassian.net/browse/ELECTRON-1100)
Separate the window safety check to make sure the window is actually focused
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/622)

ELECTRON-1100 (Add safety check for toggle developer tools)

---

package.json

Support New Field for Indexing
This fixes the below bugs
[SEARCH-1346](https://perzoinc.atlassian.net/browse/SEARCH-1346)
[SEARCH-1294](https://perzoinc.atlassian.net/browse/SEARCH-1294)
- Message renderer required fields missing from the index.
- Includes new library which supports indexing any fields inside `renderingBlob` so that we no longer required to change the library if any new fields are added to message object.
N/A
N/A
SFE-Client-App | branch-name | [PR #14184](https://github.com/SymphonyOSF/SFE-Client-App/pull/14184)
Swift-Search | branch-name | [PR #12](https://github.com/symphonyoss/SwiftSearch/pull/12) …

SEARCH-1346 - Support New Field for Indexing

---

spec/__mocks__/electron.ts
spec/dialogHandler.spec.ts

dialog handler unit test
N/A
N/A
N/A

dialog handler unit test

---

demo/download-manager.css
demo/index.html
package.json
spec/__snapshots__/loadingScreen.spec.ts.snap
spec/appMenu.spec.ts
spec/downloadManager.spec.ts
src/app/app-menu.ts
src/app/auto-launch-controller.ts
src/app/child-window-handler.ts
src/app/config-handler.ts
src/app/main-api-handler.ts
src/app/window-handler.ts
src/app/window-utils.ts
src/common/api-interface.ts
src/common/i18n-preload.ts
src/common/i18n.ts
src/common/utils.ts
src/common/whitelist-handler.ts
src/renderer/app-bridge.ts
src/renderer/components/download-manager.tsx
src/renderer/components/loading-screen.tsx
src/renderer/desktop-capturer.ts
src/renderer/notification.ts
src/renderer/preload-main.ts
src/renderer/ssf-api.ts
src/renderer/styles/loading-screen.less
src/renderer/styles/theme.less

- Auto Launch
- First-time launch
- Basic Auth
- Desktop capturer
- Code documentation
- Network error handler

Typescript (Fix issues and add support for BC)

---

spec/__mocks__/electron.ts
spec/mainApiHandler.spec.ts

main api handler unit test
N/A
N/A
N/A

main api handler unit test

---

demo/index.html
package.json
spec/mainApiHandler.spec.ts
spec/protocolHandler.spec.ts
src/app/app-menu.ts
src/app/crypto-handler.ts
src/app/main-api-handler.ts
src/app/main.ts
src/app/protocol-handler.ts
src/app/spell-check-handler.ts
src/app/window-handler.ts
src/common/api-interface.ts
src/renderer/preload-main.ts

- Fixed spellchecker module
- Bumped up electron version to 5.x
- Update unit test case
- Updated app menu to support 5.x
- Fixed protocol handler
- Demo content for language changes
- Demo content for protocol handler

Typescript (Fix spellchecker issue and bump electron version)

---

demo/index.html
spec/utils.spec.ts
src/app/main.ts
src/app/screen-snippet-handler.ts
src/app/window-handler.ts
src/app/window-utils.ts
src/common/api-interface.ts
src/common/i18n-preload.ts
src/common/i18n.ts
src/common/utils.ts
src/renderer/components/notification-settings.tsx
src/renderer/desktop-capturer.ts
src/renderer/notification.ts
src/renderer/styles/snack-bar.less

- Fixed screen snippet
- Fixed string format function
- Update unit test
- Snack bar style
- Fix display selection in the notification settings
- The logic to clean up child windows on before unload
- The logic to check media permissions

Typescript (Added logic to clean up child windows)

---

demo/index.html
installer/win/Symphony-x64.aip
installer/win/Symphony-x86.aip
package.json
spec/childWindowHandle.spec.ts
src/app/child-window-handler.ts
src/app/window-actions.ts
src/app/window-handler.ts
src/renderer/preload-main.ts

- Child window security
- Child window permissions
- Bump SwiftSearch version to 5.0.0-beta.1
- Fix bound changes logic

Typescript (Fix bound changes and update child window security)

---

demo/index.html
demo/win.html
spec/activityDetection.spec.ts
src/app/activity-detection.ts
src/app/app-menu.ts
src/app/auto-launch-controller.ts
src/app/main-api-handler.ts
src/app/main.ts
src/app/memory-monitor.ts
src/app/screen-snippet-handler.ts
src/app/window-actions.ts
src/app/window-handler.ts
src/app/window-utils.ts
src/common/animation-queue.ts
src/common/api-interface.ts
src/common/logger.ts
src/renderer/app-bridge.ts
src/renderer/components/windows-title-bar.tsx
src/renderer/preload-main.ts
src/renderer/ssf-api.ts
src/renderer/styles/snack-bar.less

- Implemented memory refresh logic
- Optimized loading styles
- Register global shortcuts for `devtools`

Typescript (Optimize loading styles & register global shortcuts)

---

package.json
src/common/api-interface.ts
src/renderer/app-bridge.ts
src/renderer/ssf-api.ts

Complete workflow of context-isolation
[SEARCH-1428](https://perzoinc.atlassian.net/browse/SEARCH-1428)
[SEARCH-1313](https://perzoinc.atlassian.net/browse/SEARCH-1313)
N/A
N/A
branch | PR
Swift-Search | [#15](https://github.com/symphonyoss/SwiftSearch/pull/15)
Attach unit in PDF format against the above task lists for this branch

SEARCH-1428 (Complete workflow of context-isolation)

---

js/windowMgr.js

Add safety checks for did-finish-load events
[ELECTRON-1208](https://perzoinc.atlassian.net/browse/ELECTRON-1208)
Early exit `did-finish-load` if the window is already been closed.

ELECTRON-1208 (Add safety checks for did-finish-load events)

---

js/activityDetection/index.js
js/badgeCount.js
js/log.js
js/memoryMonitor.js
js/windowMgr.js
tests/log.test.js

Added safety checks for logger window
[ELECTRON-1239](https://perzoinc.atlassian.net/browse/ELECTRON-1239)
- Activity detection
- Badge count
- Log
- Memory monitor
- Bound changes 
branch | PR
3.x (previous safety checks) | [link](https://github.com/symphonyoss/SymphonyElectron/pull/641)

ELECTRON-1239 (Add safety checks for logger)

---

src/app/config-handler.ts
src/app/window-handler.ts
src/app/window-utils.ts

Fix main window position calculation logic
Add safety checks and fix the config interface

Typescript (Fix main window position calculation logic)

---

package.json
src/app/app-menu.ts
src/app/config-handler.ts
src/app/init.ts

Fix custom user data path and menu item arrangements
- Config: Create a init file to initialize `userData` path before the app start 
- Menu: Rearrange and include memory refresh menu item

Typescript (Fix custom user data path and menu items)

---

js/moreInfo/index.js
js/moreInfo/more-info.html
js/moreInfo/renderer.js
locale/en-US.json
locale/en.json
locale/fr-FR.json
locale/fr.json
locale/ja-JP.json
locale/ja.json

Fix localization for more information window
Include translation
- "More Information": "Plus d’informations",
- "Version Information": "Information sur la version"
- "More Information": "詳しくは",
- "Version Information": "バージョン情報"
branch | PR
Master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/657)

ELECTRON-1213 (Fix localization for more information window)

---

src/app/init.ts

Set env path on app start child_process issue refer -> `https://github.com/electron/electron/issues/7688`
N/A
N/A

Set env path on app start child_process issue

---

src/app/config-handler.ts
src/app/window-actions.ts

Main window bound changes weren't updated to the user config file
Update the user config file whenever there is bound change

Typescript (Fix bound changes issue with main window)

---

package.json

Swift Search create search queries in SFE-client instead of Electron
[SEARCH-1502](https://perzoinc.atlassian.net/browse/SEARCH-1502)
- Considering that Electron will be released less frequently than SFE/SBE, we should move the query generation logic to SFE. Therefore we can add features/fix bugs easily to Swift Search. 
N/A
N/A
N/A
SFE-Client-App | master | [PR #14884](https://github.com/SymphonyOSF/SFE-Client-App/pull/14884)
SFE-Client-App | SEARCH-1502-context | [PR #4](https://github.com/KiranNiranjan/SFE-Client-App/pull/4)
SymphonyElectron | SEARCH-1502-master | [PR …

SEARCH-1502 - Swift Search create search queries in SFE-client instead of Electron

---

src/app/main-api-handler.ts
src/app/window-handler.ts
src/common/api-interface.ts
src/renderer/app-bridge.ts
src/renderer/desktop-capturer.ts
src/renderer/preload-main.ts

Fix issues with setting the window origin
Set the origin by making `sync` call to the main process

Typescript (Fix issues with setting the window origin)

---

spec/utils.spec.ts
src/app/config-handler.ts
src/app/init.ts
src/app/stats.ts
src/common/utils.ts

Fix throttle issue and update stats logs
- Fix issue with the throttle where some func calls were ignored
- Update the stats config logs

fix: Typescript (Fix throttle issue and update stats logs)

---

demo/index.html
spec/mainApiHandler.spec.ts
src/app/child-window-handler.ts
src/app/main-api-handler.ts
src/app/window-handler.ts
src/app/window-utils.ts
src/common/api-interface.ts
src/renderer/app-bridge.ts
src/renderer/components/notification-comp.tsx
src/renderer/notification-ssf-hendler.ts
src/renderer/notification.ts
src/renderer/ssf-api.ts

Fix issues with notification and origin 
[ELECTRON-1022](https://perzoinc.atlassian.net/browse/ELECTRON-1022)
- Assign global config URL to the browser window to use the value in preload even before page load
- Fix notification data missing in the browser window object

fix: ELECTRON-1022 (Fix issues with notification and origin)

---

package.json
src/app/crypto-handler.ts
src/renderer/ssf-api.ts

Contest-isolation was not merged to R55.2 so reverting this changes
N/A
N/A

revert: ffi and version changes

---

demo/index.html
spec/appMenu.spec.ts
src/app/app-menu.ts
src/app/window-actions.ts
src/common/logger.ts
src/renderer/notification-ssf-hendler.ts

Fix issues with notification, menu & logger modules
- By default set the menu visibility to `false` for Windows
- Pass the correct `id` & `title` to the notification module
- Fix javascript error with logger by adding safety checks

fix: Typescript (Fix issues with notification, menu & logger modules)

---

src/app/child-window-handler.ts
src/app/window-actions.ts
src/app/window-handler.ts
src/locale/en-US.json
src/locale/en.json
src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json

Handle session permissions
[ELECTRON-1238](https://perzoinc.atlassian.net/browse/ELECTRON-1238)
Verify global config's permissions field and prevent access to some properties
Notes: Add support for handling session permissions for media and others

fix: ELECTRON-1238 (Handle session permissions)

---

config/Symphony.config
src/app/config-handler.ts
src/app/window-handler.ts

Make Context Isolation configurable
[ELECTRON-1332](https://perzoinc.atlassian.net/browse/ELECTRON-1332)
Add a flag `contextIsolation: false` in `Symphony.config` global configuration file and use that to set the context isolation feature on all the browser windows.
Notes: Make Context Isolation configurable via global config file

feat: ELECTRON-1332 (Make Context Isolation configurable)

---

package.json

Swift Search ThreadAPI client interaction with throttling
[SEARCH-1565](https://perzoinc.atlassian.net/browse/SEARCH-1565)
[SEARCH-1564](https://perzoinc.atlassian.net/browse/SEARCH-1564)
Please refer implementation doc here -> https://perzoinc.atlassian.net/wiki/spaces/SEARCH/pages/595788140/Swift+Search+-+Throttling+ThreadAPI+for+Request+Bursts
N/A
N/A
N/A
N/A
SwiftSearch | branch-name | [PR #29](https://github.com/symphonyoss/SwiftSearch/pull/29)
SFE-Client-App | branch-name | [PR #15380](https://github.com/SymphonyOSF/SFE-Client-App/pull/15380)
[comment]: # (When resolved, check the box and explain the answer.)
N/A

feat: SEARCH-1565 - Swift Search - ThreadAPI client interaction with throttling

---

package.json

Add safety check for deleting real-time index (safety check)
N/A
branch | PR
Swift-Search | [link]()

fix: Add safety check for deleting real-time index (safety check)

---

src/app/analytics-handler.ts
src/app/app-menu.ts

Update the menu element text casing
[ELECTRON-1331](https://perzoinc.atlassian.net/browse/ELECTRON-1331)
- To follow the same standards across elements 
- Track initial menu settings

fix: ELECTRON-1331 (Update the menu element text casing)

---

src/app/init.ts
src/app/main.ts
src/app/spell-check-handler.ts

Fixes multiple instances issue
[ELECTRON-1358](https://perzoinc.atlassian.net/browse/ELECTRON-1358)
Move setting shell path to main.ts to prevent multiple instance issue

fix: ELECTRON-1358 (Fix Multiple instance issue)

---

package.json

Bump release version `1.55.3-rc.1`
N/A
branch | PR
Swift-Search | [#31](https://github.com/symphonyoss/SwiftSearch/pull/31)

fix: Bump release version `1.55.3-rc.1`

---

src/renderer/components/notification-comp.tsx

Disable context menu for notification windows
[ELECTRON-1037](https://perzoinc.atlassian.net/browse/ELECTRON-1037)
Add context menu listener for notification DOM element and prevent default

fix: ELECTRON-1037 (Disable context menu for notification windows)

---

src/app/window-utils.ts

Fix pop up menu position
[ELECTRON-1363](https://perzoinc.atlassian.net/browse/ELECTRON-1363)
Modify the `x, z` coordinates to fix the issue

fix: ELECTRON-1363 (Fix pop up menu position)

---

src/app/window-actions.ts

Fix issue with saving window state
[ELECTRON-1364](https://perzoinc.atlassian.net/browse/ELECTRON-1364)
Throttle window maximized and unmaximized state

fix: ELECTRON-1364 (Fix issue with saving window state)

---

src/app/window-handler.ts

Fix always on top issue when relaunched 
[ELECTRON-1367](https://perzoinc.atlassian.net/browse/ELECTRON-1367)
Set the `alwaysOnTop` property when the window is created

fix: ELECTRON-1367 (Fix always on top issue when relaunched)

---

src/app/main.ts

Prevent javascript error related to screen module
[ELECTRON-1366](https://perzoinc.atlassian.net/browse/ELECTRON-1366)
Change from `app.quit()` to `app.exit()`. read more here https://github.com/electron/electron/issues/8862

fix: ELECTRON-1366 (Prevent javascript error related to screen module)

---

src/app/config-handler.ts
src/app/window-actions.ts

Optimize and fix window bounds update issue
[ELECTRON-1364](https://perzoinc.atlassian.net/browse/ELECTRON-1364)
An issue where `maximize` & `resize` events emits at the same time which causes updateConfig to write to a file inconsistently
branch | PR
SymphonyElectron | [#710](https://github.com/symphonyoss/SymphonyElectron/pull/710)

fix: ELECTRON-1364 (Optimize and fix window bounds update issue)

---

src/renderer/components/notification-comp.tsx
src/renderer/notification.ts

Add logic to persist notification on mouse over
[ELECTRON-1344](https://perzoinc.atlassian.net/browse/ELECTRON-1344)
Add logic to persist notification on mouse over

fix: ELECTRON-1344 (Add logic to persist notification on mouse over)

---

src/renderer/components/windows-title-bar.tsx

Update DOM when ever custom title bar updates
[ELECTRON-1339](https://perzoinc.atlassian.net/browse/ELECTRON-1339)
Update the `margin-top` property when title bar renders

fix: ELECTRON-1339 (Update DOM when ever custom title bar updates)

---

src/renderer/components/notification-comp.tsx
src/renderer/styles/notification-comp.less

Update notification text color to match previous version
Set notification text color to `#000000`

fix: ELECTRON-1346 (Update notification text color to match previous version)

---

src/app/window-handler.ts
src/app/window-utils.ts

Fixes pop-up menu position for native title bar
[ELECTRON-1380](https://perzoinc.atlassian.net/browse/ELECTRON-1380)
Update coordinates based on the custom title bar settings

fix: ELECTRON-1380 (Fix pop-up menu position for native title bar)

---

package.json

Fix sort order check.
N/A
N/A
branch | PR
Swift-Search | [#32](https://github.com/symphonyoss/SwiftSearch/pull/32)
SFE-Client-App | [link]()

fix: SEARCH-1582 - Fix sort order check

---

spec/dialogHandler.spec.ts
src/app/window-actions.ts
src/app/window-handler.ts
src/renderer/notification.ts

Fixes notification z-index when alwaysOnTop is enabled
[ELECTRON-1382](https://perzoinc.atlassian.net/browse/ELECTRON-1382)
Bring active notifications to front
Notes: Fixes notification z-index when alwaysOnTop is enabled

fix: ELECTRON-1382 (Fix notification z-index when alwaysOnTop is enabled)

---

src/renderer/app-bridge.ts

Add backward support for RTC v1
[ELECTRON-1392](https://perzoinc.atlassian.net/browse/ELECTRON-1392)
Broadcast new events to backward support RTC v1
SFE-Client-App | ELECTRON-1370 | [PR #15515](https://github.com/SymphonyOSF/SFE-Client-App/pull/15515)

fix: ELECTRON-1392 (Add backward support for RTC v1 api)

---

spec/mainApiHandler.spec.ts
src/app/main-api-handler.ts
src/app/window-actions.ts
src/app/window-utils.ts

Display pop-up menu only on the main window
[ELECTRON-1380](https://perzoinc.atlassian.net/browse/ELECTRON-1380)
Add check to verify the `winName` to display the pop-up menu only on the main window

fix: ELECTRON-1380 (Show pop-up menu only on main window)

---

src/app/app-menu.ts

Fix dev tools disabled localisation
[ELECTRON-1400](https://perzoinc.atlassian.net/browse/ELECTRON-1400)
Adjust the message string in `app-menu` component.

fix: ELECTRON-1400: fix dev tools disabled localisation

---

src/renderer/components/windows-title-bar.tsx

Reverts symphonyoss/SymphonyElectron#721 As these changes are not required due to accessibility

revert: "fix: ELECTRON-1369 (Set custom title bar's title once)"

---

src/renderer/components/notification-comp.tsx

Add support for flashing notification
[ELECTRON-1394](https://perzoinc.atlassian.net/browse/ELECTRON-1394)
`SetInterval` and switch notification background-colour

fix: ELECTRON-1394 (Add support for flashing notification)

---

src/app/window-actions.ts

Fix issue in windows menu popping up for custom title bar
[ELECTRON-1406](https://perzoinc.atlassian.net/browse/ELECTRON-1406)
Add an extra check (to see if we have custom title bar) while triggering the pop up menu when "Alt" key is pressed.

fix: ELECTRON-1406: fix issue in windows menu popping up for custom title bar

---

src/app/main.ts
src/renderer/styles/notification-comp.less

Fix notification fonts and safety checks for setAboutPanel
[ELECTRON-1346](https://perzoinc.atlassian.net/browse/ELECTRON-1346)
- Change the notification text fonts to `sans-serif`
- Add safety checks for `setAboutPanel`

fix: ELECTRON-1346 (Fix notification fonts and safety checks for setAboutPanel)

---

src/app/child-window-handler.ts
src/app/window-actions.ts

Fix issues with restoring pop-out window
[ELECTRON-1401](https://perzoinc.atlassian.net/browse/ELECTRON-1401)
[ELECTRON-1417](https://perzoinc.atlassian.net/browse/ELECTRON-1417)
[ELECTRON-1404](https://perzoinc.atlassian.net/browse/ELECTRON-1404)
Send bound changes to the client as soon as the child window is created so that the client registers the pop-out window creation

fix: ELECTRON-1401 (Fix issues with pop-out window restore)

---

package.json

Bump index-version & Fix large index size
branch | PR
SwiftSearch | [#33](https://github.com/symphonyoss/SwiftSearch/pull/33)

fix: Bump index-version & Fix large index size (With libraries)

---

src/renderer/notification.ts

Fixes notification z-index & mouse hover issues
[ELECTRON-1425](https://perzoinc.atlassian.net/browse/ELECTRON-1425)
[ELECTRON-1405](https://perzoinc.atlassian.net/browse/ELECTRON-1405)
Clear displayTimer & move notification to the top when setting notification content

fix: ELECTRON-1425 & ELECTRON-1405 - (Fix notification z-index & mouse hover issues)

---

src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json

Update permissions localization strings for `ja-JP` & `fr-FR`
[ELECTRON-1418](https://perzoinc.atlassian.net/browse/ELECTRON-1418)

fix: ELECTRON-1418 (Update permissions localization strings)

---

spec/mainApiHandler.spec.ts
src/app/main-api-handler.ts
src/app/main.ts
src/app/version-handler.ts
src/app/window-handler.ts

When we redirect to a different POD, currently, the pod version doesn't get updated dynamically. This PR fixes that issue.
[ELECTRON-1431](https://perzoinc.atlassian.net/browse/ELECTRON-1431)
When a user logs in to a different POD, we register our electron specific APIs on SFE, we use this workflow to also update the pod version data on SDA.

fix: ELECTRON-1431: add logic to update pod version dynamically

---

src/renderer/components/network-error.tsx
src/renderer/components/notification-comp.tsx

Fix notification flashing issue and logo in network error
[ELECTRON-1451](https://perzoinc.atlassian.net/browse/ELECTRON-1451)
- Reset the notification flash interval
- update the new Symphony logo

fix: ELECTRON-1451 (Fix notification flashing issue and logo in network error)

---

package.json
src/app/crypto-handler.ts
src/app/memory-monitor.ts
src/renderer/preload-main.ts

Bump Electron version to 5.x
[ELECTRON-1327](https://perzoinc.atlassian.net/browse/ ELECTRON-1327)
- Bump Electron version to `5.0.8`
- Update API changes

feat: ELECTRON-1327 (Bump Electron version to 5.x)

---

spec/__snapshots__/basicAuth.spec.ts.snap
src/renderer/components/basic-auth.tsx
src/renderer/components/network-error.tsx
src/renderer/styles/basic-auth.less
src/renderer/styles/network-error.less
src/renderer/styles/theme.less

Sets font-family dynamically based on locale
[ELECTRON-1171](https://perzoinc.atlassian.net/browse/ELECTRON-1171)
- Sets `font-family` based on locale
- Include some generic Japanese fonts

fix: ELECTRON-1171 (Sets font-family dynamically based on locale)

---

package.json
src/app/child-window-handler.ts
src/app/window-actions.ts
src/renderer/components/snack-bar.ts
src/renderer/preload-main.ts

Fix snack bar issue on Windows & Fix RTC pop-out issue
[ELECTRON-1389](https://perzoinc.atlassian.net/browse/ELECTRON-1389)
- Update snack bar rendering logic
- Fix RTC pop-out issue by whitelisting `about:blank#blocked`
Snack displays but hidden when RTC `full-screen` button is clicked on Windows

fix: ELECTRON-1389 (Fix snack bar issue on Windows & Fix RTC pop-out issue)

---

src/app/window-handler.ts
src/common/i18n.ts
src/renderer/components/windows-title-bar.tsx
src/renderer/preload-main.ts

Update i18n resources when page fail to load
[ELECTRON-1488](https://perzoinc.atlassian.net/browse/ELECTRON-1488)
- Load i18n resources even when the page fails to load
- Remove unwanted code

fix: ELECTRON-1488 (Update i18n resources when page fail to load)

---

src/app/child-window-handler.ts
src/app/protocol-handler.ts

Add checks for url length
[ELECTRON-1505](https://perzoinc.atlassian.net/browse/ELECTRON-1505)
Add checks for url length and restrict to 2083
N/A

fix: ELECTRON-1505: add checks for url length

---

src/app/child-window-handler.ts
src/app/protocol-handler.ts

Prevent opening links longer than 2083
[ELECTRON-1505](https://perzoinc.atlassian.net/browse/ELECTRON-1505)
- `PreventDefault` when the URL length is longer than 2083
branch | PR
SymphonyElectron | [#774](https://github.com/symphonyoss/SymphonyElectron/pull/774)

fix: ELECTRON-1505 (Prevent opening links longer than 2083)

---

README.md

chore: Align "Contributing" section in README.md to FINOS project blueprint

---

config/Symphony.config

By default enable context isolation feature

feat: Enable context isolation feature by default

---

src/app/activity-detection.ts

Prevent setting multiple intervals for activity detection
[SDA-1549](https://perzoinc.atlassian.net/browse/SDA-1549)
- Clear interval before starting a new one

fix: SDA-1549 (Prevent setting multiple intervals for activity detection)

---

src/app/memory-monitor.ts

fix: Fix printout of memoryInfo

---

src/common/logger.ts

Create app data directory manually
[SDA-1561](https://perzoinc.atlassian.net/browse/SDA-1561)
- First, create a main app directory to fix the issue with node `mkdir`

fix: SDA-1561 (Create app data directory manually)

---

package.json
spec/__snapshots__/aboutApp.spec.ts.snap
src/app/version-handler.ts
src/app/window-handler.ts
src/renderer/components/about-app.tsx

Show SFE version in about-window

---

src/renderer/components/windows-title-bar.tsx
src/renderer/styles/title-bar.less

Add margin-top dynamically for mana
[SDA-1510](https://perzoinc.atlassian.net/browse/SDA-1510)
This is a temporary solution to fix the custom title bar margin issue with mana until we discuss a solution for extension and communication with SDA in mana

fix: SDA-1510 (Add margin-top dynamically for mana)

---

src/renderer/preload-component.ts

Set document title for all the window
[JIRA-ticket](https://perzoinc.atlassian.net/browse/SDA-1581)
Set `document.title` for all the frameless window
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/803)

fix: SDA-1581 (Set document title for all the window)

---

package.json
src/app/init.ts
src/app/window-utils.ts

Add support for the chromium sandbox mode
[SDA-1588](https://perzoinc.atlassian.net/browse/SDA-1588)
- Enable chromium sandbox
- Add sandbox support for all the renderer process
- This terminates a stale process running when there is a termination of the main process

fix: SDA-1588 (Add support for chromium sandbox mode)

---

src/app/window-handler.ts
src/renderer/components/screen-sharing-frame.tsx
src/renderer/preload-component.ts
src/renderer/styles/screen-sharing-frame.less

feat: SDA-1553 Add screen-sharing-frame, for sharing screen

---

src/locale/en-US.json
src/locale/en.json
src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json

https://perzoinc.atlassian.net/browse/SDA-1498
branch | PR

fix: SDA-1498 L10N: "Press Esc to exit full screen" not localized

---

docs/development/DEV_SETUP.md
src/demo/README.md
src/demo/index.html
src/renderer/app-bridge.ts

[JIRA-ticket](https://perzoinc.atlassian.net/browse/SDA-1587)
As it is not possible to commit code which fix the issue (for security reasons) I have instead added instructions to the app itself as well as documentation on how to get it to work locally.
branch | PR

feat: SDA-1587 Broken functions in demo app

---

src/locale/en-US.json
src/locale/en.json
src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json
src/renderer/preload-component.ts

https://perzoinc.atlassian.net/browse/SDA-1591
branch | PR

fix: SDA-1591 Translate the window title for notification settings

---

installer/mac/preinstall.sh

We could not update Symphony on mac because the version was wrong

---

.gitignore
.travis.yml
package-lock.json
src/app/main.ts

Add package-lock.json to git & disable protocol register for dev env
- Add `package-lock.json` to git
- Disable protocol register for dev env

fix: Add package-lock.json to git & disable protocol register for dev env

---

src/app/app-menu.ts

Make the zoomin to work

---

src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/sda-1600 About: Unnecessary scroll bar displayed in About Symphony screen

fix: Made the about dialog wider, to fit long SBE-names

---

src/renderer/notification.ts

Setting window title at create time

---

src/app/window-handler.ts
src/renderer/styles/about-app.less

https://perzoinc.atlassian.net/browse/SDA-1600 About: Unnecessary scroll bar displayed in About Symphony screen

fix: Remove scroll if about windows fit, plus make it not resizable

---

src/renderer/components/about-app.tsx

Fix issue with clipboard module
[SDA-1620](https://perzoinc.atlassian.net/browse/SDA-1620)
- Access clipboard module via remote in a sandboxed renderer

fix: SDA-1620 (Access clipboard module via remote)

---

src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/SDA-1610

fix: https://perzoinc.atlassian.net/browse/SDA-1610

---

package.json
scripts/build-linux.sh
scripts/build-mac.sh
scripts/build-win32.bat
scripts/build-win64.bat

Add support to switch nodejs dynamically during the build
[SDA-1623](https://perzoinc.atlassian.net/browse/SDA-1623)
Use NVM to switch between Node versions
N/A

chore: SDA-1623: switch NodeJs dynamically during build

---

package.json

https://perzoinc.atlassian.net/browse/SDA-1637
https://perzoinc.atlassian.net/browse/SDA-1638
branch | PR

fix: Bumped up version number

---

src/app/app-menu.ts
src/app/dialog-handler.ts
src/app/spell-check-handler.ts
src/app/window-handler.ts
src/app/window-utils.ts
src/common/api-interface.ts
src/demo/index.html
src/renderer/app-bridge.ts
src/renderer/ssf-api.ts

Create API and logic to restart floater windows
[SDA-1435](https://perzoinc.atlassian.net/browse/SDA-1435)
Created an API that restarts the pop-out window by closing and reopening the window with persisted size and position
SFE-Client-App | SDA-1435 | [PR #16276](https://github.com/SymphonyOSF/SFE-Client-App/pull/16276)
SFE-Core | SDA-1435 | [PR #824](https://github.com/SymphonyOSF/SFE-Core/pull/824)

fix: SDA-1435 (Create API and logic to restart floater windows)

---

package-lock.json
scripts/build-linux.sh
scripts/build-mac.sh
scripts/build-win32.bat
scripts/build-win64.bat

Add snyk as part of the build process to run security tests
[SDA-1635](https://perzoinc.atlassian.net/browse/SDA-1635)
N/A
N/A

chore: SDA-1635: add snyk to builds

---

src/renderer/components/notification-comp.tsx
src/renderer/notification.ts

Fix inconsistent in mouse leave events
[SDA-1648](https://perzoinc.atlassian.net/browse/SDA-1648)
Fix inconsistent in mouse leave events by enabling the window to resize.
https://github.com/electron/electron/issues/611

fix: SDA-1648 (Fix mouse leave events on notification window)

---

spec/appMenu.spec.ts
src/app/app-menu.ts
src/app/screen-snippet-handler.ts
src/app/window-actions.ts

Disable AOT when using the screen snippet feature
[SDA-1651](https://perzoinc.atlassian.net/browse/SDA-1651)
- Toggle AOT feature when using the screen snippet

fix: SDA-1651 (Temporarily disable AOT when screen snippet is open)

---

src/app/window-handler.ts
src/app/window-utils.ts

Make `about app` a modal window
[SDA-1661](https://perzoinc.atlassian.net/browse/SDA-1661)
- Set the modal property to `true`
- Optimize the duplicate/repeated  code

fix: SDA-1661 (Make about app window a modal window)

---

package.json

fix: Update screen snippet

---

package.json

[JIRA-ticket](https://perzoinc.atlassian.net/browse/SDA-1663)
branch | PR

fix: Updated screen snippet version

---

src/app/window-actions.ts

Set level to modal-panel when in fullscreen
[SDA-1665](https://perzoinc.atlassian.net/browse/SDA-1665)
- Make the focused window's always on top level to `modal-panel` and reset it back to the default `floating` when the app exits the fullscreen state

fix: SDA-1665 (Set level to modal-panel when in fullscreen)

---

src/app/window-handler.ts

Backport https://github.com/symphonyoss/SymphonyElectron/pull/852
[SDA-1704](https://perzoinc.atlassian.net/browse/SDA-1704)

fix: SDA-1704 (Make Screen sharing indicator window closable)

---

src/renderer/components/download-manager.ts

Fix incorrect style formatting
[SDA-1500](https://perzoinc.atlassian.net/browse/SDA-1500)
Fix the style attribute with correct format

fix: SDA-1500 (Fix incorrect style formatting)

---

config/Symphony.config

Update Symphony.config to revert to `foundation-dev` from `corporate`

fix: Update Symphony.config

---

.dockerignore
Dockerfile
docs/development/DEV_SETUP.md
package-lock.json
package.json
src/app/app-menu.ts
src/common/logger.ts

Docker container for generating the Linux builds
[SDA-1570](https://perzoinc.atlassian.net/browse/SDA-1570)
- Generate Linux builds using a docker container

build: Complete docker setup for generating Linux builds

---

src/app/window-utils.ts

[SDA-1732](https://perzoinc.atlassian.net/browse/SDA-1732)
Checking for the existance of file before attempting to open it
branch | PR

fix: SDA-1732 Checking for the existance of file before attempting to open it

---

src/locale/fr-FR.json
src/locale/fr.json

https://perzoinc.atlassian.net/browse/sda-1737 L10N: "Stop sharing" is not aligned in French

fix: sda-1737: Change the translation of Stop Sharing

---

package.json

Version bump for snippet tool to get correct rendering of dropdown menus
[SDA-1744](https://perzoinc.atlassian.net/browse/SDA-1744)
branch | PR

fix: SDA-1744 Correct rendering of dropdown menus

---

src/app/child-window-handler.ts
src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/sda-1746 Popout: Pop-outs open maximized (Mac only)

fix: Sda 1746

---

installer/mac/symphony-mac-packager.pkgproj
package.json
scripts/build-mac.sh
src/app/window-handler.ts

feat: Adding external screen share indicator frame for Mac

---

src/app/window-utils.ts

Fix a conditional issue
[SDA-1792](https://perzoinc.atlassian.net/browse/SDA-1792)

fix: SDA-1792 (Fix conditional issue)

---

package.json
src/app/window-handler.ts

fix: Enabled window tracking for screen share indicator frame on mac

---

installer/mac/preinstall.sh

fix: Let build script set app-version instead of hardcording

---

src/app/window-utils.ts

Load the complete pod URL instead of hostname
[SDA-1778](https://perzoinc.atlassian.net/browse/SDA-1778)
Load the complete config pod URL instead of just the hostname

fix: SDA-1778 (Load the complete pod url instead of hostname)

---

package.json

[SDA-1836](https://perzoinc.atlassian.net/browse/SDA-1836)
branch | PR

fix: SDA-1836 Remove error logging when no error occured

---

package.json

[SDA-1841](https://perzoinc.atlassian.net/browse/SDA-1841)
branch | PR

fix: SDA-1841 Fixed misaligned frame

---

package-lock.json
package.json
src/app/window-actions.ts
src/app/window-utils.ts

Fix issues with whitelisting
- Add logs
- remove redundant prevent default
- fix i18n issue

fix: issues with whitelist

---

package-lock.json
package.json

Bump electron version to 6.1.8
[SDA-1858](https://perzoinc.atlassian.net/browse/SDA-1858)
https://github.com/electron/electron/compare/v6.1.5...v6.1.9

fix: SDA-1858 (bump electron version to 6.1.9 from 6.1.5)

---

package.json

[SDA-1841](https://perzoinc.atlassian.net/browse/SDA-1841)
branch | PR

fix: SDA-1841 Fixed misaligned indicator frame

---

src/app/chrome-flags.ts

[SDA-1863](https://perzoinc.atlassian.net/browse/SDA-1863)
branch | PR

fix: SDA-1863 Re-enable the --no-sandbox flag

---

installer/win/Symphony-x64.aip
installer/win/Symphony-x86.aip

Support cloud-config for silent installation
[SDA-1859](https://perzoinc.atlassian.net/browse/SDA-1859)
- Change the default install parameters to ENABLED/DISABLED
branch | PR
SymphonyElectron | [6.1.x](https://github.com/symphonyoss/SymphonyElectron/pull/919)

fix: SDA-1859 (Support cloud config for silent installation) [Windows]

---

installer/mac/postinstall.sh
installer/win/Mana-x64.aip
installer/win/Mana-x86.aip
installer/win/Symphony-x64.aip
installer/win/Symphony-x86.aip
src/app/app-menu.ts
src/app/window-handler.ts

Merge master into mana and apply cloud-config fix into mana.aip
[SDA-1859](https://perzoinc.atlassian.net/browse/SDA-1859)

fix: Merge master into mana and apply cloud-config fix into mana.aip

---

src/common/logger.ts

Fix an issue with removing unaccessible log files
[SDA-1885](https://perzoinc.atlassian.net/browse/SDA-1885)
Add a file exists check while deleting a file
N/A

fix: SDA-1885 Javascript Error on cleaning logs

---

src/common/api-interface.ts
src/demo/index.html
src/renderer/app-bridge.ts
src/renderer/ssf-api.ts

https://perzoinc.atlassian.net/browse/sda-1826 RTC: SDA didn't pick up microphone (Mac only)
https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-macos
mediaType String - Can be microphone, camera or screen.
Returns String - Can be not-determined, granted, denied, restricted or unknown.

feat: SDA-1826 Add new check-media-permission

---

src/app/config-handler.ts
src/common/utils.ts

Filter out empty array `[]`
[SDA-1884](https://perzoinc.atlassian.net/browse/SDA-1884)

fix: SDA-1884 (filter out empty arrays)

---

spec/autoLaunchController.spec.ts
src/app/auto-launch-controller.ts

Add cloud-config support for launch on the start
[SDA-1890](https://perzoinc.atlassian.net/browse/SDA-1890)
- Change the check to update the cloud-config changes
branch | PR
SymphonyElectron | [link](https://github.com/symphonyoss/SymphonyElectron/pull/935)

fix: SDA-1890 (Fix auto launch on startup for cloud config)

---

src/app/window-handler.ts

[SDA-1897](https://perzoinc.atlassian.net/browse/SDA-1897)
branch | PR

fix: SDA-1897 Screen share indicator frame not showing on Mac

---

src/app/window-handler.ts

[SDA-1897](https://perzoinc.atlassian.net/browse/SDA-1897)
branch | PR

fix: SDA-1897 Cherry picked commits for fix from master

---

src/renderer/notification.ts
src/renderer/preload-main.ts

fix: SDA-1268 (Workaround to exit fullscreen when notification is clicked)[RTC]

---

package.json

fix: SDA-1841  Fixing fullscreen issue on Mac

---

package.json

fix: SDA-1841 Fixing fullscreen issue on Mac

---

src/app/app-menu.ts

fix: SDA-1910 (Add safety checks for devtools menu item)

---

spectron/fixtures/robot-actions.ts
spectron/zoom.spec.ts

fix: Add spectron test for zoom functionality

---

src/app/window-handler.ts
src/app/window-utils.ts

Disable network refresh on Mana
[SDA-1904](https://perzoinc.atlassian.net/browse/SDA-1904)

fix: SDA-1904: disable network refresh on Mana

---

Dockerfile

Install new packages to support the latest SDA dependency

fix: Linux: (Install new packages to support latest SDA dependency)

---

spec/__mocks__/electron.ts
spec/__snapshots__/aboutApp.spec.ts.snap
spec/aboutApp.spec.ts
src/app/config-handler.ts
src/app/window-handler.ts
src/renderer/components/about-app.tsx

Add new fields for about-app window and clipboard
[SDA-1924](https://perzoinc.atlassian.net/browse/SDA-1924)
- Add pod URL to the about app UI
- Write global, user, cloud & filtered config data to the clipboard
**Clipboard Data:**
<details>
<summary>Click to expand</summary>
> {
"userConfig": {
"configVersion": "6.1.0",
"buildNumber": "0",
"minimizeOnClose": "NOT_SET",
"launchOnStartup": "ENABLED",
"alwaysOnTop": "DISABLED",
"bringToFront": "DISABLED",
"whitelistUrl": "*",
"isCustomTitleBar": "ENABLED",
"memoryRefresh": "ENABLED",
"memoryThreshold": "800",
"devToolsEnabled": true,
"ctWhitelist": [],
"podWhitelist": [],
"notificationSettings": {
"position": "upper-right",
"display": ""
},
"customFlags": {
"authServerWhitelist": "",
"authNegotiateDelegateWhitelist": "",
"disableGpu": false, …

feat: SDA-1924 (Add new fields for about-app window and clipboard)

---

src/app/config-handler.ts
src/app/window-handler.ts

Add logic to persist client switch between 1.5, 2.0 and 2.0 daily
[SDA-1932](https://perzoinc.atlassian.net/browse/SDA-1932)
Add parameter to user config to persist client switch across restarts
N/A

feat: SDA-1932: persist client switch

---

src/app/window-handler.ts

Add csrf token to 1.5 switch
[SDA-1938](https://perzoinc.atlassian.net/browse/SDA-1938)
#959

fix: SDA-1938: add csrf token to 1.5 switch

---

src/common/api-interface.ts
src/demo/index.html
src/renderer/app-bridge.ts
src/renderer/ssf-api.ts

Enable RTC team to measure cpu usage for audio / video calls

feat: Measure cpu

---

src/renderer/preload-main.ts

- Create a new window object `manaSSF`
- Expose all the SDA APIs via `context bridge`
[SDA-1699](https://perzoinc.atlassian.net/browse/SDA-1699)
branch | PR
SFE-Lite | [link](https://github.com/SymphonyOSF/SFE-Lite/pull/2250)

feat: SDA-1699 (Initial SDA - Mana extension bridge implementation)

---

package.json

[SDA-1951](https://perzoinc.atlassian.net/browse/SDA-1951)
branch | PR

fix: SDA-1951 Added version and product info to ScreenShareIndicatorFrame and ScreenSnippet

---

package.json
src/app/screen-snippet-handler.ts
src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/SDA-1956 RTC: Missing red border when screen sharing whole screen
display_id is empty so we don't know what to share. In this case we will share screen 0.

fix: SDA-1956: RTC: Missing red border when screen sharing whole screen

---

package.json
src/app/screen-snippet-handler.ts
src/app/window-handler.ts

[SDA-2008](https://perzoinc.atlassian.net/browse/SDA-2008)
branch | PR

fix: SDA-2008: Invoke screen snippet tool with --no-annotate when running mana

---

package-lock.json
package.json

https://perzoinc.atlassian.net/browse/sda-2020 mediaDevices.enumerateDevices returns different deviceIds on every reload
Update Electron from 8.0.3 to 8.2.5
To get this fix from Electron https://github.com/electron/electron/issues/22144

fix: SDA-2020: Move to Electron 8.2.5 that has fix for enumerateDevices

---

src/app/download-handler.ts
src/app/window-utils.ts
src/demo/index.html
src/renderer/app-bridge.ts
src/renderer/components/download-manager.ts
src/renderer/ssf-api.ts

- Send a single item in place of an entire array when an item is downloaded
[SDA-2025](https://perzoinc.atlassian.net/browse/SDA-2025)
Related to #982

feat: SDA-2025: download manager single item api

---

package.json

[SDA-1970](https://perzoinc.atlassian.net/browse/SDA-1970)
branch | PR

fix: SDA-1970 Changed API call for getting window bounds

---

src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/sda-1738 RTC: Shared screen red border still shows after RTC diagnostics is completed
RTC diagnostic start/close screen share quickly add timeout for 300ms

fix: SDA-1738 RTC diagnotic start/close screen share quickly

---

src/renderer/components/windows-title-bar.tsx

Fix content overlap issue with MANA
[SDA-2057](https://perzoinc.atlassian.net/browse/SDA-2057)
Update styles for few elements to fix the title bar overlap issue

fix: SDA-2057 (Update few styles to fix the title bar overlap issue)

---

package.json

[SDA-1970](https://perzoinc.atlassian.net/browse/SDA-1970)
branch | PR

fix: SDA-1970 Correct alignment when window is maximized

---

package-lock.json
src/app/config-handler.ts
src/app/window-handler.ts
src/renderer/preload-main.ts

- Currently, the welcome dialog is shown multiple times, this PR fixes the issue.
[SDA-2056](https://perzoinc.atlassian.net/browse/SDA-2056)
Write build number to user config file upon new install.
N/A

fix: SDA-2056: welcome dialog issue

---

src/common/api-interface.ts
src/demo/index.html
src/renderer/components/notification-comp.tsx
src/renderer/notification-handler.ts
src/renderer/notification.ts
src/renderer/styles/notification-comp.less

Redesign Notification
[SDA-1991](https://perzoinc.atlassian.net/browse/SDA-1991)
- Redesign notifications for `mana` and `1.5`
- Support custom notification for Mac 🎉

feat: SDA-1991 (Redesign Notifications)

---

src/renderer/notification-handler.ts
src/renderer/preload-main.ts

Expose notification APIs `window.manaSSF`
[SDA-1973](https://perzoinc.atlassian.net/browse/SDA-1973)
Include `ShowNotification` & `hideNotification` mentods in `window.manaSSF`
branch | PR
SFE-Lite | [#2447](https://github.com/SymphonyOSF/SFE-Lite/pull/2447)

feat: SDA-1973 (Expose notifications APIs for mana)

---

config/titleBarStyles.css
src/renderer/components/notification-comp.tsx
src/renderer/styles/notification-comp.less

Make notification text colour black for 1.5
Update title bar style template
[SDA-2080](https://perzoinc.atlassian.net/browse/SDA-2080)

fix: SDA-2080 (Make notification text black for 1.5 and update style template)

---

src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/sda-1843 RTC: "You are sharing your screen" banner "x" close button should be easier to find

fix: sda-1843, remove the close button X

---

spec/childWindowHandle.spec.ts
src/app/child-window-handler.ts

https://perzoinc.atlassian.net/browse/sda-1971 Popout: Full Screen toggle not working for popped out windows (Mac only)

fix: sda-1971 make the pop-out full screen enable

---

src/app/config-handler.ts
src/app/screen-snippet-handler.ts
src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/sda-2121 Switch: Remove forcing and persistence mechanisms
Don't persist the SDA client switch
New parameter isMana to be used for mana features

fix: Do not persist the client switch, new parameter isMana

---

src/app/window-handler.ts
src/renderer/components/welcome.tsx

Set url valid to true when setting welcome screen url from user config
Caused by: #1009

fix: SDA-2056: fix welcome screen button

---

package.json

Update to Electron 9.0.2
Hopefully it will solve sda-2094

fix: Update to electron 9.0.2

---

src/app/window-handler.ts

We are quitting. If dev tools are open, close it
https://perzoinc.atlassian.net/browse/sda-2137 SDA 9.0.0 - Cannot close SDA when opening dev tool in separated window

fix: SDA-2137: Cannot close SDA when opening dev tool in separated window

---

package.json

[SDA-2142](https://perzoinc.atlassian.net/browse/SDA-2142)
branch | PR

fix: SDA-2142 Adding DPI awareness to fix border aligment

---

src/app/window-handler.ts

Parse and apply --windowSize command line argument (for testing)
[SDA-2160](https://perzoinc.atlassian.net/browse/SDA-2160)
branch | PR

fix: SDA-2160 Parse and apply --windowSize command line argument

---

src/renderer/components/windows-title-bar.tsx

Update the CSS property as per the web client changes
[SDA-2193](https://perzoinc.atlassian.net/browse/SDA-2193)
[SDA-2176](https://perzoinc.atlassian.net/browse/SDA-2176)
- Update the target CSS

fix: SDA-2193 (Update the CSS property as per the web client changes)

---

installer/mac/intro.html

[SDA-2232](https://perzoinc.atlassian.net/browse/SDA-2232)
branch | PR

fix: SDA-2232 Remove extra blank line in installer dialog

---

package.json

chore: bump version to 9.0.1

---

config/Symphony.config
docs/features/config-file.md
src/app/app-menu.ts
src/app/child-window-handler.ts
src/app/config-handler.ts
src/app/window-handler.ts
src/locale/en-US.json
src/locale/en.json
src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json

revert: "Add parameter to push the renderer logs inside the SDA-logs"

---

package.json
src/app/memory-monitor.ts

- Update the system idle time check method
- Bump SDA version to `9.0.1`
[SDA-2285](https://perzoinc.atlassian.net/browse/SDA-2285)
Change the method name

fix: SDA-2285 (Update system idle time API and bump version to 9.0.1)

---

config/Symphony.config
src/app/config-handler.ts
src/app/window-handler.ts
src/renderer/preload-main.ts

- Add new config filed for whitelisting origin
https://perzoinc.atlassian.net/wiki/spaces/SDA/pages/598934184/SDA+Configuration+Options
- Fixes a use case where sso URL is different from the pod URL

fix: SDA-2287 (Only create context bridge when CI is enabled and create new config filed for defining origin)

---

src/app/main.ts

https://perzoinc.atlassian.net/browse/sda-2302 Clicking on Symphony icon in the dock opens multiple app (MAC only)

fix: SDA-2302 only start main window one time

---

src/app/child-window-handler.ts

Apply contextOriginUrl for pop-out windows as well
[SDA-2301](https://perzoinc.atlassian.net/browse/SDA-2301)
branch | PR
master | [link](https://github.com/symphonyoss/SymphonyElectron/pull/1039)

fix: SDA-2301 (Apply contextOriginUrl for pop-out windows as well)

---

src/app/memory-monitor.ts

Update API from `querySystemIdleTime` to `getSystemIdleTime`
[SDA-2330](https://perzoinc.atlassian.net/browse/SDA-2330)

fix: SDA-2330 (Update API from querySystemIdleTime to getSystemIdleTime)

---

docs/development/DEV_SETUP.md

Update documentation for the Dev setup

docs: update documentation for the dev setup

---

package.json

Bump SDA version to 9.2.0
[SDA-2345](https://perzoinc.atlassian.net/browse/SDA-2345)

chore: SDA-2345 (Bump SDA version to 9.2.0)

---

spec/chromeFlags.spec.ts
src/app/chrome-flags.ts

feat: SDA-2315: add chrome flag for network in process

---

spec/chromeFlags.spec.ts
src/app/chrome-flags.ts

Reverts symphonyoss/SymphonyElectron#1049

revert: SDA-2315: add chrome flag for network in process

---

package.json

fix: address RTC meeting failure

---

scripts/jenkins-win64.bat

Modified the build script to call the BuildWixSharpInstaller script, and archive the artifact (with the prefix Experimental-) along with the existing installer
[SDA-2386](https://perzoinc.atlassian.net/browse/SDA-2386)
branch | PR

feat: SDA-2386 Generate wix# installer as part of build

---

package.json

https://perzoinc.atlassian.net/browse/sda-2268 Upgrade ffi & lodash to address medium vulnerabilities

fix: sda-2268 address security risk pointed out by Snyk

---

src/app/chrome-flags.ts

https://perzoinc.atlassian.net/browse/sda-2417 Add E2EE encryption flag requested by RTC part2

fix: sda-2417 enable only RTC insertable streams

---

src/app/download-handler.ts
src/app/window-utils.ts

This PR changes the way file names are being sent to the SFE so that it is consistent with the OS file name.
[SDA-2443](https://perzoinc.atlassian.net/browse/SDA-2443)

fix: SDA-2443 Fixed incorrect file name in edge cases

---

installer/win/WixSharpInstaller/Symphony.cs

Adding registry key for protocol handlers, and a custom action to remove registry keys on installation (including keys added by SDA, like auto-launch)
[SDA-2393](https://perzoinc.atlassian.net/browse/SDA-2393)
branch | PR

feat: SDA-2393 Adding/removing registry keys

---

installer/win/WixSharpInstaller/Symphony.cs
installer/win/WixSharpInstaller/WelcomeDlg.cs

[SDA-2394](https://perzoinc.atlassian.net/browse/SDA-2394)
branch | PR
notes: SDA-2394 Commandline installation properties

feat: SDA-2394 Commandline installation properties

---

src/app/app-menu.ts
src/app/child-window-handler.ts
src/app/window-actions.ts
src/app/window-handler.ts
src/common/logger.ts

Optimize renderer logs and prevent sending renderer to cloud 
[SDA-2467](https://perzoinc.atlassian.net/browse/SDA-2467)
- Prevent renderer logs from send into the cloud
- Optimize reading `enableRendererLogs` once
notes: renderer logs performance improvement

fix: SDA-2467 (Optimize renderer logs and prevent sending renderer to cloud)

---

package.json
src/app/stats.ts

Backport of #1074 
notes: remove capturing extra system information

fix: SDA-2418: remove capturing extra system information

---

src/app/window-handler.ts

[SDA-2465](https://perzoinc.atlassian.net/browse/SDA-2465)
To ensure we are not reading outside of the array, we clamp the value to not be outside of valid indices for the array.
branch | PR

fix: SDA-2465 Clamping the display id to ensure we are not accessing outside the array

---

package.json
src/app/stats.ts

Backport of #1074 
notes: remove capturing extra system information

fix: SDA-2418: remove capturing all stats

---

installer/win/WixSharpInstaller/MaintenanceDlg.cs
installer/win/WixSharpInstaller/MaintenanceDlg.designer.cs
installer/win/WixSharpInstaller/Symphony.cs

Added custom dialog to maintenance flow to describe its function
[SDA-2396](https://perzoinc.atlassian.net/browse/SDA-2396)
Added custom dialog to maintenance flow
N/A
notes: Added custom dialog to the installer maintenance flow

feat: SDA-2396 Added custom dialog to maintenance flow

---

README.md
docs/development/DEV_SETUP.md

Update the setup guide to reflect the latest changes
N/A
N/A
notes: update setup guide

chore: update setup guide

---

package.json
spec/appCacheHandler.spec.ts
src/app/app-cache-handler.ts
src/app/dialog-handler.ts
src/app/main.ts
src/app/window-handler.ts
src/locale/en-US.json
src/locale/en.json
src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json

- Clean app cache on a fresh install of SDA to avoid upgradation problems [SDA-2559](https://perzoinc.atlassian.net/browse/SDA-2559)
- Clean app cache and restart SDA when it crashes or is unresponsive [SDA-2359](https://perzoinc.atlassian.net/browse/SDA-2359)
- Check the user data directory and delete all the files apart from the user config & cloud config files.
#1092 
notes: clean app cache on install & crash

feat: SDA-2559: clean app cache on install & crash

---

package.json
spec/appCacheHandler.spec.ts
src/app/app-cache-handler.ts
src/app/dialog-handler.ts
src/app/main.ts
src/app/window-handler.ts
src/locale/en-US.json
src/locale/en.json
src/locale/fr-FR.json
src/locale/fr.json
src/locale/ja-JP.json
src/locale/ja.json

Backport of #1091 
notes: clean app cache on install & crash

feat: SDA-2559: clean app cache on install

---

spec/appCacheHandler.spec.ts
src/app/app-cache-handler.ts

Backport of #1097 
Notes: Delete app cache on Install & Crash

fix: SDA-2559: Delete app cache on Install

---

scripts/jenkins-win64.bat

Adding signing of the msi for new installer.
[SDA-2390](https://perzoinc.atlassian.net/browse/SDA-2390)
Signing msi by calling a signing.bat script stored locally on build machine
Notes: Modified build script to call signing script on build machine

feat: SDA-2390 Modified build script to call signing script on build machine

---

src/app/app-menu.ts
src/app/window-utils.ts

https://perzoinc.atlassian.net/browse/sda-2657 SDA - Screen Share - Red border still showing after clearing cache and reloading app
notes: remove red frame and screen sharing indicator when reloading

fix: SDA-2657 remove red frame and screen sharing indicator when reloading

---

.vscode/launch.json
.vscode/tasks.json
package.json
spec/__snapshots__/snippingTool.spec.ts.snap
src/renderer/components/color-picker-pill.tsx
src/renderer/components/snipping-tool.tsx
src/renderer/styles/snipping-tool.less

This PR extends the state of the annotate tool while also adding a color picker tool.
[SDA-2532](https://perzoinc.atlassian.net/browse/SDA-2532)
notes: This is a note.

feat: SDA-2532 Work on state for annotate and adding color picker

---

spec/aboutApp.spec.ts
src/renderer/components/about-app.tsx

https://perzoinc.atlassian.net/browse/sda-2270 About App: Change "clientVersion" to "sbeVersion" when writing the data to the clipboard
notes: change clientVersion to sbeVersion

chore: SDA-2270: change clientVersion to sbeVersion

---

spec/mainApiHandler.spec.ts
src/app/main-api-handler.ts
src/app/window-handler.ts
src/app/window-utils.ts
src/common/api-interface.ts
src/renderer/preload-main.ts
src/renderer/ssf-api.ts

Add new API to set if is running in mana client
[SDA-2652](https://perzoinc.atlassian.net/browse/SDA-2652)
- Expose an API in window `setIsMana` for the client to set the value
branch | PR
SFE-Lite | [link](https://github.com/SymphonyOSF/SFE-Lite/pull/4678)
notes: added new API `setIsMana` for the client to set the value

feat: SDA-2652 (Add new API to set if running in mana client)

---

spec/__snapshots__/annotateArea.spec.tsx.snap
spec/__snapshots__/colorPickerPill.spec.tsx.snap
spec/__snapshots__/snippingTool.spec.ts.snap
spec/annotateArea.spec.tsx
spec/colorPickerPill.spec.tsx
spec/snippingTool.spec.ts
src/app/window-handler.ts
src/renderer/components/annotate-area.tsx
src/renderer/components/color-picker-pill.tsx
src/renderer/components/snipping-tool.tsx
src/renderer/styles/snipping-tool.less
tslint.json

WIP! This PR adds possibility to annotate a screen shot.
Left to fix:
* Clear
* Erase
* Done
[SDA-2533](https://perzoinc.atlassian.net/browse/SDA-2533)
notes: add annotate to screenshot

feat: SDA-2533 add annotate to screenshot

---

spec/__snapshots__/snippingTool.spec.ts.snap
spec/utils.spec.ts
src/app/window-handler.ts
src/common/utils.ts
src/renderer/components/snipping-tool.tsx
src/renderer/styles/snipping-tool.less

- Resize image based on screen size
[SDA-2644](https://perzoinc.atlassian.net/browse/SDA-2644)
- Calculate the screen and image height
Notes: Fix the screen snippet window size issue

fix: SDA-2644 (Fix snippet window resize issue based on screen size)

---

package.json
src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/sda-2694 [Point72] blank screen
https://perzoinc.atlassian.net/wiki/spaces/SDA/pages/1383925138/2020-11-17+Point72

fix: Sda 2694 2

---

src/app/window-handler.ts

https://perzoinc.atlassian.net/browse/SDA-2694

fix: setBounds make the application unresponsive and not usable
